PCGen/pcgen

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_companion.lst
=> Greensting should have +4 Initiative

data/pathfinder_pfs/paizo/campaign_setting/pfs_inner_sea_bestiary/pfs_inner_sea_bestiary.pcc, data/pathfinder_pfs/paizo/pathfinder_society/organized_play/_guide_to_pathfinder_society_organized_play.pcc
=> DATA-2309 Add Inner Sea Bestiary to PFS

.travis.yml
Run a test, datatest and pfinttest after each commit to the pcgen repo.
=> Add travis-ci for the pcgen repo

code/src/java/plugin/pretokens/parser/PreBaseSizeParser.java, code/src/java/plugin/pretokens/parser/PreSizeParser.java, code/src/test/pcgen/persistence/lst/PObjectLoaderTest.java, code/src/test/pcgen/persistence/lst/output/prereq/PrerequisiteWriterTest.java
- Fix how SIZE is checked (not hard fail) due to use in SIZEADJUSTMENT
file (order of operations race condition)
- Some test fixes
Note: "Bob" is still broken due to PCG load issues
=> NEWTAG-476

code/src/java/pcgen/output/wrapper/CDOMReferenceWrapper.java
=> NEWTAG-472

code/src/java/plugin/lsttokens/deprecated/RaceChooseLangautoToken.java, code/src/java/plugin/lsttokens/deprecated/TemplateChooseLangautoToken.java
=> NEWTAG-340

code/src/java/pcgen/core/DataSet.java, code/src/java/pcgen/facade/core/DataSetFacade.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/gui2/facade/DelegatingDataSet.java, code/src/test/pcgen/gui2/facade/MockDataSetFacade.java
in purchase screen to be bought
=> Fix bug: CODE-2669 - Newly created custom items don't show up

code/src/test/pcgen/io/PCGVer2ParserCharacterTest.java
=> NEWTAG-475

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_companionmods.lst
=> DATA-2389: [PFCR] Druid bonus animal trick formula off by one

data/pathfinder/paizo/player_companion/animal_archive/anar_races.lst
Fixed typo in internal ability name for Skunk claw
=> DATA-2393: Animal Archive load errors

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst
Simple patch for the current ACG work
=> Archetype Support for ACG

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst
=> Correct reference .MOD

data/pathfinder/dreamscarred_press/ultimate_psionics/ultimate_psionics.pcc, data/pathfinder/dreamscarred_press/ultimate_psionics/up_feats_apg.lst
- Added dependency on PFCR
- Fixed missing CATEGORY=FEAT on some feat .mods
=> DATA-2432 Ultimate Psionics Load Errors

docs/listfilepages/datafilestagpages/datafilesequipment.html, docs/listfilepages/datafilestagpages/datafilesequipmentmodifiers.html, docs/walkthroughpages/walkthroughcreatecharacter.html
=> Docs - spelling

data/pathfinder/homebrew/my_homebrew/my__campaign.pcc, data/pathfinder/homebrew/my_homebrew/my_abilities.lst, data/pathfinder/homebrew/my_homebrew/my_classes.lst, data/pathfinder/homebrew/my_homebrew/my_companionmods.lst, data/pathfinder/homebrew/my_homebrew/my_deities.lst, data/pathfinder/homebrew/my_homebrew/my_equipmods.lst, data/pathfinder/homebrew/my_homebrew/my_profs_weapon.lst, data/pathfinder/homebrew/my_homebrew/my_races.lst, data/pathfinder/homebrew/my_homebrew/my_skills.lst, data/pathfinder/homebrew/my_homebrew/my_spells.lst, data/pathfinder/homebrew/my_homebrew/my_templates.lst, data/pathfinder/paizo/pathfinder_rpg_core.pcc
This is just adding to the Basic Loaders, and bringing the example files up to speed.
=> Background updates

code/src/java/pcgen/cdom/facet/fact/ChronicleEntryFacet.java, code/src/utest/pcgen/cdom/facet/fact/ChronicleEntryFacetTest.java
Allow multiple empty Chronicle Entries to exist on a PC
=> CODE-2861 - Campaign Story is not saved

code/src/java/pcgen/cdom/primitive/NegatingPrimitive.java
=> CODE-2835 Negating Primitive makes bad assumption of

docs/acknowledgments/outputsheets.html, docs/faqpages/faqyahooandhelping.html, docs/listfilepages/systemfilestagpages/gamemodemiscinfolist.html, docs/menupages/sources/sourcesinstalldataoptions.html, docs/menupages/sources/sourcessectionheading.html
Still many more broken links to fix.
=> Fix some broken links

docs/listfilepages/globalfilestagpages/globalfilesother.html
Documentation for #385.
See http://jira.pcgen.org/browse/DOCS-322
and http://jira.pcgen.org/browse/CODE-2866
=> DOCS-322 Update documentation for UDAM tag, following code change CODE-2866.

docs/faqpages/faqcommunity.html, docs/gmgen/preferences.html, docs/listfilepages/datafilestagpages/datafilesdomains.html, docs/listfilepages/datafilestagpages/datafilesequipment.html, docs/listfilepages/datafilestagpages/datafilesequipmentmodifiers.html, docs/listfilepages/datafilestagpages/datafilestemplates.html, docs/listfilepages/globalfilestagpages/globalfilesadd.html, docs/listfilepages/globalfilestagpages/globalfilesprexxx.html, docs/listfilepages/globalfilestagpages/globalfilesvariables.html, docs/listfilepages/listfileLSTstandards.html, docs/listfilepages/lstfileclass/lfc_lesson01_pcc.html, docs/listfilepages/lstfileclass/lfc_lesson05_race3.html, docs/listfilepages/lstfileclass/lfc_lesson13_feat2.html, docs/listfilepages/lstfileclass/lfc_lesson17_converting_feats_to_abilities.html, docs/listfilepages/lstfileclass/lfc_lesson18_HD_LEVEL_conversion.html, docs/listfilepages/rulesguide/grig_negative_levels.html, docs/listfilepages/systemfilestagpages/systemfilesbiosettingslist.html, docs/listfilepages/systemfilestagpages/systemfilestraitslist.html, docs/menupages/tools/toolsinstalldataset.html, docs/navlistindex.html, docs/tabpages/inventory/inventorygear.html, docs/tabpages/inventory/inventorysectionheading.html
Fixing of broken links continues.
=> Fix broken links 4

docs/listfilepages/systemfilestagpages/systemfilessizeadjustment.html, docs/listfilepages/systemfilestagpages/systemfilessizeadjustment.md
Implement documentation changes for new tag SIZENUM. Refer NEWTAG-480.
While I'm at it, re-write the entire document on `sizeAdjustment.lst` from scratch.
=> NEWTAG-480

code/src/java/pcgen/cdom/base/CategorizedAbilitySelectionChooseInformation.java, code/src/java/pcgen/cdom/base/CategorizedChooseInformation.java, code/src/java/pcgen/cdom/base/ChoiceSet.java, code/src/java/pcgen/cdom/choiceset/AbilityRefChoiceSet.java, code/src/java/pcgen/cdom/choiceset/CollectionToAbilitySelection.java, code/src/java/pcgen/cdom/enumeration/AssociationKey.java, code/src/java/pcgen/cdom/helper/AbilitySelector.java, code/src/java/pcgen/cdom/helper/AbilityTargetSelector.java, code/src/java/pcgen/cdom/list/AbilityList.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/kit/KitAbilities.java, code/src/java/plugin/lsttokens/AbilityLst.java, code/src/java/plugin/lsttokens/add/AbilityToken.java, code/src/java/plugin/lsttokens/choose/AbilitySelectionToken.java, code/src/java/plugin/lsttokens/choose/AbilityToken.java, code/src/java/plugin/lsttokens/deprecated/ChooseFeatSelectionToken.java, code/src/java/plugin/lsttokens/deprecated/ChooseFeatToken.java, code/src/java/plugin/lsttokens/deprecated/KitFeatToken.java, code/src/java/plugin/lsttokens/deprecated/RemoveFeatToken.java, code/src/java/plugin/lsttokens/deprecated/TemplateFeatToken.java, code/src/java/plugin/lsttokens/kit/ability/AbilityToken.java, code/src/test/pcgen/core/PCClassTest.java, code/src/test/pcgen/core/PCTemplateTest.java, code/src/test/pcgen/core/PObjectTest.java, code/src/utest/plugin/lsttokens/add/AbilityTokenTest.java
=> CODE-2829 - Make Ability Tokens Editor Friendly

code/src/java/plugin/lsttokens/SortKeyLst.java
Alternative method in the token of comparing that the resulting SORTKEY
list is valid (esp necessary on SortKeyRequired items)
=> Eliminate Duplicate concern in SORTKEY

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_abilities_class.lst
Add DEFINE to BONUS line for standard summoner in APG.
=> DATA-2521 [APG] Can't take standard summoner

code/src/java/plugin/lsttokens/skill/VisibleToken.java
=> NEWTAG-561

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_classes.lst
Replace Alchemist_Caster_Level with Caster_Level_Alchemist
=> DATA-2525: Fix typo in Alchemist caster level variables

data/pathfinder/paizo/roleplaying_game/bestiary_3/bestiary_3.pcc
Replace UM & UC PRECAMPAIGN with APG (all that's necessary)
=> DATA-2527: Changed dependencies to only those necessary for the source

data/pathfinder/paizo/roleplaying_game/advanced_class_guide/_advanced_class_guide.pcc, data/pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_equip.lst, data/pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_profs_weapon.lst
1) Fixed PRECAMPAIGN line
2) Removed WEAPONPROF .MODs which rely on ARG & B3, which are not required by the source
=> DATA-2528: Clean up dependencies in ACG

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/model/AlignmentFacet.java, code/src/java/plugin/exporttokens/deprecated/AlignmentToken.java
Add pc.alignment FreeMarker interpolation
=> NEWTAG-485 Deprecate ALIGNMENT and ALIGNMENT.SHORT output tokens

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/ColorToken.java
NEWTAG-491 Deprecate COLOR.HAIR output token
NEWTAG-492 Deprecate COLOR.SKIN output token
=> NEWTAG-490 Deprecate COLOR.EYE output token

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/MiscToken.java
NEWTAG-498 Deprecate MISC.COMPANIONS output token
NEWTAG-499 Deprecate MISC.ASSETS output token
NEWTAG-500 Deprecate MISC.MAGIC output token
=> NEWTAG-497 Deprecate MISC.GM output token

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/LanguagesToken.java
Languages already in model
This is deprecation only
Deprecate LANGUAGES output token
=> NEWTAG-509

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/WeaponProfsToken.java
WeaponProfs already in output model
This is deprecation only
Deprecate WEAPONPROFS output token
=> NEWTAG-510

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/CheckToken.java
Checks already in model, this is deprecation only
Deprecate CHECK output token
=> NEWTAG-512

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/DeityToken.java
Deity already in model, this is deprecation only
Deprecate DEITY output token
=> NEWTAG-514

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/DomainToken.java
Deprecate DOMAIN output token
DomainFact already in model, this is only deprecation
=> NEWTAG-515

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/RaceToken.java
Race model already implemented, this is just deprecation
=> NEWTAG-517

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/SizeLongToken.java, code/src/java/plugin/exporttokens/deprecated/SizeToken.java
Model already integrated, so this is just deprecation
=> NEWTAG-518

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/fact/GoldFacet.java, code/src/java/plugin/exporttokens/deprecated/GoldToken.java, code/src/test/plugin/exporttokens/GoldTokenTest.java
Deprecate GOLD output token
Add pc.gold to FreeMarker
=> NEWTAG-524

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/analysis/AgeSetFacet.java, code/src/java/pcgen/cdom/facet/fact/AgeFacet.java, code/src/java/pcgen/output/model/AgeSetModel.java, code/src/java/pcgen/output/wrapper/AgeSetWrapper.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/plugin/exporttokens/deprecated/AgeToken.java
Deprecate AGE.CATEGORY output token
Add pc.age as FreeMarker interpolation
Add pc.ageset as FreeMarker interpolation
=> NEWTAG-484

code/src/java/plugin/pretokens/parser/PreFactParser.java, code/src/java/plugin/pretokens/writer/PreFactWriter.java, code/src/utest/plugin/pretokens/PreFactRoundRobin.java
Fix bug: CODE-2886 - PREFACT with multiple criteria not parsed correctly
=> Code 2886 - PREFACT with multiple criteria

.gitignore
https://pcgenorg.atlassian.net/browse/CODE-2892
=> gitignore customsources

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/analysis/FavoredClassFacet.java, code/src/java/pcgen/cdom/facet/analysis/HasAnyFavoredClassFacet.java, code/src/java/plugin/exporttokens/deprecated/FavoredClassToken.java, code/src/java/plugin/exporttokens/deprecated/FavoredListToken.java
Deprecate FAVOREDCLASS, FAVOREDLIST
Add FavoredClassFacet and HasAnyFavoredClassFacet to model
=> NEWTAG-516

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/fact/CharacterTypeFacet.java, code/src/java/plugin/exporttokens/deprecated/CharactertypeToken.java
Deprecate CHARACTERTYPE output token
Support pc.charactertype in FreeMarker
=> NEWTAG-519

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/fact/GenderFacet.java, code/src/java/plugin/exporttokens/deprecated/GenderToken.java
Deprecate GENDER output token
Enable pc.gender in FreeMarker
=> NEWTAG-521

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/analysis/ReachFacet.java, code/src/java/plugin/exporttokens/deprecated/ReachToken.java
Deprecate REACH output token
Add pc.reach to FreeMarker
=> NEWTAG-523

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/fact/HeightFacet.java, code/src/java/plugin/exporttokens/deprecated/HeightToken.java
Deprecate HEIGHT output token
Add pc.height to FreeMarker
=> NEWTAG-522

code/pluginbuild.xml, code/src/java/plugin/exporttokens/deprecated/BRToken.java, code/src/java/plugin/exporttokens/deprecated/EndManualWhitespaceToken.java, code/src/java/plugin/exporttokens/deprecated/InvalidTextToken.java, code/src/java/plugin/exporttokens/deprecated/ManualWhitespaceToken.java, code/src/java/plugin/exporttokens/deprecated/PipeToken.java, code/src/java/plugin/exporttokens/deprecated/SpaceToken.java, code/src/test/plugin/exporttokens/SpaceTokenTest.java
Deprecate non-freemarker output controls
=> NEWTAG-526

outputsheets/base.xml.ftl, outputsheets/d20/fantasy/htmlxml/csheet_fantasy_std.htm.ftl, outputsheets/d20/fantasy/pdf/common_sheet/block_features.xslt, outputsheets/d20/fantasy/pdf/fantasy_master_common_blocks.xslt, preview/d20/fantasy/Standard.htm.ftl
Add OS block for "Prestige Awards"
=> OS-410 - add OS block for "Prestige Awards"

docs/acknowledgments/publishersandsources.html
=> Add info on Paizo Community Use Policy per Paul Grosse's request.

code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/output/base/NamedModel.java, code/src/java/pcgen/output/model/BooleanOptionModel.java, code/src/java/pcgen/output/publish/OutputDB.java, code/src/java/pcgen/system/PCGenSettings.java
Add ability to export preferences
=> NEWTAG-528 Export Using Output name preference

code/src/java/plugin/primitive/skill/UseUntrainedToken.java, code/src/utest/plugin/lsttokens/testsupport/AbstractPCQualifierTokenTestCase.java, code/src/utest/plugin/lsttokens/testsupport/TransparentPlayerCharacter.java, code/src/utest/plugin/primitive/skill/UseUntrainedTokenTest.java, code/src/utest/plugin/primitive/weaponprof/TypeTokenTest.java, code/src/utest/plugin/qualifier/ability/PCQualifierTokenTest.java, code/src/utest/plugin/qualifier/pcclass/PCQualifierTokenTest.java, code/src/utest/plugin/qualifier/skill/ClassQualifierTokenTest.java, code/src/utest/plugin/qualifier/skill/CrossClassQualifierTokenTest.java, code/src/utest/plugin/qualifier/skill/ExclusiveQualifierTokenTest.java, code/src/utest/plugin/qualifier/skill/NoRankQualifierTokenTest.java, code/src/utest/plugin/qualifier/skill/RanksQualifierTokenTest.java
=> CODE-2790 New Tests

code/pluginbuild.xml, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/output/base/ModeModelFactory.java, code/src/java/pcgen/output/factory/UnitSetModelFactory.java, code/src/java/pcgen/output/model/UnitSetModel.java, code/src/java/pcgen/output/publish/OutputDB.java, code/src/java/plugin/exporttokens/deprecated/UnitSetToken.java
NEWTAG-527 Export UnitSet as gamemode.unitset
Deprecate UNITSET output token
=> NEWTAG-527 Export UnitSet as gamemode.unitset

code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/character/SpellInfo.java
Fixed Concentration is never set in the code - removing unusable code
=> CODE-2790 Delete unused (unusable) code

code/src/java/pcgen/cdom/content/ContentDefinition.java, code/src/java/pcgen/cdom/content/UserContent.java, code/src/java/plugin/lsttokens/datacontrol/ExplanationToken.java
Prep work for Formula Parser.  Extracts behavior that will later be common to keep it out of the major merging commit
=> Extract common UserContent behavior

code/src/java/pcgen/io/IIFNode.java
- use final where appropriate
- don't use "_" for params
- avoid issues with returning modifiable list
- use diamond operator
=> CODE-2790: Clean up IIFNode

system/gameModes/Modern/migration.lst
=> Fix CATEGORY should be ABILITY

code/src/java/pcgen/gui2/dialog/AboutDialog.java
(hopefully I'll be getting to 'real code'
and not just cleanup shortly)
=> Code cleanup 	- make variables local from class 	variables to make it easier to follow

code/src/java/pcgen/gui2/csheet/CharacterSheetPanel.java
- change enum to include data attached instead of using a
separate switch statement
- Use resource based try statements
- Be explicit about caught exceptions
- Don't explicitly init to null
- Use final where possible
- Use string formatting instead of manual concat
- Cut off lines at consistent 80 char mark
=> CODE-2790: Clean up CharacterSheetPanel

system/gameModes/Modern/migration.lst, system/gameModes/Pathfinder_PFS/miscinfo.lst
Main repo fixes to pcc load errors: missing comment glyph and what looks like just a random preceding - in PFS miscinfo
=> DATA-2609: PCC read errors

code/src/test/pcgen/gui2/facade/EquipmentSetFacadeImplTest.java
@James or @thpr this is a failing unit test discovered during prerelease test. Can't proceed till this is fixed.
=> Unit test Failure asserts 2, but recent changes make this 1.

code/src/test/pcgen/gui2/facade/EquipmentSetFacadeImplTest.java
Updated the second test in the same file to pass release. This is part of the 6.05.05 release I'm uploading, but going through the proper channels here...
=> Updated test

installers/win-installer/gendatalist.pl
@jdempsey-au update the exclusion list - removed homebrew and add readme.md
=> exclude the filename readme.md, re-include homebrew due to complaints

installers/win-installer/gendatalist.pl
@jdempsey-au an update cleans up missing homebrew publisher entry. Re-running test. So far so good.
=> 6.05.06 release

code/src/java/pcgen/gui2/facade/TempBonusHelper.java, code/src/java/plugin/lsttokens/TempValueLst.java, code/src/utest/plugin/lsttokens/TempValueLstTest.java, code/src/utest/plugin/lsttokens/testsupport/AbstractGlobalTokenTestCase.java
Fixed bug and added a unit test for the token.
=> Fix bug: CODE-2936 - CONVERTER 6.06: CHOOSE:NUMBER double converts

code/src/java/pcgen/cdom/base/ChooseInformationUtilities.java, code/src/java/pcgen/cdom/content/AbilitySelection.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/io/exporttoken/AbilityToken.java, code/src/test/pcgen/io/exporttoken/AbilityTokenTest.java, code/src/test/plugin/exporttokens/VAbilityTokenTest.java, code/testsuite/csheets/35e_Bob.xml
- Also output ability selection choices in a human readable manner.
=> Fix bug: CODE-2949 - Saved FEATSELECTION choices need migration.

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_globalvar.lst
=> DATA-2673: [PFUM] Magus doesn't get lvl 3 arcana

.gitignore, code/src/java/pcgen/gui2/equip/EquipCustomPanel.java, code/src/java/pcgen/gui2/equip/EquipQualifiedTreeCellRenderer.java, code/src/java/pcgen/gui2/sources/AdvancedSourceSelectionPanel.java, code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/models/CharacterTreeCellRenderer.java, code/src/java/pcgen/gui2/tabs/summary/LanguageTableModel.java, code/src/java/pcgen/gui2/util/JTreeTable.java, code/src/java/pcgen/gui2/util/TreeColumnCellRenderer.java, code/src/java/pcgen/util/fop/FOP11HandlerImpl.java
This time with jira issue ids and no build.gradle modifications
=> Various UI Fixes

code/src/java/pcgen/gui2/tabs/InfoTabbedPane.java
CODE-2939 - Character Sheet page does not update when change character
=> Bug Fix: CODE-2969 - Character sheet doesn't refresh

data/pathfinder/paizo/campaign_setting/inner_sea_world_guide/iswg_equip_arms_armor.lst, data/pathfinder/paizo/campaign_setting/inner_sea_world_guide/iswg_profs_weapon.lst
=> DATA-2713: ISWG Load errors

code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/DescriptionFormatting.java, code/src/java/pcgen/facade/core/InfoFactory.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/gui2/kits/KitPanel.java, code/src/java/pcgen/gui2/tabs/ClassInfoTab.java, code/src/java/pcgen/gui2/tabs/DomainInfoTab.java, code/src/java/pcgen/gui2/tabs/EquipInfoTab.java, code/src/java/pcgen/gui2/tabs/PurchaseInfoTab.java, code/src/java/pcgen/gui2/tabs/RaceInfoTab.java, code/src/java/pcgen/gui2/tabs/TempBonusInfoTab.java, code/src/java/pcgen/gui2/tabs/TemplateInfoTab.java, code/src/java/pcgen/gui2/tabs/equip/EquipmentTableModel.java, code/src/java/pcgen/gui2/tabs/skill/SkillTreeViewModel.java, code/src/java/pcgen/gui2/tabs/spells/SpellBooksTab.java, code/src/java/pcgen/gui2/tabs/spells/SpellNodeDataView.java, code/src/java/pcgen/gui2/tabs/spells/SpellTreeViewModel.java, code/src/java/pcgen/gui2/tabs/spells/SpellsKnownTab.java, code/src/java/pcgen/gui2/tabs/spells/SpellsPreparedTab.java
CODE-2751
CODE-1367
CODE-1075
CODE-1074
CODE-1073
CODE-1072
CODE-1071
CODE-1070
CODE-1069
=> Added description column in various tables

code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/summary/StatTableModel.java
=> Abilities (Stats) table bug fixes.

preview/summary/35e_info.html, preview/summary/fc_info.html, preview/summary/killshot_info.html, preview/summary/pfrpg_info.html
OS-436: [Summary Statistics] Pathfinder sheet is missing column titles
=> OS-434: [Summary Statistics] Vertically center text with images

code/src/java/pcgen/gui2/util/JTreeViewTable.java
This really helps on the feats tab where there might be thousands of different abilities to choose from. Makes the tab switch pretty instantaneous. :)
=> CODE-2990: UI performance enhancements

data/pathfinder/paizo/roleplaying_game/pathfinder_unchained/pu_abilities_class.lst
The Unchained Rogue can take several of the talents of the ordinary
Rogue in unmodified form.
=> Add the unmodified talents for the Unchained Rogue

code/src/test/pcgen/core/PlayerCharacterTest.java, code/src/test/pcgen/core/prereq/PreAttTest.java, code/src/test/pcgen/io/exporttoken/WeaponTokenTest.java, code/src/test/plugin/exporttokens/AttackTokenTest.java
=> Remove COMBAT|BAB

code/src/java/pcgen/cdom/base/FormulaFactory.java, code/src/test/pcgen/core/prereq/PreCheckBaseTest.java, code/src/test/pcgen/core/prereq/PreCheckTest.java
Improve message on broken formula
=> Fix tests to not use deprecated BONUS

build.gradle, code/src/java/pcgen/cdom/base/FormulaFactory.java
Update to Version 44 of PCGen-Formula library (bug fix)
=> Fix for updated message in PCGen-Formula

code/pluginbuild.xml, code/src/java/pcgen/cdom/inst/CodeControl.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/persistence/GameModeFileLoader.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/persistence/lst/LstUtils.java, code/src/java/pcgen/rules/persistence/CodeControlLoader.java, code/src/java/pcgen/rules/persistence/token/AbstractStringStoringToken.java, code/src/java/plugin/bonustokens/HP.java, code/src/java/plugin/exporttokens/AltHPToken.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/AltHPToken.java
NEWTAG-568 CODECONTROL Game Mode File
NEWTAG-569 ALTHP Code Control (Formula Conversion)
=> NEWTAG-568 and NEWTAG-569

preview/d20/fantasy/troubleshooting.htm.ftl
This is a Freemarker version of the troubleshoooting preview sheet. 
only remark thing: it can't display the templates added to the character that has VISIBLE:NO.
they aren't counted (pcvar("COUNT[TEMPLATES]") > 0 fail)  and also they don't appear in the pcstring('TEMPLATELIST') but they are applied (the ability that apply them is displayed correctly, also the effects. Obviously if you change the VISIBLE:NO to VISIBLE:YES they appear.
already wrote to mailing list these problems: https://groups.yahoo.com/neo/groups/pcgen/conversations/messages/114564
but in the end, it runs correctly.
=> FreeMarker version of troubleshooting sheet.

code/src/java/pcgen/output/actor/SourceActor.java, code/src/java/pcgen/output/model/SourceModel.java, code/testsuite/base-xml.ftl
Rebuild source output in Freemarker
=> NEWTAG-530-B

code/src/java/pcgen/cdom/facet/ObjectWrapperFacet.java, code/src/java/pcgen/output/actor/IntegerKeyActor.java, code/src/java/pcgen/output/actor/OutputNameActor.java, code/src/java/pcgen/output/actor/SourceActor.java, code/src/java/pcgen/output/actor/StringKeyActor.java, code/src/java/pcgen/output/actor/VariableActor.java, code/src/java/pcgen/output/base/SimpleObjectWrapper.java, code/src/java/pcgen/output/base/SimpleWrapperLibrary.java, code/src/java/pcgen/output/model/BooleanModel.java, code/src/java/pcgen/output/model/DateModel.java, code/src/java/pcgen/output/model/FactFacetModel.java, code/src/java/pcgen/output/model/NumberModel.java, code/src/java/pcgen/output/model/OrderedPairModel.java, code/src/java/pcgen/output/model/SourceModel.java, code/src/java/pcgen/output/model/StringModel.java, code/src/java/pcgen/output/model/UnitSetModel.java, code/src/java/pcgen/output/wrapper/AgeSetWrapper.java, code/src/java/pcgen/output/wrapper/BooleanWrapper.java, code/src/java/pcgen/output/wrapper/CDOMReferenceWrapper.java, code/src/java/pcgen/output/wrapper/CategoryWrapper.java, code/src/java/pcgen/output/wrapper/DateWrapper.java, code/src/java/pcgen/output/wrapper/NumberWrapper.java, code/src/java/pcgen/output/wrapper/OrderedPairWrapper.java, code/src/java/pcgen/output/wrapper/StringWrapper.java, code/src/java/pcgen/output/wrapper/TypeSafeConstantWrapper.java
Build custom wrappers that also implement Reference
This is preparation for having channels to communicate core/UI et al
=> Stop using Freemarker default/simple wrapper

code/src/java/pcgen/cdom/enumeration/SubClassCategory.java, code/src/java/pcgen/cdom/inst/AbstractCategory.java
Extract function from SubClass - to be shared as part of DynamicScope object infrastructure
=> Introduce AbstractCategory

code/pluginbuild.xml, code/src/java/gmgen/plugin/PlayerCharacterOutput.java, code/src/java/pcgen/cdom/facet/analysis/ArmorClassFacet.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/core/display/TemplateModifier.java, code/src/java/pcgen/core/term/BasePCTermEvaluator.java, code/src/java/pcgen/core/term/PCCountEqTypeTermEvaluator.java, code/src/java/pcgen/core/term/PCSizeModEvaluatorTermEvaluator.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/plugin/bonustokens/Combat.java, code/src/java/plugin/bonustokens/EqmArmor.java, code/src/java/plugin/bonustokens/deprecated/ACValue.java, code/src/java/plugin/exporttokens/ACToken.java, code/src/java/plugin/exporttokens/ArmorToken.java, code/src/java/plugin/exporttokens/DefenseToken.java, code/src/java/plugin/exporttokens/SizeModToken.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/ACAlterType.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/ACVarToken.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/AltersAC.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/EqACModToken.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/EqBaseACModToken.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/SizeModDefenseToken.java
=> NEWTAG-576-B

build.gradle, code/src/java/pcgen/cdom/facet/VariableStoreFacet.java, code/src/java/pcgen/cdom/formula/MonitorableVariableStore.java, code/src/java/pcgen/cdom/formula/VariableChangeEvent.java, code/src/java/pcgen/cdom/formula/VariableChannel.java, code/src/java/pcgen/cdom/formula/VariableListener.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/output/channel/ChannelUtilities.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/testcommon/compare/InequalityTesterInst.java, code/src/utest/plugin/modifier/number/SetNumberModifierTest.java
=> Introduce Variable Channels

code/pluginbuild.xml, code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/enumeration/ListKey.java, code/src/java/pcgen/cdom/facet/FacetInitialization.java, code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/facet/ScopeFacet.java, code/src/java/pcgen/cdom/facet/base/AbstractScopeFacetConsolidator.java, code/src/java/pcgen/cdom/facet/input/DynamicFacet.java, code/src/java/pcgen/cdom/facet/model/DynamicConsolidationFacet.java, code/src/java/pcgen/cdom/facet/model/VarScopedFacet.java, code/src/java/pcgen/cdom/inst/Dynamic.java, code/src/java/pcgen/cdom/inst/DynamicCategory.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/persistence/lst/CampaignLoader.java, code/src/java/pcgen/persistence/lst/utils/VariableReport.java, code/src/java/pcgen/rules/persistence/CDOMControlLoader.java, code/src/java/pcgen/rules/persistence/DynamicLoader.java, code/src/java/plugin/lsttokens/GrantLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/java/plugin/lsttokens/campaign/DynamicToken.java, code/src/java/plugin/lsttokens/datacontrol/DynamicScopeToken.java
NEWTAG-572 DYNAMICSCOPE:
NEWTAG-571 DYNAMIC:
NEWTAG-570 GRANT: 
Add tracking VarScoped objects on PC
=> Vision Subsystem and Dynamic

code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/output/channel/compat/AbstractAdapter.java
There is a lot of cleanup work that still needs to be done, but this should be enough to get input support for stats.
=> Linked UI into stat channels.

data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_equip_general.lst, data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_arms_armor.lst, data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_general.lst
Note: this also contains a small fix for the bandolier. It should not be prevented from being properly equipped just because the character wears an outfit.
=> Implement: DATA-2903 Gunslinger ammunition improvements

docs/acknowledgments/publishersandsources.html, preview/d20/5e/Standard.htm.ftl
Fixes 5e Preview Sheet
Adds a Link to the Wiki where a complete list of books will be held by gamemode.
=> Pub update

code/testsuite/csheets/pf_Cleric.xml, code/testsuite/csheets/pf_Paladin.xml, code/testsuite/csheets/pf_goldielocks.xml
=> Revert "Update Unit tests to reflect changes in lst files."

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/facade/CharacterLevelsFacadeImpl.java
- remove some methods that are not needed
- convert and remove some deprecated methods
- Fix the documentation
- Don't compare a possible NaN to NaN since this will always be
false
=> Fix a couple of different issues

build.gradle, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java, code/src/java/pcgen/gui2/dialog/TipOfTheDay.java, code/src/java/pcgen/system/Main.java, code/src/java/pcgen/system/PCGenPropBundle.java
This makes the code a little more obvious as to what's happening and
provides usable --help output.
=> Convert argument parsing to use argparse4j

code/src/java/pcgen/persistence/CampaignFileLoader.java
remove some references to svn (and related modernization)
=> remove svn

code/src/java/pcgen/util/fop/FopTask.java
trying to keep these smaller. As they get merged I'll eventually have functional diffs for y'all.
=> simple simplification

code/src/java/gmgen/plugin/SystemDie.java, code/src/java/gmgen/plugin/dice/AppendModifier.java, code/src/java/gmgen/plugin/dice/ResultCounter.java, code/src/java/gmgen/plugin/dice/ResultModifier.java, code/src/java/gmgen/plugin/dice/SimpleModifier.java, code/src/java/gmgen/plugin/dice/SimpleSumCounter.java, code/src/java/gmgen/plugin/dice/SystemModifier.java
This furthers the die abstraction work but moving the addition of new values out of the Die and into a DieModifier.
In the old world there are multiple levels of abstraction:
Die, Dice, DieEx, SystemDie
all of which provide very specific features.
In the new world these will all be replaced by a DiceConfiguration which is just a sequence of filters
=> further the Die abstraction work

code/src/java/pcgen/io/ExportHandler.java
- fileAccess was unused, but it was passed through recursively. Remove it.
- make functions static where possible
- make functions private where possible
=> remove unused variable - modernize code

code/src/itest/pcgen/io/testsupport/AbstractSaveRestoreTest.java, code/src/java/gmgen/gui/ImagePreview.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/system/CharacterManager.java
this isn't used and harms my plan to separate out PlayerCharacter into composable chunks.
=> remove 'load' from PlayerCharacter ctor

code/src/java/pcgen/gui2/facade/EquipmentSetFacadeImpl.java
Before I spend much time inside of EquipmentSet clean it up a bit. This will serve as a base commit for future work and make it easier to review changes.
=> initial pass over EquipmentSet

code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/chooser/ChooserUtilities.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/plugin/exporttokens/EqContainerToken.java, code/src/java/plugin/lsttokens/add/LanguageToken.java, code/src/java/plugin/lsttokens/add/SpellCasterToken.java, code/src/test/pcgen/AbstractCharacterTestCase.java
Depends on #1516 - this continues the work to find PlayerCharacter and remove it from various parts.
=> further decouple PlayerCharacter from the rest of the system (part 2)

code/src/java/plugin/initiative/CheckModel.java, code/src/java/plugin/initiative/DiceRollModel.java, code/src/java/plugin/initiative/gui/CheckDialog.java, code/src/java/plugin/initiative/gui/DiceRollDialog.java, code/src/java/plugin/initiative/gui/Initiative.java
While this may overlap with the GUI rewrite a bit this code intersects with the PlayerCharacter code in somewhat indirect ways. I ended up here, so clean it up.
=> Clean up initiative code

data/pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_race.lst
I have no idea why Github add the previously merged output sheet commit to this PR.
=> DATA-3043 swashbuckler favored class panache bonus

code/gradle/autobuild.gradle, code/gradle/reporting.gradle, code/standards/pmdruleset.xml
for PMD and a few other things
=> bump date and versions

build.gradle
This is like JSR305 but lets it be used
Uses compileOnly to avoid license and distribution requirements
=> just add annotions

code/src/java/pcgen/output/base/SimpleWrapperLibrary.java
while here make the utility class, a utility class
=> remove impossibleness from SimpleLibraryWrapper

build.gradle
- add slf4j for logging
- add logback for logging implementation (to replace other logging)
- add plugin to find out of date deps
=> add two new deps

code/src/utest/pcgen/base/util/NamedFormulaTest.java, code/src/utest/pcgen/base/util/WeightedCollectionTest.java
I got really confused when I saw the @Test annotations along with an extension from TestCase.
Begin converting entirely to junit 4
=> convert from Junit 3 -> Junit 4 properly

code/src/java/pcgen/base/enumeration/TypeSafeConstant.java, code/src/java/pcgen/cdom/base/PrimitiveFilter.java, code/src/java/pcgen/cdom/enumeration/StringPCAttribute.java, code/src/java/pcgen/cdom/facet/BonusChangeFacet.java, code/src/java/pcgen/cdom/facet/BonusSkillRankChangeFacet.java, code/src/java/pcgen/cdom/facet/SkillRankFacet.java, code/src/java/pcgen/cdom/facet/event/AssociationChangeListener.java, code/src/java/pcgen/cdom/formula/VariableListener.java, code/src/java/pcgen/cdom/meta/PerspectiveLocation.java, code/src/java/pcgen/cdom/reference/UnconstructedListener.java, code/src/java/pcgen/facade/util/event/ChangeListener.java, code/src/java/pcgen/facade/util/event/ReferenceListener.java, code/src/java/pcgen/gui2/tools/CharacterSelectionListener.java, code/src/java/pcgen/io/filters/OutputFilter.java, code/src/java/pcgen/output/base/SimpleObjectWrapper.java, code/src/java/pcgen/pluginmgr/PCGenMessageHandler.java, code/src/java/pcgen/util/SortKeyAware.java
this doesn't add it globally - only where it seems to make sense
=> add a few functional interface annotations

build.gradle
The project is dead, the replacement project is dead.
Also nothing fails (tests, compilation, or running) when removed.
I am loyal to the royal court of arthur
=> as best as I could tell - we don't use avalon anymore

build.gradle
This reverts commit bd29db9ef1348547cc4061ad105246192dc502fe.
=> Revert "make tests run faster"

build.gradle
see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html for details
=> make compilation faser

build.gradle
=> Revert "make compilation faser"

build.gradle, code/resources/logback.xml, code/src/java/pcgen/system/Main.java
This is really here to add logback.xml and to show how it gets called.
example logs:
=> Add basic Log4J Logging

build.gradle, code/resources/logback.xml, code/src/java/pcgen/system/Main.java
add different logic for having a marker vs not. This is mostly an example and not really useful in of itself.
Also fix formatting in Main
Also fix some minor issues in logback.xml
=> fix formatting; add special logging for exceptions

build.gradle
grep didn't find xunit - apparently we still use it :/
=> remove comments that reference things we don't use;

build.gradle
this is the remainder of the version bumps
=> combined version bump

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/converter/PCGenDataConvert.java, code/src/java/pcgen/gui2/coreview/CoreViewFrame.java, code/src/java/pcgen/gui2/dialog/AboutDialog.java, code/src/java/pcgen/gui2/dialog/CharacterHPDialog.java, code/src/java/pcgen/gui2/dialog/DIWarningDialog.java, code/src/java/pcgen/gui2/dialog/DataInstaller.java, code/src/java/pcgen/gui2/dialog/EquipCustomizerDialog.java, code/src/java/pcgen/gui2/dialog/ExportDialog.java, code/src/java/pcgen/gui2/dialog/KitSelectionDialog.java, code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java, code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/dialog/PrintPreviewDialog.java, code/src/java/pcgen/gui2/dialog/RandomNameDialog.java, code/src/java/pcgen/gui2/dialog/SpellChoiceDialog.java, code/src/java/pcgen/gui2/prefs/CharacterStatsPanel.java, code/src/java/pcgen/gui2/prefs/NewPurchaseMethodDialog.java, code/src/java/pcgen/gui2/solverview/SolverViewFrame.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/summary/LanguageTableModel.java, code/src/java/pcgen/gui2/tools/Utilities.java, code/src/java/pcgen/gui2/tools/Utility.java
my actual goal here is to ensure that '@contract' shows up in the code base so that it doesn't break.
This is used by FindBugs and related utilities to identify issues. In the case of pure=true this is used to identify where the return value isn't checked (which must be an error since the function has no side effects).
=> clean up utility

code/src/java/pcgen/core/PlayerCharacter.java
I consider this a misdesigned interface but generally you want valueOf, not new ...
=> value of decimal as string

code/src/java/pcgen/cdom/facet/base/AbstractItemConvertingFacet.java
This reverts commit 6d0c49efed2397cd2c6655a6d4e153a1a0f95741.
=> Fix Build: Revert "inner qual -> nothing"

code/src/java/applicationContext.xml
honestly not sure if this is correct, but the style seems off and figured I'd get your attn to it
=> case of spring

code/src/test/AllJUnitTests.java, code/src/test/pcgen/core/AllJUnitTests.java
this is the top level of the tests: make this junit 4
=> migrate test runner away from junit3

code/src/java/plugin/initiative/gui/OpposedCheckDialog.java
in addition to regular cleanup I've found a way to reduce the total number of unchecked generic assignments. This does move a couple of them around, but fixing those requires modifying other classes.
=> reduce warnings in  OpposedCheckDialog

build.gradle, code/gradle/reporting.gradle, code/standards/fancy-hist.xsl, code/standards/findbugs_ignore.xml
This also makes a few other changes: 
- enable some reporting by default. This moves on a path towards *erroring* when the reporting fails which is the only real way to ensure we don't regress.
=> Add findbugs to gradle

code/src/java/pcgen/core/PlayerCharacter.java
=> dec -> dec

code/src/java/pcgen/io/Compatibility.java
don't think this is anything other than a newly working validation, but maybe I missed where else this would get triggered.
=> fix minor validation bug in compatability

code/pluginbuild.xml, code/src/java/pcgen/cdom/facet/CheckBonusFacet.java, code/src/java/pcgen/cdom/facet/StatCalcFacet.java, code/src/java/pcgen/cdom/facet/StatValueFacet.java, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/facade/core/CharacterFacade.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/gui2/tabs/summary/StatTableModel.java, code/src/java/pcgen/output/channel/ChannelCompatibility.java, code/src/java/pcgen/output/channel/compat/StatAdapter.java, code/src/java/plugin/bonustokens/Save.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/BaseSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/EpicSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/MagicSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/MiscSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/RaceSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/StatModSave.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/TotalSave.java, code/src/java/plugin/pretokens/parser/PreCheckParser.java
Add SAVE Code Controls (allows access by data to the UI fields of the stat values)
=> NEWTAG-611

build.gradle
See http://ci.pcgen.org:8080/jenkins/job/PCGen_Full_Build_Gradle/234/ for the build failure.
=> downgrade launch4j to maybe fix the build failure

code/src/java/plugin/network/NetworkCombatant.java, code/src/java/plugin/network/NetworkModel.java, code/src/java/plugin/network/gui/NetworkView.java
This removes some checkstyle warnings (mostly around javadocs) and generally cleans up the networking code.
=> Clean up checkstyle and related warnings

code/src/java/plugin/encounter/EncounterPlugin.java, code/src/java/plugin/experience/ExperienceAdjusterPlugin.java, code/src/java/plugin/network/NetworkModel.java, code/src/java/plugin/notes/gui/NotesView.java, code/src/java/plugin/overland/gui/OverPanel.java
This allows not implementing many empty methods as boilerplate.
=> Prefer extending from an adapter instead of implementing a listener

build.gradle, code/src/java/applicationContext.xml, code/src/java/pcgen/base/calculation/FormulaCalculation.java, code/src/java/pcgen/cdom/content/ProcessCalculation.java, code/src/java/pcgen/cdom/facet/ModifierFacet.java, code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/facet/ScopeFacet.java, code/src/java/pcgen/cdom/facet/SolverManagerFacet.java, code/src/java/pcgen/cdom/inst/EquipmentHead.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/java/plugin/function/InputFunction.java, code/src/java/plugin/function/LookupFunction.java, code/src/java/plugin/modifier/set/AddModifierFactory.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java, code/src/utest/plugin/modifier/number/SetNumberModifierTest.java, code/src/utest/plugin/modifier/testsupport/EvalManagerUtilities.java
=> Formula Library v95

outputsheets/d20/fantasy/pdf/common_sheet/block_class_features.xslt, outputsheets/d20/fantasy/pdf/csheet_condensed_display_grey_light_largeTEXT.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_no_header.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_spell_list_only.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blackandwhite.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blue.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blue_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_companion_box_first_page.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_green_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_grey.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_grey_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_red_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_yellow_full.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_yellow_light.xslt
Also fixed colored block extending over the edge of these boxes.
=> Fix OS-472: Text in 35e class feature boxes does not wrap

.gitignore, build.gradle, code/src/java/pcgen/cdom/facet/SolverManagerFacet.java, code/src/java/pcgen/cdom/formula/ManagerKey.java, code/src/java/pcgen/cdom/formula/VariableChannel.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/persistence/token/AbstractSetModifierFactory.java, code/src/java/plugin/function/DropIntoContext.java, code/src/java/plugin/modifier/number/SetModifierFactory.java, code/src/testcommon/compare/InequalityTesterInst.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/function/AbstractFormulaTestCase.java, code/src/utest/plugin/function/DropIntoContextFunctionTest.java, code/src/utest/plugin/function/TestUtilities.java
Update to use Dynamic Solver Manager
Formula Library Version 101
=> NEWTAG-596 add dropIntoContext function

preview/d20/5e/Standard.htm.ftl
Attempting to clean up the 5e preview to remove some stats that are not used or needed in 5e. Wanted to do this before I started converting or updating things to reflect more prof bonuses, etc.
=> 5e Preview Cleanup

build.gradle
- remove useless commons-logging
- split hamcrast-all into just the parts of the library I actually use
=> clean up gradle deps

code/src/java/gmgen/gui/RelativeImageView.java
I'm unsure if this is correct or if the real fix is to make use of the removed functions; on the other hand I can't find any GUI bugs that result from this.
=> Remove some unused code

code/src/java/pcgen/cdom/helper/SpringHelper.java
While here replace calls to init* with a static initialiser which is
easier to understand and easier to use (no special calls required!).
Also clean up a little bit of code.
=> Replace use of deprecated XmlBeanFactory

build.gradle, code/gradle/release.gradle, code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/plaf/LookAndFeelManager.java, installers/win-installer/release.pl
This one is more personal style but IMHO kunststoff always looks worse than the system style
In addition there explicit code to add kunststoff in a variety of places complicating some parts of the code base.
When conor finishes the Gui3 rewrite this won't matter anyways so simplify life until then and reduce the amount of compat testing to do.
=> remove kunstoff LaF

code/src/java/gmgen/gui/FlippingSplitPane.java, code/src/java/gmgen/gui/Utilities.java
As far as I could tell this bug no longer exists. In addition,
semantically we don't want the "right mouse" - we want the "popup
trigger" which was never buggy in the first place"
=> Remove some bug-workaround code

code/src/java/plugin/converter/ChooseConvertPlugin.java, code/src/java/plugin/converter/FavClassConvertPlugin.java, code/src/java/plugin/converter/PreVisionConvertPlugin.java, code/src/java/plugin/converter/PreVisionInvertedConvertPlugin.java
Its unclear to me if we still need this plugin or not, but either way, lets modernize some code
=> Modernize converter plugin

build.gradle, code/gradle/release.gradle, code/src/java/gmgen/manifest.mf, code/src/java/pcgen/resources/lang/LanguageBundle.properties, code/src/java/pcgen/resources/lang/cleaned.properties, code/src/java/plugin/doomsdaybook/manifest.mf, code/src/java/plugin/initiative/manifest.mf, code/src/java/plugin/notes/manifest.mf, code/src/java/plugin/overland/manifest.mf, code/src/test/pcgen/inttest/pcGenGUITestCase.java, installers/win-installer/pcgen-nsis.jelly, installers/win-installer/release.pl
the tests still run correctly with the native JDK implementation
=> Remove xalan and xerces

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/tools/Utility.java, code/src/java/pcgen/system/Main.java
This doesn't actually make the menubar work as expected, but it gets farther along (and reduces some silly indirection)
=> pull macOS code into a common location

data/pathfinder/paizo/roleplaying_game/mythic_adventures/ma_equip.lst
Updated magic item's type tags to be consistent with current system
=> Corrected item Type tags

data/pathfinder/paizo/player_companion/magical_marketplace/mm_equip_general.lst
Healer's Burning Glass only 32,400 gp not 324,000 gp
=> Remove extra 0 from Healer's Burning Glass price

build.gradle, code/gradle/release.gradle, gradle/wrapper/gradle-wrapper.properties
this gets us to the latest Gradle version. We're still
using some deprecated features which will be removed in Gradle 5.
I'll fix those in a separate PR (ideally post-this being merged)
=> Upgrade to Gradle 3.3

code/src/java/plugin/notes/gui/NotesTreeNode.java
=> remove some CVS references

.travis.yml, code/src/java/plugin/pretokens/parser/PreTypeParser.java
While we don't currently run slowtest in Travis, at least avoid compile
errors.
=> Compile slowtest in Travis

code/src/java/translation/util/Tips.java, code/src/java/translation/util/package-info.java, code/src/test/translation/util/TipsTest.java
This does break some style rules, but please treat this as a revert, not a code submission (i.e., I'll get to fixing the style issues eventually)
=> Partial revert of some of the Tips changes

code/src/java/pcgen/util/Logging.java
Add SuppressWarnings for multiple loggers on logging class
Mark it as a utility class
=> Fix two pmd warnings for Logging class

code/gradle/autobuild.gradle
=> Revert "Try alt directory in autobuild"

data/pathfinder/paizo/player_companion/andoran_spirit_of_liberty/andoran_spirit_of_liberty.pcc, data/pathfinder/paizo/player_companion/andoran_spirit_of_liberty/asol_skills.lst
Removing asol_skills.lst because there is no data in this file.
=> Removal of unused file

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/_pfs/pfs_apg_spells.lst
=> APG PFS fix

data/pathfinder/paizo/campaign_setting/faction_guide/_pfs/_.pcc, data/pathfinder/paizo/campaign_setting/faction_guide/_pfs/pfs_pcfg_abilities.lst, data/pathfinder/paizo/campaign_setting/faction_guide/_pfs/pfs_pcfg_feats.lst, data/pathfinder/paizo/campaign_setting/faction_guide/_pfs/pfs_pcfg_spells.lst, data/pathfinder_pfs/paizo/pathfinder_society/pathfinder_society_complete.pcc
=> Faction Guide PFS Support

.travis.yml
This will also help to catch more errors
=> Also run itest in travis

code/src/java/pcgen/resources/lang/LanguageBundle_it.properties
Submission to the Help address
@thpr or @cpmeister  or @grimreaper please review to the best of your ability
=> Submission for Italian update

checkstyle.xml, findbugs-excludes.xml, ruleset.xml
Its kind of ridiculous that codacity doesn't have a way to point it to
the real files without including them in the project root. Its
questionable if we need codacity in the first place, but given we have
it, lets at least make it more useful than it otherwise would be.
=> Add configuration files for codacity

build.gradle, code/gradle/reporting.gradle
This still requires manual work to use (-Dscan) but this makes it
possible.
=> Enable the buildscan plugin

code/src/java/gmgen/gui/ImagePreview.java, code/src/java/pcgen/cdom/base/Constants.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/InfoGuidePane.java, code/src/java/pcgen/gui2/UIPropertyContext.java, code/src/java/pcgen/gui2/dialog/CharacterHPDialog.java, code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/tabs/DomainInfoTab.java, code/src/java/pcgen/gui2/tabs/SkillInfoTab.java, code/src/java/pcgen/gui2/tabs/ability/CategoryTableModel.java, code/src/java/pcgen/gui2/tabs/bio/ImagePreviewer.java, code/src/java/pcgen/gui2/tabs/bio/PortraitPane.java, code/src/java/pcgen/gui2/tabs/equip/EquipmentModel.java, code/src/java/pcgen/gui2/tabs/equip/EquipmentModels.java, code/src/java/pcgen/gui2/tabs/skill/SkillPointTableModel.java, code/src/java/pcgen/gui2/tabs/summary/ClassLevelTableModel.java, code/src/java/pcgen/gui2/tabs/summary/LanguageTableModel.java, code/src/java/pcgen/gui2/tabs/summary/StatTableModel.java, code/src/java/pcgen/gui2/util/JTreeTable.java, code/src/java/pcgen/gui2/util/SimpleTextIcon.java, code/src/java/pcgen/gui2/util/table/TableUtils.java, code/src/java/plugin/notes/gui/NotesView.java
While this those changes are in the right direction, more work is needed to make the GUI properly reactive and flexible.
Fixes #2963
=> Revert the row height changes from #2963

apex-ruleset.xml
Let's see if codacy picks this one up....
=> Add another possible config file

code/src/test/pcgen/PCGenTestCase.java
=> remove complexity from PCGenTestCase

code/src/java/pcgen/base/util/RandomUtil.java, code/src/java/pcgen/core/RollingMethods.java, code/src/utest/pcgen/core/RollingMethodsTest.java
When top(N) is specified in the roll(String) method take the top(N) and not the bottom(N) dice.
=> [CODE-3185] Fix the top(N) for the dice roller

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_class.lst
Updated UM to give new familiars to Shaman
=> DATA-3302: Shaman UM Familiars

code/src/java/pcgen/core/Description.java
Thanks to @thpr for this quick fix.
=> Clean up Description display of %LIST associations.

code/gradle/reporting.gradle, code/standards/pmdruleset.xml
Ignore some errors on the way, but they will be fixed in due course
=> Bump pmd, checkstyle to latest

code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/NoteItem.java, code/src/java/pcgen/core/character/EquipSet.java, code/src/java/pcgen/core/character/SpellBook.java, code/src/java/pcgen/rules/context/AbstractListContext.java, code/src/utest/pcgen/testsupport/NoPublicZeroArgConstructorMap.java, code/standards/pmdruleset.xml
As we make progress towards a cleaner code base, lets keep it that way!
=> Reduce exclusions from pmd

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_classes.lst
Weapon Mastery was not affected by Fighter_CF_WeaponMastery
=> Fighter Archetype fix

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr__datacontrols.lst, data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_globalvar.lst
Added ability to replace/alter weapon proficiencies and armor proficiencies.
=> Druid Archetype proficiencies

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_abilities_class.lst
Corrected CF tags for individual alchemist discoveries
=> Alchemist_Archetype_Discovery_Fix

docs/doc_tools/all_link_anchors_to_lowercase.py
This reverts commit 497e7848d6433775fd30205a6542ae8d5f896506.
=> Revert "Convert to dual language: python 2 and 3"

build.gradle, code/gradle/reporting.gradle, gradle/wrapper/gradle-wrapper.properties
This fixes a few minor incompatibilities with 4.0
=> Bump gradle to 4.0.2

code/pluginbuild.xml, code/src/java/pcgen/cdom/content/fact/FactDefinition.java, code/src/java/plugin/function/GetFact.java, code/src/utest/plugin/function/GetFactFunctionTest.java
=> NEWTAG-595 add getFact Function to new formula system

build.gradle
We dynamically rely on rhinojs, but it was removed early (by me :()
=> Fix 'preview' tab for pcgen

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenStatusBar.java, code/src/java/pcgen/gui2/util/StatusWorker.java, code/src/java/pcgen/gui2/util/SwingWorker.java
This reverts commit d88a0b4d81283286cff7866ede3851749033ceb3.
=> Revert "Use modern SwingWorker instead of SWv3; remove constant if conditions (#2383)"

code/src/java/gmgen/plugin/Combatant.java, code/src/java/plugin/encounter/EncounterPlugin.java
- Remove old history
- remove Javadoc from method that does not return
- simplify handleAddCreature
=> Fix a few minor style issues

outputsheets/base.xml.ftl, outputsheets/d20/5e/htmlxml/csheet_5e_xml_generic.html.ftl, outputsheets/d20/fantasy/htmlxml/csheet_fantasy_generic_export.xml.ftl, outputsheets/d20/starfinder/htmlxml/csheet_fantasy_std.htm.ftl, outputsheets/d20/starfinder/pdf/common_sheet/block_attack.xslt, outputsheets/d20/starfinder/pdf/common_sheet/block_equipment.xslt, outputsheets/d20/starfinder/pdf/common_sheet/block_misc.xslt, outputsheets/d20/starfinder/pdf/common_sheet/block_pc_header_row.xslt, outputsheets/d20/starfinder/pdf/common_sheet/block_weapons.xslt, outputsheets/d20/starfinder/pdf/fantasy_common.xsl, outputsheets/d20/starfinder/pdf/fantasy_master_common_blocks.xslt, outputsheets/fop.xconf, preview/d20/starfinder/Standard.htm.ftl, system/gameModes/5e/base.xml.ftl, system/gameModes/Fantasy_Craft/base.xml.ftl, system/gameModes/Pathfinder/base.xml.ftl, system/gameModes/Sagaborn/base.xml.ftl, system/gameModes/Starfinder/base.xml.ftl, system/gameModes/Starfinder/equipmentslots.lst
FOP 2.x issue with URI standard - All base.xml.ftl sheets updated to use freemarker conversion utility to proper URI standard.
=> Fix bug: OS-495 Pictures not included on PDF export.

code/gradle/release.gradle, installers/win-installer/pcgen.nsis
1) Add Windows 32 JRE to installer.
2) Installer selects right JRE version during installation.
=> Fix issue CODE-3187

outputsheets/d20/starfinder/text/csheet_PaizoForumBBcode.TXT, preview/d20/starfinder/Standard.htm.ftl
Added new BBcode output template.
Updated standard preview sheet template.
=> New output and preview sheets for starfinder

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_races_companion.lst, data/pathfinder/paizo/roleplaying_game/pathfinder_unchained/pu_feats.lst
Pathfinder Eidolon unable to take Martial Weapon Proficiency feat since it already has all of them for race type...
=> Fix bug: DATA-3401

code/src/java/pcgen/core/DataSet.java
added buy/sell rates for starfinder buy 100 sell 10
=> Update DataSet.java for starfinder

data/pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_abilities_builder.lst
Race Builder size modifier missing stat bonuses/penalties
=> Fix bug: DATA-3398

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items.lst
Updated magic item description to be consistent between the core rulebook and ultimate equipment (currently when item is equipped it is listed twice)
=> updated magic item description

code/src/java/pcgen/cdom/enumeration/Gender.java, code/src/java/pcgen/resources/lang/LanguageBundle.properties
Add "Host" to gender selection
=> Feature: CODE-3217

data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_feats.lst
Threatening Defender trait doesn't apply when using Stalwart w/ Combat Expertise
=> Fix bug: DATA-3403

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst
Fix to correct attack bonus progression from 13th level, and to also allow other classes to affect the Monk's Flurry.
=> Fix for Monk's Flurry of Blows

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg__datacontrols.lst
Added a small bit for summoner archetype support
=> Summoner Support 11_16_2017

data/pathfinder/paizo/roleplaying_game/core_rulebook/core_rulebook.pcc, data/pathfinder/paizo/roleplaying_game/pathfinder_unchained/pu_skills.lst
Removes "ACHECK" group. Groups Lore and Consolidated Skills.
=> Skill_table_cleanup

data/pathfinder/paizo/roleplaying_game/mythic_adventures/ma_equipmods.lst
Legendary Item not available for Bracers
=> Fix bug: DATA-3485

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_equip_magic_items.lst
Ring of Mechanical Devices doesn't exist and is actually a Ring of Maniacal Devices
=> corrected item name to Maniacal Devices

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_equip_magic_items.lst
http://paizo.com/pathfinderRPG/prd/ultimateEquipment/wondrousItems/hands.html
=> corrected minor spelling error

data/pathfinder/paizo/roleplaying_game/occult_adventures/oa_abilitycategories.lst, data/pathfinder/paizo/roleplaying_game/ultimate_intrigue/ui_abilitycategories.lst
Fixed a naming issue from old standard to new standard.
=> Archetype_fix_12_12_17

data/pathfinder/paizo/player_companion/dwarves_of_golarion/dog_equip_arms_armor.lst
Fixed mistake on Dorn-Dergar critical threat range
=> Dwarves_of_Golarion_correction

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr__datacontrols.lst
Added a bit more support for bard archetypes
=> Bard_Archetype_Support_12_27_17

data/pathfinder/paizo/player_companion/adventurers_armory/aa_profs_weapons.lst
Fixed several problems with weapon proficiencies
=> Adventurers_Armory_weapon_prof_fix

code/src/java/pcgen/core/BonusManager.java
This addresses Sorcerer Aberrant Bloodline and related issues.
=> only cache bonuses that have been positively found

code/src/java/pcgen/gui2/dialog/CalculatorDialog.java
This makes the Expression Calculator more user friendly.
=> Put expression output in scrollbar

code/src/java/plugin/function/GetFactFunction.java, code/src/utest/plugin/function/GetFactFunctionTest.java
Need to change GetFact.java to GetFactFunction.java so jar plugin finder can reference it correctly
=> NewTAG-597 add GetFactFunction.java

data/pathfinder/paizo/roleplaying_game/ultimate_magic/_ultimate_magic.pcc
Found reference to shaman class spirit animals in UM. Forwardref'ed it to kill error.
=> UM_forwardref_1_7_18

data/pathfinder/paizo/player_companion/champions_of_balance/_champions_of_balance.pcc, data/pathfinder/paizo/player_companion/champions_of_balance/cob_deities.lst, data/pathfinder/paizo/player_companion/champions_of_balance/support/cob_deities_deg.lst
Moved .MODed deities to a support folder so the source can be loaded with fewer prerequisites.
=> COB - Move DEG Deities to Support File

data/pathfinder/paizo/player_companion/undead_slayers_handbook/_undead_slayers_handbook.pcc, data/pathfinder/paizo/player_companion/undead_slayers_handbook/ush_kits.lst
Fixed incomplete item names in kits (I seem to remember that name was changed recently). Added source prerequisites to fix many unconstructed reference errors.
=> USH - Wrong Names and Missing Sources

.classpath, .project
This is what I need to keep Gradle as part of the project (and not constantly trying to change the name of the project) with EGit.  Open to reducing the change if there are ways around some of this
=> Updates for Oxygen

data/pathfinder/paizo/player_companion/adventurers_armory/aa_equip.lst
renamed items to be consistent with other sources
=> renamed items to be consistent

code/src/java/pcgen/base/calculation/AbstractPCGenModifier.java, code/src/java/pcgen/base/calculation/CalculationModifier.java, code/src/java/pcgen/base/calculation/PCGenModifier.java, code/src/java/pcgen/cdom/formula/AssociationUtilities.java, code/src/java/pcgen/gui2/solverview/SolverViewFrame.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/java/pcgen/rules/persistence/MasterModifierFactory.java, code/src/java/pcgen/rules/persistence/token/AbstractFixedSetModifierFactory.java, code/src/java/pcgen/rules/persistence/token/AbstractNumberModifierFactory.java, code/src/java/pcgen/rules/persistence/token/AbstractSetModifierFactory.java, code/src/java/pcgen/rules/persistence/token/ModifierFactory.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/java/plugin/lsttokens/datacontrol/DefaultVariableValueToken.java, code/src/java/plugin/lsttokens/race/FaceToken.java, code/src/java/plugin/lsttokens/template/FaceToken.java, code/src/java/plugin/modifier/cdom/SetModifierFactory.java, code/src/java/plugin/modifier/number/SetModifierFactory.java, code/src/java/plugin/modifier/set/AddModifierFactory.java, code/src/java/plugin/modifier/set/SetModifierFactory.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/modifier/bool/SetBooleanModifierTest.java, code/src/utest/plugin/modifier/number/AddNumberModifierTest.java, code/src/utest/plugin/modifier/number/DivideNumberModifierTest.java, code/src/utest/plugin/modifier/number/MaxNumberModifierTest.java, code/src/utest/plugin/modifier/number/MinNumberModifierTest.java, code/src/utest/plugin/modifier/number/MultiplyNumberModifierTest.java, code/src/utest/plugin/modifier/number/SetNumberModifierTest.java, code/src/utest/plugin/modifier/orderedpair/SetOrderedPairModifierTest.java, code/src/utest/plugin/modifier/string/SetStringModifierTest.java
Reopens PR#3685 due to my mistakenly deleting the branch on github
=> Convert User Priority |PRIORITY=x to a full association on MODIFY*

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr__datacontrols.lst
Added Cleric_Archetype_Aura flag
=> Cleric_Archetype_aura_support

data/pathfinder/paizo/player_companion/dirty_tactics_toolbox/_dirty_tactics_toolbox.pcc
Please remember to pull/rebase branches before committing to make sure they are current with other edits.
=> DTT - Reverse Dirty Edits in PCC

data/pathfinder/paizo/campaign_setting/distant_worlds/_distant_worlds.pcc, data/pathfinder/paizo/campaign_setting/distant_worlds/dw_equip.lst, data/pathfinder/paizo/campaign_setting/distant_worlds/dw_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/bestiary_4/_bestiary4.pcc, data/pathfinder/paizo/roleplaying_game/bestiary_4/b4_kits_race.lst
Matched all versions of the Shobhad Longrifle and fixed capitalization errors.
Removed FOREWARDREF from B4 pcc; it's not needed with references requiring them in support file.
Fixed illegal characters.
=> B4 - Load Error Corrections

data/pathfinder/paizo/player_companion/monster_summoners_handbook/msh_equipmods.lst
Changed KEY to new style as of EQMOD overhaul.
=> MSH - Corrected Keys

build.gradle, code/src/java/pcgen/cdom/base/FormulaFactory.java, code/src/java/pcgen/rules/context/PCGenManagerFactory.java, code/src/java/pcgen/rules/persistence/MasterModifierFactory.java, code/src/java/plugin/function/DropIntoContext.java, code/src/java/plugin/function/GetFactFunction.java, code/src/java/plugin/function/GetFunction.java, code/src/java/plugin/function/InputFunction.java, code/src/java/plugin/function/LookupFunction.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/function/LookupFunctionTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java
The main direct improvement here is a better check is possible in lookup() to check the semantics of the lookup value (2nd argument)
=> Updates for Formula Library 146

data/pathfinder/paizo/roleplaying_game/core_essentials/ce_templates.lst
Added language templates for languages in CE
=> CE_Language_Templates

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_abilities_class.lst
=> Fix Zen Archer Bonus Feats by MOD correct ability

code/testsuite/csheets/pf_Cleric.xml, code/testsuite/csheets/pf_Paladin.xml, code/testsuite/csheets/pf_Rogue.xml, data/pathfinder/paizo/adventure_path/curse_of_the_crimson_throne/players_guide/cotctpg_profs_weapon.lst, data/pathfinder/paizo/adventure_path/legacy_of_fire/players_guide/lofpg_prof_weapon.lst, data/pathfinder/paizo/campaign_setting/inner_sea_world_guide/iswg_profs_weapon.lst, data/pathfinder/paizo/player_companion/adventurers_armory/aa_profs_weapons.lst, data/pathfinder/paizo/player_companion/adventurers_armory_2/aa2_profs_weapon.lst, data/pathfinder/paizo/player_companion/dwarves_of_golarion/dog_profs_weapon.lst, data/pathfinder/paizo/player_companion/gnomes_of_golarion/gnog_profs_weapon.lst, data/pathfinder/paizo/player_companion/halflings_of_golarion/haog_profs_weapon.lst, data/pathfinder/paizo/player_companion/pirates_of_the_inner_sea/potis_profs_weapon.lst, data/pathfinder/paizo/player_companion/ranged_tactics_toolbox/rtt_profs_weapon.lst, data/pathfinder/paizo/player_companion/varisia_birthplace_of_legends/vbol_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_profs_shield.lst, data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/bestiary_3/b3_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/bestiary_4/b4_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/core_essentials/ce_profs_armor.lst, data/pathfinder/paizo/roleplaying_game/core_essentials/ce_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_profs_armor.lst, data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_profs_shield.lst, data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_profs_weapon.lst, data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_profs_weapon.lst
Non-destructive rename of proficiencies by adding KEY. Also updated TestSuite files with new proficiency output.
=> Proficiencies Cleanup and TestSuite Update

data/pathfinder/paizo/campaign_setting/inner_sea_intrigue/_inner_sea_intrigue.pcc, data/pathfinder/paizo/campaign_setting/inner_sea_intrigue/isi_companionmods.lst
Forgot to activate master bonus from familiar
=> ISI_familiar_bonus_fix

data/pathfinder/paizo/roleplaying_game/bestiary_4/_bestiary4.pcc, data/pathfinder/paizo/roleplaying_game/bestiary_4/b4_companionmods.lst
Somehow forgot to include the MOD that activate the bonus granted to a master
=> B4_familiar_bonus_fix

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_companion.lst
Allows replacing companion advancement options for certain companion archetypes
=> Companion Archetype Advancement Support

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst
Simple edit to fix the elemental bloodline element choices.
=> Elemental Bloodline Choice Fix

code/src/java/plugin/exporttokens/deprecated/FaceToken.java
This will occur with FACE.SHORT and identical x,y only if using the new
code control
=> Makes FACE output token truncate

data/starfinder/paizo/core/scr_equip.lst
Dermal Plating levels incorrect
=> Fix bug: DATA-3554

code/pluginbuild.xml, code/src/java/plugin/function/KeyFunction.java
Adds a key() function that will convert CDOMObjects (like Size, et al) into a string (by their key)
=> Add key() function

data/pathfinder/paizo/roleplaying_game/core_essentials/ce_skills.lst
Trailing space was preventing skill situation from working properly
=> Core_Essentials_minor_fix_for_skills

build.gradle, code/src/java/plugin/function/DropIntoContext.java, code/src/java/plugin/function/GetFactFunction.java, code/src/java/plugin/function/GetFunction.java, code/src/java/plugin/function/KeyFunction.java, code/src/java/plugin/function/LookupFunction.java, code/src/utest/plugin/function/AbstractFormulaTestCase.java
Updates to allow Main repo to use Library version 157
=> Library157

data/pathfinder/paizo/roleplaying_game/occult_adventures/oa_spells.lst
Added missing Spiritualist spells to spell list
=> OA_spiritualist_spells_fix

build.gradle, code/src/java/pcgen/rules/persistence/MasterModifierFactory.java, code/src/java/plugin/function/GetOtherFunction.java, code/src/utest/plugin/function/AbstractFormulaTestCase.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java
Includes Base Library version 129
=> Updates to Formula Library version 159

code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java, code/src/java/pcgen/gui2/tabs/summary/InfoPaneHandler.java
This fixes a NullPointerException experienced on game modes where Alignment is not defined
=> Fix Alignment Bug

code/gradle/distribution.gradle, homebrewdata/readme.md, vendordata/readme.md
Adds folders for the filepaths of Homebrew and Vendor data.
Also adds the folders to the distribution in Gradle
=> Default installs

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_equip_magic_items.lst
made names consistent with listing in Ultimate Equipment lst files to remove duplicates
=> made names consistent

data/pathfinder/paizo/roleplaying_game/monster_codex/_monster_codex.pcc
Added "(Player Options Only)" to pcc
=> Monster_Codex_notation

data/pathfinder/paizo/roleplaying_game/monster_codex/_monster_codex.pcc
Add KEY tag so that when the non-player data is added it won't need to be changed and migrated.
=> MC - Fix Key

outputsheets/d20/fantasy/htmlxml/common/PF-FG.ftl, outputsheets/d20/fantasy/htmlxml/csheet_FantasyGrounds2_pc_PFv3.xml.ftl
Updated version of the export sheet for Fantasy Grounds. Made specifically for Pathfinder and Fantasy Grounds 3.3.4
=> Fantasy Grounds Export Sheet Update

data/pathfinder/paizo/roleplaying_game/core_essentials/ce_templates.lst
ARG 216, Special Subtypes sidebar, Half-Construct and Half-Undead are race subtypes, not race types.
=> Subtypes Aren't Applying Correctly

code/src/itest/pcgen/io/testsupport/AbstractSaveRestoreTest.java, code/src/itest/tokenmodel/testsupport/AbstractTokenModelTest.java, code/src/java/applicationContext.xml, code/src/java/pcgen/base/calculation/FormulaModifier.java, code/src/java/pcgen/cdom/content/DefaultVarValue.java, code/src/java/pcgen/cdom/facet/FacetInitialization.java, code/src/java/pcgen/cdom/facet/LoadContextFacet.java, code/src/java/pcgen/cdom/facet/ModifierFacet.java, code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/facet/SolverManagerFacet.java, code/src/java/pcgen/cdom/facet/model/ActiveEqHeadFacet.java, code/src/java/pcgen/cdom/facet/model/ActiveEqModFacet.java, code/src/java/pcgen/cdom/formula/local/DefinedFunction.java, code/src/java/pcgen/cdom/formula/local/DefinedWrappingLibrary.java, code/src/java/pcgen/cdom/formula/local/DefinedWrappingModifier.java, code/src/java/pcgen/cdom/formula/local/ModifierDecoration.java, code/src/java/pcgen/cdom/formula/local/RemoteWrappingLibrary.java, code/src/java/pcgen/cdom/formula/local/RemoteWrappingModifier.java, code/src/java/pcgen/cdom/inst/EquipmentHead.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/plugin/lsttokens/datacontrol/DefaultVariableValueToken.java, code/src/test/pcgen/AbstractCharacterTestCase.java, code/src/test/pcgen/AbstractJunit4CharacterTestCase.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/pcgen/cdom/facet/model/ActiveEqModFacetTest.java, code/src/utest/pcgen/testsupport/AbstractCharacterUsingTestCase.java
Enables this() for MODIFY 
and 
source() and target() for MODIFYOTHER
Note: source() does not work if the function is used from the GlobalModifier file as there is no usable source.
=> Enable Local Functions

build.gradle
This enables operators on ARRAY[x] formats using Library version 161
=> Enable Operators on Arrays

build.gradle
No real changes: mostly build and documentation
=> bump org.jetbrains.annotations to 16.0.1

data/pathfinder/paizo/player_companion/blood_of_the_night/botn_equip_general.lst
http://www.archivesofnethys.com/MagicRingsDisplay.aspx?FinalName=Bloodletting%20Thimble
=> corrected thimble to ring instead of wondrous item

code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java
By definition in the new channel structure this code is basically "set
alignment to itself" (useless code)
=> Cleanup from moving Alignment to a channel.

code/pluginbuild.xml, code/src/java/pcgen/core/DataSet.java, code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/facade/core/DataSetFacade.java, code/src/java/pcgen/gui2/facade/DelegatingDataSet.java, code/src/java/pcgen/gui2/tabs/InfoTabbedPane.java, code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java, code/src/java/plugin/lsttokens/campaign/DataTableToken.java, code/src/java/plugin/lsttokens/gamemode/DisplayorderToken.java, code/src/java/plugin/lsttokens/gamemode/SuppressDeityDomainToken.java, code/src/test/pcgen/gui2/facade/MockDataSetFacade.java
Indicates a game mode has no Deity or Domain items - 
Allows the internal system to ignore those UI items
Also preparation for making Deity / Domains into Channels (system needs to know this situation)
=> Add SUPPRESSDEITYDOMAIN Token in Game Mode

code/src/java/pcgen/rules/context/LoadContextInst.java
It used to drop to itself (oops)
=> DropIntoContextx is making an error when it's a local drop

code/src/java/pcgen/rules/persistence/TokenSupport.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java
calling toString on a proxy was causing it to dump stack
=> Fix InterfaceToken which was dumping stack

code/src/java/pcgen/gui2/tabs/InfoTabbedPane.java
(Note: setVisible is used internally, we have to add/remove the tab)
=> Fix Visibility

code/src/java/pcgen/cdom/formula/VariableChannel.java, code/src/java/pcgen/cdom/formula/VariableChannelFactory.java, code/src/java/pcgen/cdom/formula/VariableChannelFactoryInst.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/output/channel/ChannelCompatibility.java, code/src/java/pcgen/output/channel/ChannelUtilities.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/utest/plugin/function/InputFunctionTest.java
Allows VariableChannel objects to be requested from more than one
location and still produce the same object.
=> VariableChannel factory control.

code/gradle/release.gradle, installers/win-installer/pcgen.nsi
Fix File name to match rest of file naming convention
=> Correct publisher list

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items.lst
http://paizo.com/pathfinderRPG/prd/ultimateEquipment/artifactsAndOthers/artifacts.html
=> corrected spelling

data/starfinder/paizo/core/OGL.txt, data/starfinder/paizo/core/_starfinder_core_rulebook.pcc
[Starfinder] OGL dialog not being triggered.
=> Fix bug: DATA-3614

build.gradle, gradle/wrapper/gradle-wrapper.properties
Many changes but most notable native junit changes
=> [gradle] Updateto gradle 4.6

build.gradle, code/src/java/pcgen/cdom/base/CDOMObject.java, code/src/java/pcgen/cdom/enumeration/ListKey.java, code/src/java/pcgen/cdom/enumeration/MapKey.java, code/src/java/pcgen/cdom/helper/AllowUtilities.java, code/src/java/pcgen/cdom/helper/InfoBoolean.java, code/src/java/pcgen/cdom/helper/InfoUtilities.java, code/src/java/pcgen/core/Kit.java, code/src/java/pcgen/core/prereq/PrerequisiteUtilities.java, code/src/java/pcgen/gui2/facade/CoreUtils.java, code/src/java/pcgen/gui2/facade/Gui2CampaignInfoFactory.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/output/model/InfoModel.java, code/src/java/plugin/lsttokens/AllowLst.java, code/src/java/plugin/lsttokens/EnableLst.java
Adds the String to be able to look up an INFO and provide info to a user
=> Convert ALLOW and ENABLE to String|Formula format

data/pathfinder/paizo/roleplaying_game/pathfinder_unchained/pu_abilities_class.lst, data/pathfinder/paizo/roleplaying_game/pathfinder_unchained/pu_companionmods.lst
Unchained Eidolon subtype selection limited to 'FEY'
=> Fix bug: DATA-3627

build.gradle, code/src/java/pcgen/cdom/base/FormulaFactory.java, code/src/java/pcgen/cdom/formula/local/DefinedFunction.java, code/src/java/plugin/function/GetFactFunction.java, code/src/java/plugin/function/GetFunction.java, code/src/java/plugin/function/GetOtherFunction.java, code/src/java/plugin/function/InputFunction.java, code/src/java/plugin/function/KeyFunction.java, code/src/java/plugin/function/LookupFunction.java, code/src/utest/plugin/function/GetFactFunctionTest.java, code/src/utest/plugin/function/GetOtherFunctionTest.java, code/src/utest/plugin/function/LookupFunctionTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java
Effectively the change here is the semantics no longer has a valid
check, rather it throws an exception if invalid
=> Update to Formula Library 167

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items.lst
http://www.d20pfsrd.com/magic-items/rods/suzerain-scepter/
http://www.d20pfsrd.com/magic-items/rods/rod-of-mind-mastery/
http://www.d20pfsrd.com/Magic-items/rings/ring-of-the-sea-strider
=> corrected caster level

code/src/java/pcgen/io/exporttoken/WeaponToken.java, code/src/java/plugin/bonustokens/WeaponProf.java
Add a new BONUS for a fix required for Finesse to work properly
=> Add BONUS:WEAPONPROF=x|STATDAMAGE

data/starfinder/paizo/core/scr_equip.lst
Personal Upgrades prices are incorrect for Mk2 and Mk3
=> Fix bug: DATA-3631

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst, data/pathfinder/paizo/roleplaying_game/ultimate_combat/_ultimate_combat.pcc, data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_class.lst, data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_class_apg.lst, data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_globalvar.lst
Ninja Archetype 'Scout' not removing class features
=> Fix bug: DATA-3642

data/pathfinder/paizo/campaign_setting/inner_sea_combat/isc_equip_magic.lst
corrected spelling to actual extant Sable Company and capitalized letters for consistency
=> corrected spelling and capitalized letters

data/pathfinder/paizo/player_companion/demon_hunters_handbook/dhh_equip.lst
renamed items to be consistent with other conventions and added missing item types to magic items
=> made names consistent and added item types

data/pathfinder/paizo/roleplaying_game/monster_codex/_monster_codex.pcc, data/pathfinder/paizo/roleplaying_game/monster_codex/support/mc_abilities_feat_arg.lst
Gorthek Mount (MC) not added to Beast Rider feat
=> Fix bug: DATA-3667

outputsheets/d20/4e/pdf/common_sheet/block_features.xslt, outputsheets/d20/sagaborn/htmlxml/csheet_sagaborn.htm.ftl, preview/d20/sagaborn/Standard.htm.ftl
Pathfinder/Starfinder Organized Play is only relevant Paizo products.
=> PFS remove support for 4e and sagaborn

data/pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_abilities_builder.lst
[Race Builder Design] Race Trait Movement: Flight seems not fully functional.
=> Bug fix: DATA-3687

data/pathfinder/paizo/roleplaying_game/ultimate_intrigue/ui_equip_arms_armor.lst
corrected minor spelling error
=> minor spelling

data/pathfinder/paizo/adventure_path/kingmaker/players_guide/kmpg_languages.lst
Noble Born Trait (Kingmaker Player Guide) (House Lebeda) bonuses not being placed on character
=> Fix bug: DATA-3659

data/pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_domains.lst
Shaman additional spells granted by spirits do not appear in an additional spell list
Add actual file...
=> Fix bug: DATA-3674

preview/d20/fantasy/Standard.htm.ftl
MULT Selection Feats adding additional empty spaces on preview she
* Clean up Fantasy Standard Preview display using countdistinct
=> Fix bug: OS-507

build.gradle
Just keep up ourselves up to date
=> Bump a couple of deps

data/pathfinder/paizo/roleplaying_game/advanced_race_guide/advanced_race_guide.pcc
Blood of Fiends: Tiefling Racial Trait Errors
=> Fix bug: DATA-3699

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/converter/panel/RunConvertPanel.java, code/src/java/pcgen/gui2/dialog/AboutDialog.java, code/src/java/pcgen/gui2/facade/SpellSupportFacadeImpl.java, code/src/java/pcgen/gui2/prefs/LocationPanel.java, code/src/java/pcgen/gui2/tools/DesktopBrowserLauncher.java, code/src/java/pcgen/gui2/tools/Hyperactive.java, code/src/java/pcgen/gui2/tools/InfoPaneLinkAction.java, code/src/java/pcgen/gui2/tools/Utility.java, code/src/java/pcgen/resources/lang/LanguageBundle.properties
The utilities code appears to be a pass-through into the desktop code, so
just merge them all together and make the logic slightly less complex.
=> [gui2] Merge DesktopBrowserLauncher into Utilities

build.gradle, code/gradle/reporting.gradle, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/test/pcgen/core/analysis/OutputNameFormattingTest.java, code/src/test/pcgen/gui2/facade/CompanionSupportFacadeImplTest.java, code/standards/ruleset.xml
=> update pmd to 6.7.0

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_feats_wordsofpower.lst
Words of power feat "extra word" can only be taken once
=> Fix bug: DATA-3726

build.gradle
Please apply as a rebase (not squash or merge).
=> [build] multiple updates: gradle, spotbugs, spring

.travis.yml
=> Compile with Open JDK

code/gradle/release.gradle, installers/win-installer/pcgen.nsi
This is the final GA URL for OpenJDK 11
=> Use the final GA URL

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenStatusBar.java, code/src/java/pcgen/gui2/util/StatusWorker.java, code/src/java/pcgen/gui2/util/SwingWorker.java
This reverts commit 18e1e790b44ccbe225fa030c6bf89860868f80f9.
=> Revert "Replace SwingWorker Version 3 with JDK 6+ SwingWorker (#4335)"

code/src/java/pcgen/cdom/formula/VariableChannelFactoryInst.java, code/src/java/pcgen/core/Deity.java
Some compatibility framework so items are easier to convert from facets to the new formula system
=> Add a Framework for converting items to Channels

code/src/java/pcgen/gui2/InfoGuidePane.java, code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenMenuBar.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/UIContext.java, code/src/java/pcgen/gui2/sources/AdvancedSourceSelectionPanel.java, code/src/java/pcgen/gui2/sources/SourceSelectionDialog.java
Moves Source Selection to a DI-type behavior
=> Externalize Source Selection Info

code/pluginbuild.xml, code/src/java/pcgen/cdom/reference/AbstractReferenceManufacturer.java, code/src/java/plugin/modifier/dynamic/SetModifierFactory.java
Fixes an issue Andrew found in the new formula system
Ensures Dynamic objects are allowed to be a variable FORMAT
=> Fix for how Dynamic Objects are used in the new formula system

code/src/itest/pcgen/io/BasicSaveRestoreTest.java, code/src/itest/tokencontent/testsupport/AbstractContentTokenTest.java, code/src/itest/tokenmodel/testsupport/AbstractGrantedListTokenTest.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/core/kit/KitAlignment.java, code/src/java/pcgen/core/npcgen/NPCGenerator.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/pcgen/output/channel/ChannelCompatibility.java, code/src/java/pcgen/output/channel/compat/AlignmentCompat.java, code/src/test/pcgen/core/PrereqHandlerTest.java, code/src/test/pcgen/core/prereq/PreAlignTest.java, code/src/test/pcgen/core/prereq/PreDeityAlignTest.java, code/src/test/pcgen/core/prereq/PreDeityDomainTest.java, code/src/test/pcgen/core/prereq/PreDeityTest.java, code/src/test/pcgen/core/prereq/PreDomainTest.java
Non-functional change; refactoring only
Will make Alignment Channel consistent with others in having its own compatibility class
=> Alignment Channel Part 2

code/src/java/pcgen/base/util/ProxyUtilities.java, code/src/java/pcgen/rules/persistence/TokenSupport.java
This will be reused elsewhere, don't want it embedded in TokenSupport
=> Extract StagingProxy for common use in PCGen

code/src/java/pcgen/cdom/formula/local/DefinedFunction.java, code/src/java/pcgen/cdom/formula/local/DefinedWrappingLibrary.java, code/src/java/pcgen/cdom/formula/local/DefinedWrappingModifier.java, code/src/java/pcgen/core/display/BonusDisplay.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/gui2/facade/TempBonusHelper.java
NOTE: This should be a non-logic changing (non-functional) change and should be reviewed as such
=> Cleanup and prepare various classes in preparation for TempBonus work

code/src/itest/pcgen/output/actor/FactKeyActorTest.java, code/src/itest/pcgen/output/actor/FactSetKeyActorTest.java, code/src/itest/pcgen/output/actor/IntegerKeyActorTest.java, code/src/itest/pcgen/output/actor/ListKeyActorTest.java, code/src/itest/pcgen/output/actor/ObjectKeyActorTest.java, code/src/itest/pcgen/output/actor/StringKeyActorTest.java
Preparation work for making Deity a channel, which will mean the Facet is eliminated and can't be used in tests :)
=> Change output actors to depend on Race not Deity

code/src/java/pcgen/cdom/enumeration/Handed.java, code/src/java/pcgen/cdom/facet/fact/HandedFacet.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/pcgen/output/channel/compat/HandedCompat.java, code/src/utest/pcgen/cdom/facet/fact/HandedFacetTest.java
Prepare to place Handed in the data
Note: This is a merge-conflict fix.  Previously approved in PR 4407
=> Isolate Handed to minimize awareness it's an Enumeration

code/src/java/gmgen/plugin/PlayerCharacterOutput.java, code/src/java/pcgen/core/BioSet.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/core/kit/KitBio.java, code/src/java/pcgen/core/npcgen/Configuration.java, code/src/java/pcgen/core/npcgen/GenderGeneratorOption.java, code/src/java/pcgen/gui2/doomsdaybook/NameGenPanel.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Creator.java, code/src/java/pcgen/output/channel/compat/GenderCompat.java, code/src/java/plugin/exporttokens/deprecated/GenderToken.java, code/src/java/plugin/lsttokens/kit/GenderToken.java, code/src/java/plugin/pretokens/test/PreGenderTester.java
Prepare for moving Gender to Data
Note: This is a conflict resolution, previously approved in PR 4406
=> As much as possible, Isolate that Gender is an Enumeration

gradle/wrapper/gradle-wrapper.properties
We're on a beta-release so lets keep up
=> [build] bump gradle to RC4

code/src/java/pcgen/gui2/dialog/AboutDialog.java, code/src/java/pcgen/gui2/tools/Icons.java, code/src/java/plugin/notes/gui/NotesView.java
Also switch hashmap to EnumMap
=> [Icons] migrate away from deprecated code

code/src/java/pcgen/cdom/content/factset/FactSetParser.java
Actually allow assertion to detect bad cases
=> Correct assertion in FactSetParser.java

code/src/java/pcgen/cdom/formula/ListChannelAdapter.java, code/src/java/pcgen/facade/util/DefaultListFacade.java, code/src/java/pcgen/facade/util/WriteableListFacade.java
Enables us to easily have ARRAY[x] channels presented in the UI
=> Add ListChannelAdapter

code/src/java/pcgen/cdom/facet/GrantedVarFacet.java
=> Appropriate case for variable name

code/src/java/pcgen/gui2/filter/FilterUtilities.java
=> Mark FilterUtilities as a utility class

code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/persistence/lst/SimpleLoader.java, code/src/java/pcgen/rules/persistence/DynamicLoader.java
Ensure Variables are loaded before Dynamic items
Ensure Scope is properly set when processing Dynamic objects
=> CODE-3305 - Fix Dynamic Item interaction with Variables

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_equip_magic_items.lst
campfire beads aren't consumed when used
http://aonprd.com/MagicWondrousDisplay.aspx?FinalName=Campfire%20Bead
=> corrected campfire bead type

code/src/java/pcgen/cdom/formula/VariableChannelFactoryInst.java, code/src/java/pcgen/cdom/formula/VariableUtilities.java, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/persistence/SourceFileLoader.java
Avoids changes to SourceFileLoader for each Code Control in the future
=> Standardize new Code Control behaviors

code/src/java/pcgen/cdom/formula/VariableChannelFactoryInst.java, code/src/java/pcgen/cdom/formula/VariableUtilities.java, code/src/java/pcgen/cdom/util/ControlUtilities.java, code/src/java/pcgen/core/PlayerCharacter.java
Also removes some static items from a class where they weren't that great of a location
=> Add a simplified watching system for channels to set a PC dirty

code/src/java/pcgen/io/PCGVer2Parser.java
I can't figure out what the intent is, so remove.
=> [PCGVer2Parser] remove unused method

code/src/java/pcgen/cdom/facet/AddLevelFacet.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/core/kit/KitClass.java, code/src/java/pcgen/core/kit/KitRace.java
This setting has been broken since the era of sourceforge. Time for it
to properly die.
=> [settings] remove showFeatDialogAtStartup

code/src/java/gmgen/plugin/PlayerCharacterOutput.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Creator.java, code/src/java/plugin/exporttokens/deprecated/AlignmentToken.java, code/src/java/plugin/pretokens/test/PreAlignTester.java
This basically inlines a method
=> Second Step in Alignment becoming a channel

code/src/java/pcgen/cdom/formula/VariableUtilities.java, code/src/java/pcgen/output/channel/ChannelUtilities.java
Also includes various minor cleanup
=> Relocation of Channel items to ChannelUtilities

code/src/java/pcgen/core/PlayerCharacter.java
Channels will require the controller be built somewhat earlier
=> Reorder some items in PC build to avoid order of ops issues

data/pathfinder/paizo/player_companion/people_of_the_stars/pots_equip.lst
changed item types to match common conventions
=> changed item types to match common conventions

.travis.yml, code/gradle/distribution.gradle, code/gradle/release.gradle, installers/win-installer/pcgen.nsi
1) Add _images and _universal to the core section of installer
2) Include 32 and 64 bit JRE in the full zip
=> Distribution enhancements

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg__datacontrols.lst
Added support for witch archetypes that alter weapon proficiencies
=> Witch_archetype_support_12_21_18

code/src/java/pcgen/facade/util/ListFacades.java
While here avoid unchecked warnings and generify.
=> Use Collections.emptyIterator instead of manually constructed one.

code/src/java/pcgen/core/SettingsHandler.java
This setting is never used, so just remove it.
=> SettingsHander: remove showImagePreview

code/src/java/pcgen/io/IOConstants.java
If any of these shouldn't be dead, let this be a flag.
=> Remove dead IOConstants

code/src/test/pcgen/gui2/ScanForUnusedIl8nKeys.java
- use UTF-8 instead of ISO-8859-1
- use streams
- use generics
=> [ScanForUnusedIl8nKeys] Multiple fixes

data/pathfinder/paizo/player_companion/people_of_the_north/potn_equip_general.lst
Added weapon attributes to Whale Oil as it listed as functioning as regular oil
http://www.aonprd.com/EquipmentMiscDisplay.aspx?ItemName=Whale%20oil
=> made it so whale oil functions as a weapon

code/src/java/gmgen/plugin/PlayerCharacterOutput.java, code/src/java/pcgen/cdom/facet/analysis/ChallengeRatingFacet.java, code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/core/PCTemplate.java
testing:
and cr was blank in master (no screenshot)
=> PlayerCharacterOutput: handle fractional CR

code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/facet/FacetInitialization.java, code/src/java/pcgen/cdom/facet/GrantedVarFacet.java, code/src/java/pcgen/cdom/facet/ScopedDistributionFacet.java, code/src/java/pcgen/cdom/helper/BridgeListener.java
CDOMObjects need to go to CharacterConsolidationFacet
other Scoped (e.g. Dynamic) can be consolidated just as Scoped
=> Correct how items from GrantedVarFacet flow

code/src/java/pcgen/core/character/EquipSet.java, code/src/java/pcgen/gui2/facade/EquipNode.java, code/src/java/pcgen/gui2/facade/EquipmentSetFacadeImpl.java
This is a fairly simple bulk code move to move certain items into the core, so they can be accessed by kits rather than solely by the existing UI
=> Move some items into EquipSet

code/src/java/pcgen/core/DataSet.java
Lowers dependency on the core to do work for the UI
=> Moves sorting of certain elements out to the UI

code/src/java/pcgen/cdom/formula/ListChannelAdapter.java
While this fired events on changes from the UI, if the core ever needed to change the item, it would not have properly fired off reference events.  Now it should do so.
=> Fix to ensure core changes flow to UI

build.gradle, gradle.properties
(Travis is dying of what appear to be memory issues - likely due to
parallelism)
=> [FOR FREEZE] Eliminate Parallelism

code/src/itest/tokencontent/GlobalSpellKnownTest.java, code/src/java/pcgen/cdom/enumeration/Type.java, code/src/java/pcgen/cdom/formula/PluginFunctionLibrary.java, code/src/java/pcgen/core/prereq/PrerequisiteTestFactory.java, code/src/java/pcgen/gui2/converter/TokenConverter.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/persistence/lst/TokenStore.java, code/src/java/pcgen/persistence/lst/output/prereq/PrerequisiteWriterFactory.java, code/src/java/pcgen/persistence/lst/prereq/PreParserFactory.java, code/src/java/pcgen/pluginmgr/PluginManager.java, code/src/java/pcgen/util/PJEP.java, code/src/test/pcgen/core/CampaignTest.java, code/src/test/pcgen/core/EquipmentModifierTest.java, code/src/test/pcgen/core/SourceEntryTest.java, code/src/test/pcgen/core/SpellProgressionCacheTest.java, code/src/test/pcgen/core/analysis/OutputNameFormattingTest.java, code/src/test/pcgen/core/prereq/PreReqHandlerTest.java, code/src/test/pcgen/io/migration/AbilityMigrationTest.java, code/src/test/pcgen/io/migration/EquipmentMigrationTest.java, code/src/test/pcgen/io/migration/RaceMigrationTest.java, code/src/test/pcgen/io/migration/SourceMigrationTest.java, code/src/test/pcgen/persistence/lst/FeatTest.java, code/src/test/pcgen/persistence/lst/InstallLoaderTest.java, code/src/testcommon/plugin/lsttokens/testsupport/TokenRegistration.java, code/src/utest/plugin/lsttokens/testsupport/AbstractSelectionTokenTestCase.java
Update JUnit 5 tests in the test/ folder to have them tear down as many resources as possible
=> Cleanup test static after

code/src/itest/pcgen/io/testsupport/AbstractSaveRestoreTest.java, code/src/itest/tokenmodel/testsupport/AbstractTokenModelTest.java, code/src/java/pcgen/core/kit/KitTemplate.java, code/src/java/pcgen/core/npcgen/NPCGenerator.java, code/src/java/pcgen/util/chooser/ChooserFactory.java, code/src/test/pcgen/AbstractCharacterTestCase.java, code/src/test/pcgen/core/PlayerCharacterTest.java
This doesn't matter ever, as start is only ever called from test code.
Continue to reduce code paths to ChooserFactory.
=> remove ChooserFactory.stopUsingRandomChooser

data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/_.pcc, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_abilities.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_abilities_class.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_abilities_companion.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_abilities_race.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_abilitycategories.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_equipmods.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_feats.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_kits_companion.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_languages.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_races_companion.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_skills.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_spells.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/pfs_botb_templates.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/support/pfs_botb_abilities_class_pu.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/support/pfs_botb_abilities_class_pu_fap.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/support/pfs_botb_abilities_race_pu.lst, data/pathfinder/paizo/player_companion/blood_of_the_beast/_pfs/support/pfs_botb_feats_fap.lst, data/pathfinder_pfs/paizo/pathfinder_society/pathfinder_society_complete.pcc, data/pathfinder_pfs/paizo/pathfinder_society/roleplaying_guild_guide/_roleplaying_guild_guide.pcc
Enable PFS options for Blood of the Beast
=> [PFS] Blood fo the Beast

data/pathfinder/paizo/campaign_setting/classic_treasures_revisited/_classic_treasures_revisited.pcc, data/pathfinder/paizo/player_companion/giant_hunters_handbook/_giant_hunters_handbook.pcc
Sources showing up in Other rather than Paizo
=> Sourcebook_publisher_fix

code/src/itest/pcgen/io/testsupport/AbstractSaveRestoreTest.java, code/src/itest/tokenmodel/testsupport/AbstractTokenModelTest.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/test/pcgen/AbstractCharacterTestCase.java, code/src/test/pcgen/AbstractJunit4CharacterTestCase.java, code/src/testcommon/util/FormatSupport.java, code/src/utest/pcgen/testsupport/AbstractCharacterUsingTestCase.java
Shared framework to ensure tests have appropriate variable defaults
=> Add format support

build.gradle
Might avoid some of the installer errors. Ref #4995
=> [ap-saas-core] partial "modernize our gradle a bit"

code/src/java/pcgen/cdom/helper/BridgeListener.java, code/src/utest/pcgen/cdom/helper/BridgeListenerTest.java, code/src/utest/plugin/function/InputFunctionTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java
It is now also a ReferenceListener (prep for future)
It also has unit tests
=> Add BridgeListener improvements

code/src/itest/tokenmodel/testsupport/AbstractTokenModelTest.java, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/testcommon/plugin/lsttokens/testsupport/BuildUtilities.java
Fix Alignment Setup for Integration Tests
Fix PlayerCharacter to be dirty (need save) when Alignment changes
=> Fix Alignment Channel

code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java, code/src/java/pcgen/gui2/tabs/models/FormattedFieldHandler.java
More UI consistency.
Allows easier swap of different classes with similar behaviors.
=> Have FormattedFieldHandler extend ManagedField

code/src/java/pcgen/gui2/tabs/bio/BioItem.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java
Use Optional where appropriate to avoid null
Consolidation of duplicate methods
Reduce field count and clean interface (Create ItemListener at construction)
=> BioItem Cleanup

code/src/java/pcgen/facade/core/DescriptionFacade.java, code/src/java/pcgen/gui2/facade/DescriptionFacadeImpl.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java
The custom fields produce some really nasty indirection problems
for refactoring, so this eliminates them (by making them always
visible).  It is likely they will be restored in the future, albeit with
more flexibility.
=> Eliminate Custom Bio Fields

code/src/itest/tokencontent/GlobalModifyTest.java, code/src/java/pcgen/cdom/facet/FacetInitialization.java, code/src/java/pcgen/rules/persistence/TokenLibrary.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/utest/plugin/lsttokens/testsupport/AbstractGlobalTokenTestCase.java
Clean up misc errors associated with the test/improve test cleanup
=> Add Integration Test for Modify

outputsheets/d20/5e/htmlxml/csheet_fantasy_std.htm.ftl, outputsheets/d20/fantasy/htmlxml/csheet_fantasy_std.htm.ftl, outputsheets/d20/pathfinder_2/htmlxml/csheet_fantasy_std.htm.ftl, outputsheets/d20/starfinder/htmlxml/csheet_fantasy_std.htm.ftl, preview/d20/5e/Standard.htm.ftl, preview/d20/fantasy/Standard.htm.ftl, preview/d20/pathfinder_2/Standard.htm.ftl, preview/d20/starfinder/Standard.htm.ftl
This removes the large blanks caused by new paragraph blocks.
=> Outputsheets - Add p margin 0 to css

outputsheets/d20/fantasy/htmlxml/csheet_fantasy_std.htm.ftl
- close correct tag
- don't duplicate class
=> [fantasy sheet] mild improvements to output sheets

data/pathfinder/paizo/roleplaying_game/occult_adventures/oa_equip.lst
Tome has 50 charges
http://aonprd.com/MagicWondrousDisplay.aspx?FinalName=Tome%20of%20Origami%20Animals
=> Added charges to "Tome of Origami Animals"

code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java
=> CODE-3335 Gate item on null that is crashing swap between PCs

build.gradle
Bumps commons-collections4 from 4.2 to 4.3.
=> Build(deps): bump commons-collections4 from 4.2 to 4.3

data/pathfinder/paizo/roleplaying_game/ultimate_wilderness/uw_equip_general.lst
enabled container functionality to waist pouch
=> enabled container functionality

outputsheets/d20/fantasy/htmlxml/csheet_fantasy_std.htm.ftl, preview/d20/fantasy/Standard.htm.ftl
Fixes column spacing, adds ACP indicator, and removes Linguistics languages list.
=> OS - d20/Fantasy - Fix Skills

build.gradle
=> [build] remove vintage test runner.

code/src/java/pcgen/gui2/PCGenMenuBar.java
=> PCGMenuBar: implement cut/copy/paste

code/src/java/pcgen/cdom/enumeration/IntegerKey.java, code/src/java/pcgen/util/StringPClassUtil.java
Continue the campaign of removal of dead code
=> StringPClassUtil: clean  up and remove unused functions

code/src/java/pcgen/cdom/facet/fact/GenderFacet.java, code/src/java/pcgen/cdom/facet/fact/HeightFacet.java, code/src/java/pcgen/cdom/facet/fact/WeightFacet.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/utest/pcgen/cdom/facet/fact/GenderFacetTest.java, code/src/utest/pcgen/cdom/facet/fact/HeightFacetTest.java, code/src/utest/pcgen/cdom/facet/fact/WeightFacetTest.java
There is little need for special "set" or "get". Even the few "get" we
do need can likely be handled by making "null safe" as generic.
=> Facet: clean duplicative interfaces

code/src/java/pcgen/gui2/CharacterTabs.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenMenuBar.java, code/src/java/pcgen/gui2/tabs/CharacterSheetInfoTab.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/tabs/TempBonusInfoTab.java, code/src/java/pcgen/gui2/util/AbstractListMenu.java, docs/navtree.html
This looks like it'd be useful. Also remove a dead menu item.
=> [menu] Enable temporary bonus menu in "edit"

code/src/java/pcgen/cdom/facet/FacetLibrary.java
Add some logging so we know when we're falling back. Prep work for
removing fallback.
=> FacetLibrary add logging for fallback case

code/src/java/pcgen/gui2/tabs/EquipInfoTab.java, code/src/java/pcgen/gui2/tabs/PurchaseInfoTab.java
- This was previously non-functional as we never actually passed targets
into the handlers.
- Enable/Disable sort based on if the item is a container
=> [gui] Implement popup for Equipment Information tab

code/src/java/pcgen/gui2/tabs/PurchaseInfoTab.java, code/src/java/pcgen/resources/lang/LanguageBundle.properties
I introduced this difference, lets make (slightly) more clear the
difference.
=> CODE-2772: Add tooltip to sell and remove buttons

code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java
Replace ObjectTypeComparator with Comparator
Replace BonusComparator with comparator.comparing
=> Use Comparator if possible

code/src/java/pcgen/core/PlayerCharacter.java
Note that this is a change of behavior (previously it would get the
last rather than the first match.
=> getEquipmentNamed: replace with streams

code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/gui2/converter/panel/GameModePanel.java, code/src/java/pcgen/gui2/converter/panel/StartupPanel.java, code/src/java/pcgen/gui2/util/StatusWorker.java, code/src/java/pcgen/persistence/CampaignFileLoader.java, code/src/java/pcgen/persistence/GameModeFileLoader.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/system/BatchExporter.java, code/src/java/pcgen/system/Main.java, code/src/java/pcgen/system/PCGenTask.java, code/src/java/pcgen/system/PCGenTaskExecutor.java, code/src/java/pcgen/system/PluginClassLoader.java, code/src/test/pcgen/persistence/lst/DataLoadTest.java, code/src/test/pcgen/persistence/lst/DataTest.java, code/src/test/pcgen/util/TestHelper.java
This is pre-req work to make PCGenTaskExecutor use a ThreadPool instead
of doing things manually. Furthermore it's the "right" thing to do.
=> PCGenTest: implement Runnable

code/src/java/pcgen/gui2/SplashScreen.java, code/src/java/pcgen/system/PCGenTask.java, code/src/java/pcgen/system/PCGenTaskEvent.java, code/src/java/pcgen/system/ProgressContainer.java
This is more pre-req work to enable splitting PCGenTask from
PCGenTaskExecutor.
=> PCGenTask: introduce ProgressContainer interface.

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_arms_armor.lst
Price was incorrect in UE files, now fixed.
=> DATA-3890 [UE] Fixed price of Four-Mirror armor

outputsheets/d20/fantasy/pdf/common_sheet/block_spells_condensed.xslt
manual handling of spells for slots 10+ (until 30)
There may be a better way to do so (with a loop), but I don't know XSLT well, and I don't think many characters will have that must spell slots
=> handle spell levels > 9 and < 30

docs/installationpages/installationjava.html, docs/installationpages/requirements.html
We badly need someone to do a fairly extensive audit of the
documentation. That said, in the meantime, here is a quick and dirty
update for some the starter pages.
=> [docs] first pass of updating minimum requirements

code/src/java/pcgen/core/SpellSupportForPCClass.java, code/src/test/pcgen/core/PCClassTest.java
Spell slots given by Improved Spell Capacity are subject to bonus slots via high statistics
=> bonus spells for SPELLCAST bonus slots

code/src/java/pcgen/core/BonusManager.java, code/src/java/pcgen/gui2/facade/TempBonusHelper.java
- delete BonusInfo which is an older and unused version of TempBonusInfo
- remove some unused functions
- perform some basic cleanup which will be helpful to propagate "temp
bonuses changed" in the future.
=> BonusManager: clean up

code/src/java/pcgen/gui2/dialog/DataInstaller.java, code/src/java/plugin/notes/gui/NotesView.java
Using the standard APIs is likely to be faster and/or more
understandable in most cases. In the event we need custom stuff we can
implement it in a proper utility method.
p.s. why is file reading/writing happening inside of "gui2" code?
=> [*] Use modern Java APIs for reading buffers instead of homebrewing

code/src/java/pcgen/util/Logging.java, code/src/java/pcgen/util/PCGenLogLevel.java
Logging: fix logging
- remove beep(). Its irksome.
- have error printing call errorPrint rather than system.out
- remove useless toString
=> Logging: fix logging

code/src/itest/plugin/lsttokens/editcontext/equipment/WieldIntegrationTest.java
Because speeling is important.
=> Rename WeildIntegrationTest to WieldIntegrationTest

code/src/java/pcgen/gui2/dialog/ExportDialog.java, code/src/java/pcgen/gui2/dialog/PrintPreviewDialog.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/io/PCGIOHandler.java, code/src/java/pcgen/persistence/lst/utils/VariableReport.java, code/src/java/pcgen/system/BatchExporter.java, code/src/java/plugin/notes/gui/NotesTreeNode.java, code/src/java/plugin/notes/gui/NotesView.java, code/src/test/pcgen/gui2/ScanForUnusedIl8nKeys.java, code/src/test/plugin/FacetDefinitionTest.java
This is useful since most of what we're using commos-io
for is actually availble in native jdk
=> reduce reliance on commons-io

code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/formula/scope/GlobalEQScope.java
This will allow us to add variables to equipment that don't rely on on
the PC.
=> NEWTAG-627: Add GlobalEQScope

code/gradle/autobuild.gradle, code/gradle/distribution.gradle, code/src/java/pcgen/gui2/converter/ObjectInjector.java, code/src/java/pcgen/gui2/converter/panel/RunConvertPanel.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/output/base/SimpleWrapperLibrary.java, code/src/java/pcgen/output/model/DateModel.java, code/src/java/pcgen/output/wrapper/DateWrapper.java, code/src/java/pcgen/util/SourceLogFormatter.java, code/src/java/pcgen/util/fop/FopTask.java, code/src/java/plugin/exporttokens/deprecated/ExportToken.java, code/src/java/plugin/lsttokens/SourcedateLst.java, code/src/test/pcgen/gui2/ScanForUnusedIl8nKeys.java, code/standards/ruleset.xml
Some usages can't be removed (e.g., fop)
=> [*] reduce obsolete Date/Time APIs

code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/csheet/CharacterSheetPanel.java, system/Languages/LanguageBundle_en_US.properties
- enables us to eliminate two old and buggy dependencies
- improves speed of output sheet panel
- enables the use of modern HTML5 in output sheets
- enables the use of JavaScript in output sheets
- enables interaction between java code and output sheet (e.g., changing
data in OS itself)
- moves us closer to migrating away from Swing.
=> CharacterSheetPanel: convert from swing to JavaFX webview

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities.lst
=> pathfinder data: add GM Awards for movement speed.

code/src/java/pcgen/cdom/facet/analysis/UnarmedDamageFacet.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/core/PCClass.java, code/src/java/pcgen/io/exporttoken/WeaponToken.java, code/src/java/plugin/exporttokens/EqContainerToken.java, code/src/java/plugin/exporttokens/EqContainersToken.java, code/src/java/plugin/exporttokens/EqContainerwToken.java, code/src/test/pcgen/core/GlobalsTest.java
Overall, this gets Damage Adjustment away from a tight tie to SizeAdjustment objects - preparation for a data-controlled world
=> AdjustDamage updates to take a differential value vs SizeAdjustments

build.gradle, code/src/java/pcgen/gui3/package-info.java
=> [gui] make new gui3 code stricter w.r.t. code standards

code/src/java/pcgen/io/ExportHandler.java
Previous the list was sorted, and then ignored.
=> ExportHandler: make use of sorted list

code/pluginbuild.xml, code/src/itest/plugin/lsttokens/editcontext/equipment/WeildIntegrationTest.java, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/persistence/GameModeFileLoader.java, code/src/java/pcgen/persistence/lst/WieldCategoryLoader.java, code/src/java/pcgen/util/StringPClassUtil.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/WieldCatToken.java, code/src/java/plugin/lsttokens/gamemode/wieldcategory/DownToken.java, code/src/java/plugin/lsttokens/gamemode/wieldcategory/SizediffToken.java, code/src/java/plugin/lsttokens/gamemode/wieldcategory/UpToken.java, code/src/test/pcgen/AbstractCharacterTestCase.java, code/src/test/pcgen/AbstractJunit5CharacterTestCase.java, code/src/testcommon/util/GameModeSupport.java, code/src/utest/plugin/lsttokens/equipment/WieldTokenTest.java
Add WieldCategory so it can be a format
=> NEWTAG-624 Implement WieldCategory CodeControl

code/pluginbuild.xml, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/core/Equipment.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/CostMultiplierToken.java
=> NEWTAG-632: Implement COSTMULTIPLIER for equipment

code/gradle/reporting.gradle
The given link probably gives enough information to fix, but I'm tired
so start by just linking it :)
=> [build] update comment for broken spotbugs config

code/src/resources/applicationContext.xml
No real change, but long term we should split out the resources dir
from the code dir.
=> applicationContext: move to new resources directory

code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/grouping/GroupingCollection.java, code/src/java/pcgen/cdom/grouping/GroupingScopeFilter.java
Fixes the interface & implementation - better names
=> CODE-3400 Fix: Grouping should be passed the TARGET not the source

code/src/java/pcgen/base/test/InequalityTester.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/utest/plugin/lsttokens/race/FaceTokenTest.java, code/src/utest/plugin/lsttokens/template/FaceTokenTest.java, code/standards/ruleset.xml
We've cleaned up the code base enough that some of these no longer need
to be excluded wholesale.
=> pmd: reduce number of exclusions

code/src/java/pcgen/core/doomsdaybook/DataValue.java, code/src/java/pcgen/core/doomsdaybook/WeightedDataValue.java
Weight is never modified, so remove the ability to do so
=> Removed unused code from WeightedDataValue

code/src/java/pcgen/gui2/converter/panel/ConversionInputDialog.java, code/src/java/pcgen/gui2/converter/panel/RunConvertPanel.java
Unused features adds complexity to the JavaFX migration.
=> RunConvertPanel: remove unused features / code

code/src/java/pcgen/gui3/component/PCGenStatusBar.java, code/src/java/pcgen/gui3/component/PCGenStatusBarModel.java, code/src/resources/pcgen/gui3/component/PCGenStatusBar.fxml
=> PCGenStatusBar: show percent done as label

code/src/java/pcgen/core/utils/LastGroupSeparator.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/system/CharacterManager.java, code/src/java/plugin/initiative/gui/DamageDialog.java
Partial commit of #5272. Resolves some pmd issues in later versions
=> [*] remove some unneeded "throws"

code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/facade/SpellBuilderFacadeImpl.java, code/src/java/pcgen/gui2/prefs/EquipmentPanel.java, code/src/java/pcgen/gui3/JFXPanelFromResource.java, code/src/java/pcgen/gui3/ResettableController.java, code/src/java/pcgen/gui3/preferences/EquipmentPreferencesModel.java, code/src/java/pcgen/gui3/preferences/EquipmentPreferencesPanelController.java, code/src/resources/pcgen/gui3/preferences/EquipmentPreferencesPanel.fxml
This also converts some of our preferences to properties, establishing a 
new pattern.
Depends on #5579
=> EquipmentPreferencesPanel: convert to JavaFX

code/src/java/pcgen/gui2/plaf/LookAndFeelManager.java
Let them sort however the system gives them to us.
=> LookAndFeel remove special sorting

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/gui2/prefs/PurchaseModeFrame.java, code/src/java/pcgen/gui2/tabs/bio/PortraitPane.java, code/src/java/pcgen/gui2/util/ArrowIcon.java, code/src/java/pcgen/gui2/util/table/IntegerEditor.java, code/src/java/plugin/exporttokens/PortraitToken.java, code/src/java/plugin/overland/gui/OverPanel.java, code/src/java/plugin/pretokens/test/PreItemTester.java, code/standards/ruleset.xml
Ignore a few for loops that declare multiple variables.
=> PMD: start enforcing OneDeclarationPerLine

build.gradle, code/src/java/pcgen/gui3/preloader/PCGenPreloader.java, code/src/resources/pcgen/gui3/preloader/PCGenPreloader.fxml, code/src/utest/pcgen/gui3/preloader/PCGenPreloaderTest.java
Add the infrastructure to write UI tests.
=> JavaFX: add the first UI test

code/src/java/pcgen/core/SpellProgressionCache.java
congrats thpr - you got rid of all the usages!
=> SpellProgressionCache: remove several unused functions

build.gradle
This allows us to produce native images using jlink.
=> [gradle] introduce "runtime" goal

code/src/java/gmgen/GMGenSystemView.java
The ChangeListener doesn't do anything. This is a pre-req to converting
GMGenSystemView to JavaFX
=> GMGenSystemView: unimplement ChangeListener

code/src/java/pcgen/gui2/prefs/LanguagePanel.java
This breaks the pattern of JavaFX due to the current data model. Further
it shows that while JavaFX makes it *easier* - it isn't required.
=> LanguagePanel: convert to JavaFX

code/src/java/pcgen/core/SettingsHandler.java
This removes two unused functions and removing some explicit unboxing.
=> SettingsHandler: another round of cleaning

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/plaf/DesktopHandler.java
There is nothing mac specific in the handler anymore. We actually want
the behavior in all platforms.
=> MacGUIHandler: use for all platforms

code/src/java/plugin/initiative/OpposedSkillBasicModel.java, code/src/java/plugin/initiative/gui/TableColumnInformation.java
There is only one usage, and it adds little value
=> TableColumnInformation: remove initial capacity

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/core/SettingsHandler.java
As we convert to JavaFX these settings will become less meainngful, and
size-settings would work differently. In prep for a complete conversion,
removing the settings which won't be meaningful in the future.
=> SettingsHandler: stop saving screen size

code/src/resources/pcgen/gui3/dialog/DebugDialog.css, code/src/resources/pcgen/gui3/dialog/DebugDialog.fxml
- show all rows on dialog
- avoid fixed size dialog
=> Display improvements for debug pane

code/src/java/pcgen/gui2/InfoGuidePane.java
This was a feature of the previous implementation I did not port over.
Also it fixes an odd UI quirk.
=> InfoGuidePane: hide pane when character is selected

code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/dialog/ExportDialog.java
also convert several standard dialog
=> [*] continue converting from JFileChooser to FileChooser

code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties
These are no longer required/useful in the JavaFX`world.
=> Language: remove extraneous HTML tags

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui3/preferences/ConvertedJavaFXPanel.java
gui3 included "conversion support" code.
=> ConvertedJavaFXPanel: move to gui3 package

data/pathfinder/paizo/player_companion/occult_origins/oo_abilities_class.lst
=> Occult_origins_fix_052519

code/src/java/pcgen/gui2/PCGenFrame.java
Long term we'll need to be better about ensuring functions get called on
the right thread. In the short-medium term we'll be crossing between
swing and Java fairly often,
=> Move pcgen frame alerts to JavaFX thread

code/src/java/pcgen/cdom/enumeration/FormulaKey.java, code/src/java/pcgen/cdom/enumeration/IntegerKey.java, code/src/java/pcgen/cdom/enumeration/ObjectKey.java, code/src/java/pcgen/cdom/formula/VariableUtilities.java, code/src/java/pcgen/core/display/TemplateModifier.java, code/src/java/pcgen/core/display/UnarmedDamageDisplay.java, code/src/java/pcgen/gui2/converter/TokenConverter.java, code/src/java/pcgen/gui2/facade/TempBonusHelper.java, code/src/java/pcgen/gui2/tabs/ability/AbilityTreeViews.java, code/src/java/pcgen/gui2/tools/CommonMenuText.java, code/src/java/pcgen/gui2/util/FontManipulation.java, code/src/java/pcgen/gui2/util/table/TableUtils.java, code/src/java/plugin/overland/model/TravelMethodFactory.java, code/standards/ruleset.xml
These rules are now enforced:
- UseUtilityClass
- IntegerInstantiation
- ClassWithOnlyPrivateConstructorsShouldBeFinal
=> pmd: Enforce more rules; add more excuses

code/src/java/gmgen/gui/PreferencesDialog.java, code/src/java/plugin/initiative/InitiativePlugin.java, code/src/java/plugin/initiative/gui/Initiative.java
These are being removed in the JavaFX rewrite.
=> [*] remove several gui-state-restore options

code/src/java/pcgen/gui2/csheet/CharacterSheetPanel.java
We'll eventually expose the choice of CSS directly, in the meantime
don't mangle CSS internally.
=> CharacterSheetPanel: don't handle CSS specially

code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties
These tags are no longer needed and show up as literal text.
=> Translations: remove some HTML tags

code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/LevelInfo.java, code/src/java/pcgen/core/kit/KitAbilities.java, code/src/java/pcgen/io/PCGIOHandler.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/pcgen/io/exporttoken/SkillpointsToken.java, code/src/java/plugin/lsttokens/deprecated/TemplateFeatToken.java, code/standards/ruleset.xml
- start enforcing AvoidDecimalLiteralsInBigDecimalConstructor
=> pmd: yet another round of excuses, fixes, and enforcement

code/src/java/plugin/notes/gui/NotesView.java
While this would be nice to keep, it isn't currently active, and the
JavaFX conversion will force a rewrite anyways
=> NotesView: remove unused drop-target code

code/src/java/gmgen/GMGenSystem.java
=> GMGenSystem: Unimplement MenuListener

code/src/java/pcgen/core/SettingsHandler.java
These are also handled by PCGenSettings
- showSkillModifier
- showSkillRanks
- pcgen.files.portraits
=> SettingsHandler: remove more unused settings

code/src/java/pcgen/gui2/dialog/ExportDialog.java
Finding templates isn't particularly expensive and makes following the
logic for how this dialog gets initialized confusing.
=> ExportDialog: pull file searching out of thread

code/src/java/gmgen/plugin/Combatant.java, code/src/java/gmgen/plugin/Effect.java, code/src/java/gmgen/plugin/Event.java, code/src/java/gmgen/plugin/Spell.java, code/src/java/pcgen/gui2/doomsdaybook/NameGenPanel.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java, code/src/java/plugin/encounter/EncounterPlugin.java, code/src/java/plugin/initiative/gui/AttackDialog.java, code/src/java/plugin/initiative/gui/Initiative.java, code/src/java/plugin/notes/gui/NotesTreeNode.java, code/src/java/plugin/notes/gui/NotesView.java, code/src/java/plugin/overland/model/TravelMethodFactory.java, code/standards/ruleset.xml
This mostly just adds the excludes to the same places where we exclude
other Vector related PMD checks
=> PMD: enforce UseArrayListInsteadOfVector

code/src/java/plugin/notes/gui/NotesTreeNode.java, code/src/java/plugin/notes/gui/NotesView.java
Similar to 1acffbef43130abb491d51ab7b0495088e4a309e
While this would be nice to keep, it isn't currently active, and the
JavaFX conversion will force a rewrite anyways
=> NotesView: continue dropping drop-target

code/src/resources/pcgen/gui3/preferences/DisplayOptionsPreferencesPanel.fxml, code/src/resources/pcgen/gui3/preferences/EquipmentPreferencesPanel.fxml, code/src/resources/pcgen/gui3/preferences/InputPreferencesPanel.fxml, code/src/resources/pcgen/gui3/preferences/LevelUpPreferencesPanel.fxml
The TitlePane doesn't add much and mildly confuses the layout.
=> preference panes: stop using TitledPane

code/src/java/pcgen/cdom/enumeration/FormulaKey.java, code/src/java/pcgen/cdom/enumeration/IntegerKey.java, code/src/java/pcgen/cdom/enumeration/ObjectKey.java, code/src/java/pcgen/core/utils/LastGroupSeparator.java, code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/equip/EquipCustomPanel.java, code/src/java/pcgen/gui2/facade/SpellSupportFacadeImpl.java, code/src/java/pcgen/gui3/preferences/EquipmentPreferencesModel.java, code/standards/checkstyle.xml
I had forgotten that we set the severity to "warning" in a previous
effort to clean up.
=> checkstyle: actually enforce things

code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java
This causes a freeze bug for @LegacyKing. 
This reverts commit ec7c3513410b839b2c389b5a766c68276e8ac780.
=> Revert "CODE-3248: store language choosers in CharacterFacadeImpl (#5438)"

code/standards/checkstyle-suppressions.xml
Instead of testing and suppressing, just stop testing for the things we
ignore. We can add real suppressions later as we begin to enforce more.
=> Checkstyle: remove suppressions

code/src/java/pcgen/gui2/dialog/AbstractDialog.java
This will simplify porting to JavaFX
=> AbstractDialog: remove unused features

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java
As nicer as FlippingSplitPane is, it isn't required for preferences.
=> PreferencesPanel: downgrade from FlippingSplitPane to JSplitPane

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/prefs/OutputPanel.java
=> OutputPanel: convert to JavaFX

code/src/java/gmgen/gui/PreferencesDialog.java, code/src/java/gmgen/gui/PreferencesPanel.java, code/src/java/gmgen/gui/PreferencesRootTreeNode.java, code/src/java/gmgen/pluginmgr/messages/RequestAddPreferencesPanelMessage.java, code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui3/GuiAssertions.java, code/src/java/pcgen/gui3/JFXPanelFromResource.java, code/src/java/pcgen/gui3/preferences/ColorsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/ConvertedJavaFXPanel.java, code/src/java/pcgen/gui3/preferences/CopySettingsPanelController.java, code/src/java/pcgen/gui3/preferences/DefaultsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/DisplayOptionsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/PreferencesPluginsPanel.java, code/src/java/pcgen/gui3/preferences/SourcesPreferencesPanelController.java, code/src/java/plugin/experience/ExperienceAdjusterPlugin.java, code/src/java/plugin/experience/gui/PreferencesExperiencePanel.java, code/src/java/plugin/initiative/InitiativePlugin.java, code/src/java/plugin/initiative/gui/PreferencesDamagePanel.java, code/src/java/plugin/initiative/gui/PreferencesInitiativePanel.java, code/src/java/plugin/initiative/gui/PreferencesMassiveDamagePanel.java, code/src/java/plugin/initiative/gui/PreferencesMiscPanel.java, code/src/java/plugin/initiative/gui/PreferencesPerformancePanel.java, code/src/java/plugin/initiative/gui/PreferencesTrackingPanel.java, code/src/java/plugin/notes/NotesPlugin.java, code/src/java/plugin/notes/gui/PreferencesNotesPanel.java
Previously there were two types of PCGen specific JDialog wrappers. Now 
there are one.
Depends on #5852 and #5854
=> Preferences: unify preference dialog types

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/converter/PCGenDataConvert.java, code/src/java/pcgen/gui2/coreview/CoreViewFrame.java, code/src/java/pcgen/gui2/dialog/CharacterHPDialog.java, code/src/java/pcgen/gui2/dialog/DataInstaller.java, code/src/java/pcgen/gui2/dialog/EquipCustomizerDialog.java, code/src/java/pcgen/gui2/dialog/ExportDialog.java, code/src/java/pcgen/gui2/dialog/KitSelectionDialog.java, code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java, code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/dialog/PrintPreviewDialog.java, code/src/java/pcgen/gui2/dialog/RandomNameDialog.java, code/src/java/pcgen/gui2/dialog/SpellChoiceDialog.java, code/src/java/pcgen/gui2/prefs/CharacterStatsPanel.java, code/src/java/pcgen/gui2/solverview/SolverViewFrame.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/tabs/SummaryInfoTab.java, code/src/java/pcgen/gui2/tabs/summary/LanguageTableModel.java, code/src/java/pcgen/gui2/tools/Utility.java
The special handling isn't required anymore (setLocationRelativeTo
does the same) and the logic will have to change with JavaFX anyways.
=> gui2: simplify component centering

code/src/java/pcgen/cdom/reference/FilteredReference.java, code/src/java/pcgen/core/BonusManager.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/Kit.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/term/PCCountEquipmentTermEvaluator.java, code/src/java/pcgen/io/exporttoken/EqToken.java, code/src/java/pcgen/persistence/lst/prereq/AbstractPrerequisiteListParser.java, code/src/java/pcgen/persistence/lst/utils/VariableReport.java, code/src/java/plugin/exporttokens/deprecated/TemplateToken.java, code/src/java/plugin/lsttokens/gamemode/tab/SkilltablehiddencolumnsToken.java, code/src/java/plugin/lsttokens/gamemode/tab/StattablehiddencolumnsToken.java, code/src/java/plugin/modifier/set/AddModifierFactory.java
These are all found by Intellij static analysis tools.  i stuck with simple ones that could be found and replaced easily.
=> fixes many small performance issues

code/src/java/pcgen/gui2/dialog/PrintPreviewDialog.java, code/src/java/pcgen/gui2/util/table/TableCellUtilities.java
(untested, but this may actually fix the previous bug)
=> TableCellUtilities: remove workaround for nimbus

code/src/utest/pcgen/gui3/tools/IconsTest.java
one more swing ref knocked down
=> IconsTest: test JavaFX representation instead of swing

code/src/java/pcgen/gui2/dialog/AbstractDialog.java, code/src/java/pcgen/gui2/dialog/ChooserDialog.java, code/src/java/pcgen/gui2/dialog/EquipCustomizerDialog.java, code/src/java/pcgen/gui2/dialog/LanguageChooserDialog.java, code/src/java/pcgen/gui2/dialog/RadioChooserDialog.java, code/src/java/pcgen/gui2/dialog/RandomNameDialog.java, code/src/java/pcgen/gui2/dialog/SinglePrefDialog.java, code/src/java/pcgen/gui2/dialog/SpellChoiceDialog.java, code/src/java/pcgen/gui2/prefs/PurchaseModeFrame.java, code/src/java/pcgen/gui3/component/OKCloseButtonBar.java, code/src/java/pcgen/gui3/core/IORuntimeException.java, code/src/resources/pcgen/gui3/component/OKCloseButtonBar.fxml, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties
This is #5895 for LanguageChooserDialog. It is a separate PR to 
reduce/eliminate the conflicts
Depends on #5895 and #5894
=> LanguageChooserDialog: convert to OKCloseButtonBar

code/src/java/pcgen/system/Main.java
this also reduced time from 8 ms to 1 ms, but the real value is that it's easier to read.
=> cleaned up logging method to be more straight forward.

code/src/java/pcgen/core/VariableProcessor.java, code/src/java/pcgen/gui2/csheet/CharacterSheetPanel.java, code/src/java/pcgen/gui2/tabs/models/HtmlSheetSupport.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/io/FreeMarkerExportHandler.java, code/src/java/pcgen/io/PCGenExportHandler.java, code/src/java/pcgen/system/BatchExporter.java, code/src/test/pcgen/io/ExportHandlerTest.java, code/src/test/pcgen/io/exporttoken/AbilityListTokenTest.java, code/src/test/pcgen/io/exporttoken/AbilityTokenTest.java, code/src/test/pcgen/io/exporttoken/TextTokenTest.java, code/src/test/pcgen/io/freemarker/PCBooleanFunctionTest.java, code/src/test/pcgen/io/freemarker/PCHasVarFunctionTest.java, code/src/test/plugin/exporttokens/BioTokenTest.java, code/src/test/plugin/exporttokens/CampaignHistoryTokenTest.java, code/src/test/plugin/exporttokens/VAbilityTokenTest.java
classes that switch on enums are possible candidates for converting to inheritance models.  i have done so here since this class in question appears to have 2 very different, independent, workflows.
=> addressed Enum internal switching code smell

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui3/dialog/DebugDialog.java
Previously, the dialog would not be shown multiple times as we only show
on create.
=> [DebugDialog] allow opening and closing multiple times

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_class.lst
=> [UM] Needed to update bloodline tracker for feat/spells

code/src/java/pcgen/gui2/dialog/ExportDialog.java
https://pcgenorg.atlassian.net/browse/CODE-3451
The fix is simple, I raised some questions in the solution section of 3451 that may need to be discussed before or after pulling.
=> Fix CODE-3451: Simply remove redundant dialog.

code/src/java/pcgen/facade/core/DescriptionFacade.java, code/src/java/pcgen/gui2/facade/DescriptionFacadeImpl.java, code/src/java/pcgen/gui2/tabs/bio/BioItem.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java
- Modify setBiographyField to update bioItem.
- Replace redundant HairStyle subclass.
- Remove errant Javadoc.
------
Fixes the associated JIRA ticket and a few things along the way.
=> FIX CODE-3456: Text Disappearing on Description

code/src/java/pcgen/gui2/tabs/bio/BioItem.java, code/src/java/pcgen/gui2/tabs/bio/BiographyInfoPane.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/testResources/pcgen/lang/cleaned.properties
This adds complexity to the UI and is one of two special places where we
handle have-this-but-don't-show-it.
=> [bio] remove show/hide checkboxes

code/src/java/pcgen/gui2/dialog/DataInstaller.java
- Another JavaFX/Swing cross over problem.
=> FIX CODE-3466: Install data feature broken

README.md
- Add information on how to join team & setup development.
---------------------------------
Before merging, do note if I missed anything. Tried to put enough info to help new people and reference links to stuff we need.
=> FIX CODE-3478: Update The README.

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui3/dialog/DebugDialog.java
Currently loading debug dialog fails since it is on the wrong thread.
Fix this, and add more assertions to catch this earlier
=> [gui] fix debug dialog threading

code/src/java/pcgen/core/Globals.java
found a global field that can be removed for being redundant.  this should make future performance enhancements easier.
=> removed redundant field and cleaned up javadoc

code/src/java/pcgen/gui2/sources/SourceSelectionDialog.java
while looking for ways to modernize code i found an embedded class that was not being used.
=> removed unused subclass

code/src/java/pcgen/cdom/facet/analysis/MovementResultFacet.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/gui2/tabs/EquipInfoTab.java, code/src/java/pcgen/util/enumeration/Load.java
functionality related to the Load class was in other places, so i consolidated it
=> moved methods related to Load into the Load class and refactored

code/src/java/pcgen/cdom/base/Constants.java, code/src/java/pcgen/core/SettingsHandler.java
Refactored Color constants to the class that calls them.
Looks ok and passes the validation build locally.
=> Refactored Color constants

data/pathfinder_pfs/paizo/pathfinder_society/organized_play/gtpsop_kits.lst, data/pathfinder_pfs/paizo/pathfinder_society/organized_play/gtpsop_templates.lst, data/pathfinder_pfs/paizo/pathfinder_society/roleplaying_guild_guide/rgg_templates.lst
Standardize differences between Guide To Pathfinder Society Organized Play and Roleplaying Guild Guide for PFS.
=> Standardize PFS Templates and Kits

build.gradle
Release notes: https://github.com/openjdk/jfx/blob/jfx14/doc-files/release-notes-14.0.1.md#release-notes-for-javafx-1401
=> [javafx] bump to JavaFX 14

code/src/java/pcgen/cdom/base/CDOMObject.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/persistence/lst/CampaignLoader.java, code/src/java/pcgen/system/BatchExporter.java, code/src/test/pcgen/persistence/lst/DataLoadTest.java, code/src/test/pcgen/persistence/lst/DataTest.java
other changes support that refactor
=> refactored and cleaned focusing on SourceFileLoader

code/src/java/pcgen/core/term/PCCountSpellsKnownTermEvaluator.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/plugin/lsttokens/kit/levelability/LevelAbilityToken.java, code/src/java/plugin/lsttokens/pcclass/HdToken.java, code/src/java/plugin/lsttokens/pcclass/MaxlevelToken.java, code/src/java/plugin/lsttokens/spell/ClassesToken.java, code/src/java/plugin/lsttokens/spell/DomainsToken.java, code/src/utest/plugin/lsttokens/pcclass/HDTokenTest.java
Removing a -> a casts as identified by Eclipse
=> Remove unncessary casts

build.gradle, gradle.properties
Fix issues with application configuration in intellij caused by missing JavaFX libs. Issue was introduced in https://github.com/PCGen/pcgen/pull/6243.
=> Fixed intellij configuration issues.

data/pathfinder/paizo/player_companion/blood_of_the_moon/_pfs/pfs_botm_abilities_traits.lst, data/pathfinder/paizo/player_companion/blood_of_the_moon/_pfs/pfs_botm_feats.lst, data/pathfinder/paizo/player_companion/blood_of_the_moon/_pfs/pfs_botm_races.lst, data/pathfinder/paizo/player_companion/blood_of_the_moon/_pfs/pfs_botm_spells.lst
Remove unnecessary requirement to bring it in line with other non-legal PFS races.
=> Bug Fix: PFS BOTM Remove Requirement

README.md
Given that many people looking to run this software aren't developers, it seems useful to put a set of basic installation instructions at the top of the README. Devs will most likely be OK scrolling down a bit more :)
=> Update README with instructions for installation

code/src/resources/pcgen/gui3/dialog/DebugDialog.fxml
Problem
AnchorPane is fixed size and thus resizing the debug dialog does not
resize the sub-panes.
Solution
Remove the wrapped AnchorPane
=> [gui3] make DebugDialog resizeable

.gitignore
added vim temp files to gitignore
=> vim-gitignore

code/src/resources/pcgen/gui3/dialog/ExportDialog.fxml
I forgot to add this to a prior commit and had it locally for ages
=> [export] add missing ExportDialog

code/src/java/plugin/function/GroupFunction.java
We currently create a list of available items but then throw it away. We
should actually return it.
=> [bugfix] honor available in GroupFunction

code/src/java/plugin/lsttokens/choose/LangToken.java
=> [bugfix] fix window name of "Language choice" dialog

code/src/java/pcgen/cdom/facet/base/AbstractCNASEnforcingFacet.java, code/src/java/pcgen/cdom/helper/ClassSkillChoiceActor.java, code/src/java/pcgen/core/BonusManager.java, code/src/java/pcgen/core/character/SpellBook.java, code/src/java/pcgen/gui2/doomsdaybook/NameGenPanel.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/io/PCGVer2Creator.java, code/src/test/pcgen/persistence/lst/DataTest.java, code/src/utest/pcgen/cdom/formula/testsupport/AbstractModifier.java
- prefer enhanced for over while
- prefer pattern variables where possible
- prefer EnumMap where possible
=> [codequal] minor java QoL improvements

PCGen-Formula/build.gradle, PCGen-Formula/gradle/wrapper/gradle-wrapper.properties, PCGen-Formula/settings.gradle
- add a new settings.gradle (else it inherits the parent)
- remove uploadArchives which is going to not be needed with build merge
- explicitly require allowInsecureProtocol for ivy repo
=> [formula] bump gradle to 7.2

PCGen-base/build.gradle, PCGen-base/gradle/wrapper/gradle-wrapper.properties, PCGen-base/settings.gradle
- rename `testRuntime` to `testRuntimeOnly`
- remove soon to be unused uploadArchives
- add settings.gradle to create root
=> [base] bump gradle to 7.2

gradle/wrapper/gradle-wrapper.properties
There is no functional for us just yet. Just a build bump.
=> [build] update gradle to 7.3

code/gradle/release.gradle
=> fix downloadJRE

build.gradle
We have no current need for preview features.
=> [build] remove `--enable-preview`

code/src/java/pcgen/gui2/tabs/spells/SpellBooksTab.java, code/src/java/pcgen/gui2/tabs/spells/SpellsKnownTab.java, code/src/java/pcgen/gui2/tabs/spells/SpellsPreparedTab.java
Instead of combination of Box'es, JPanel is used in these tabs.
=> CODE-3527: fixes SpellBooksTab, SpellsKnownTab and SpellsPreparedTab.

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/tools/DesktopBrowserLauncher.java, code/src/java/pcgen/gui2/tools/InfoPaneLinkAction.java, code/src/java/pcgen/gui3/dialog/AboutDialog.java, code/src/java/pcgen/gui3/dialog/AboutDialogController.java, code/src/resources/pcgen/gui3/dialog/AboutDialog.fxml, code/src/utest/pcgen/gui3/dialog/AboutDialogTest.java
Now the About dialog can be properly sized by the user.
The tabs cannot be closed anymore
Changed few lines related to URL class whose public constructors will be deprecated in JDK 20.
Changed styled of few elements in About dialog (added paddings)
p.s. you can squash this PR, if you approve it, because I have introduced two commits.
=> Improved About dialog sizing behavior

code/src/itest/plugin/lsttokens/editcontext/testsupport/AbstractIntegerIntegrationTestCase.java, code/src/java/pcgen/gui3/dialog/AboutDialog.java, code/src/testResources/pcgen/lang/cleaned.properties, code/src/testResources/pcgen/lang/unused.properties
The test  was failing, because PreMultParser wasn't registered for the string "PREMULT:1,[PREHD:MIN=1],[PRELEVEL:MIN=1]"
Changed the formatting of AboutDialog, because Checkmarx tests were failing.
cleaned and unused property files were updated by the Gradle tasks.
=> Fixed the failed "slowtest": STARTFEATS

code/src/test/pcgen/AbstractCharacterTestCase.java
@karianna, I have removed the comment based on your code review.
=> Removed redundant comment after the code review in AbstractCharacterTestCase.java

code/testsuite/csheets/pf_Cleric.xml, code/testsuite/csheets/pf_Paladin.xml
There are two simple commits that fix the failed integration tests.
@LegacyKing you were the one, who agreed that traits should disappear from XML. At least, this is expected for you.
=> Fixed: Updated expected templates (csheet files)

code/testsuite/PCGfiles/sf_mechanic.pcg, code/testsuite/PCGfiles/sf_soldier.pcg
Fix the PCG test characters to reflect updated values.
=> 2023 07 07

build.gradle, code/src/java/pcgen/gui3/component/PCGenToolBar.java
needed to add xalan/serializer to build.gradle for print to work
commented out gui assertion that was preventing preview from working.
=> fix print and export

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/core/term/PCCasterLevelTotalTermEvaluator.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/io/exporttoken/Token.java
more complete support for .INFO. export.
=> Info export

data/pathfinder/paizo/roleplaying_game/bestiary_2/b2_abilities_familiar.lst
COMPANIONLIST doesn't like PREALIGN
=> [HELP-228] PF B2 Familiars not populating
