code/src/java/pcgen/cdom/facet/base/AbstractAssociationFacet.java
Template w/ SIZE:L is breaking the character sheets - java.lang.IllegalArgumentException: CDOMObject cannot be null
=> Fix bug: CODE-2848 - Template removal - CDOMObject cannot be null

code/src/java/pcgen/core/DataSet.java, code/src/java/pcgen/gui2/tabs/ability/AbilityTreeViews.java
Exclude negative (i.e. must not have) prereqs from the prereq tree for abilities.
=> Fix bug: CODE-2858 - infinite loop in ability prereq tree view

docs/faqpages/faqcommunity.html, docs/faqpages/faqcommunity.md, docs/navtree.html
This is a new page detailing where to find PCGen help, resources, and community discussion.
It is meant to improve on the information currently duplicated across pcgen.org, wiki.pcgen.org, and pcgen.sf.net.
1. http://pcgen.org/get-help/
2. http://pcgen.org/get-involved/
3. http://wiki.pcgen.org/Users
4. http://pcgen.sourceforge.net/04_support.php
5. http://pcgen.sourceforge.net/05_email_lists.php
6. http://pcgen.sourceforge.net/06_trackers.php
Points open to discussion;
* Whether it's more appropriate to have this in the HTML documentation, on the pcgen.org website, or the wiki
* the relative importance of Yahoo Groups vs. the new phpBB forums
* sections I probably haven't included like Donations
Whatever is decided, I think it is important for there to be exactly one place for this …
=> Add new page to FAQ - "Community"

code/pluginbuild.xml, code/src/itest/pcgen/io/GeneralSaveRestoreTest.java, code/src/java/plugin/exporttokens/deprecated/TemplateListToken.java, code/src/java/plugin/exporttokens/deprecated/TemplateToken.java
Template already in output model, this is deprecation only
Deprecate TEMPLATE and TEMPLATELIST output tokens
=> NEWTAG-511

code/src/java/pcgen/rules/context/TrackingReferenceContext.java
Avoid problems if methods are re-entrant
fix: Unconstructed references error log is spewing tons of extra (useless) lines
=> CODE-2894 Unconstructed references error log is spewing tons of extra (useless) lines

outputsheets/d20/fantasy/pdf/common_sheet/block_equipment.xslt
Equipping more than one of a given potion, sends 2 rows of checkboxes to PDF
=> OS-408 Double row of Checkboxes for Potions/Oils

code/standards/checkstyle.xml
((String) foo).length() is legal
today Checkstyle wants:
((String)foo).length() is legal
Allow whitespace in array initialization:
new String[] { "Blah" };
today Checkstyle wants:
new String[] {"Blah"};
=> Allow whitespace after cast:

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_race.lst
Fixed variable name in Internal ABILITY for Dwarf darkvision
=> DATA-2604: Dwarf racial vision traits do not remove darkvision

installers/win-installer/pcgen-nsis.jelly, installers/win-installer/pcgen.nsis
@jdempsey-au & @thpr 
I left the include references in other files. This is only to remove the shortcut link from being created.
=> CODE-2868 Windows install has links to the no longer issued .bat file

.travis.yml, build.gradle
Reordered the repositories used by gradle to avoid timeouts waiting for libraries that are not held in the pcgen specific repos.
=> Fix the travis build

code/src/java/pcgen/gui2/converter/LSTConverter.java
Now that the stats etc are in the data, they need to be loaded by the converter.
=> Fix bug: CODE-2928 - CONVERTER 6.06: Cannot Parse BONUS:STAT|CAST.x|y

code/src/java/pcgen/system/Main.java
I made this change so pcgen would work with a system-wide installation on linux. See [here](https://aur.archlinux.org/packages/pcgen-git/).
=> Allow specifying config.ini directory

code/src/java/pcgen/persistence/lst/output/prereq/PrerequisiteMultWriter.java, code/src/java/plugin/pretokens/parser/PreFactParser.java, code/src/java/plugin/pretokens/parser/PreFactSetParser.java, code/src/java/plugin/pretokens/writer/PreFactSetWriter.java, code/src/test/pcgen/persistence/lst/output/prereq/PrerequisiteWriterTest.java, code/src/utest/plugin/pretokens/PreFactSetRoundRobin.java
@LegacyKing Are you happy for me to merge this? It will cause failures in the dataload tests for pathfinder as it picks up previously hidden typos.
=> CODE-2958 - Validate leys in PREFACT and PREFACTSET on data load

code/src/java/pcgen/gui2/filter/FilterBar.java, code/src/java/pcgen/gui2/sources/AdvancedSourceSelectionPanel.java
There were two ways to fix this, either collapse the game mode combo box
along with the filters, or remove the collapser.
I chose the latter since game mode selection isn't a filter it would be undesireable to hide it from the user.
=> CODE-2977 - Advanced Source selection filter collapser doesn't collapse.

build.gradle
The specified option is only valid for Java 1.8. Adding an if statement to only execute if running on Java 1.8.
=> Fix the javadoc failure during Jenkins build.

pcgen.sh
The issue here is with the way Windows/DOS systems create text files versus how Unix/Linux systems do it. Basically, "DOS uses carriage return and line feed ("\r\n") as a line ending, which Unix uses just line feed ("\n"). You need to be careful about transferring files between Windows machines and Unix machines to make sure the line endings are translated properly." (http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html).
There are a number of possible fixes, including a Perl program called dos2unix that can do the conversion. More information can be found at https://kb.iu.edu/d/acux and at the StackOverflow article I posted (http://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter).
The fact is that the Shell file is fine except that it was created or …
=> Update to pcgen.sh to fix Unix/DOS file issue

outputsheets/d20/fantasy/pdf/common_sheet/block_attack.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_bio_condensed.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_class_features.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_equipment.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_features.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_hp_defense.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_misc.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_pc_header_row.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_protection.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_psionics.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_skills.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_spells_condensed.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_spells_list.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_stat_block.xslt, outputsheets/d20/fantasy/pdf/common_sheet/block_weapons.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_no_header.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_spell_list_only.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blackandwhite.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blue.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_blue_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_companion_box_first_page.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_green_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_grey.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_grey_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_red_light.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_yellow_full.xslt, outputsheets/d20/fantasy/pdf/csheet_fantasy_std_yellow_light.xslt, outputsheets/d20/fantasy/pdf/fantasy_common.xsl, outputsheets/d20/fantasy/pdf/fantasy_master_common_blocks.xslt
This updates our default output sheets to current FOP syntax, so that they do not generate excessive warnings and can even be loaded with strict validation active.
These four syntax issues were occurring widely throughout the files:
* Empty `<fo:table-cell>` nodes are no longer allowed in FOP 1.0+. We had a lot of `<fo:table-cell/>`, or cells that can be empty if a loop or template called inside returns an empty result. I have added `<fo:block/>` to the empty cells or wrapped the loops and templates in a `<fo:block>` node.
* The `padding` attributes cannot be used with tables that use the collapsed-border table model and are ignored, but generate a warning. I have removed these attributes.
* The fixed table-layout assumes `width="auto"` when the `width` attribute is not present. However, …
=> Clean up output sheet to avoid FOP warnings

code/src/java/gmgen/plugin/Dice.java, code/src/java/gmgen/plugin/Die.java, code/src/java/gmgen/plugin/DieEx.java, code/src/java/gmgen/plugin/InfoCharacterDetails.java, code/src/java/gmgen/plugin/InitHolder.java, code/src/java/gmgen/plugin/PcgCombatant.java, code/src/java/gmgen/plugin/SystemDie.java
This fixes a slight bug in my last PR: use aModifier instead of modifier.
Also reduces the chance of this happening in the future by removing 'modifier' from the Die base class.
In the long term most of the Die class should be pulled out into System/DieEx or be replaced with composable pieces.
=> fix a slight bug in my last PR

code/src/java/pcgen/cdom/enumeration/BiographyField.java, code/src/java/pcgen/cdom/enumeration/GenericPCAttribute.java, code/src/java/pcgen/cdom/enumeration/NotePCAttribute.java, code/src/java/pcgen/cdom/enumeration/PCAttribute.java, code/src/java/pcgen/core/BioSet.java, code/src/java/pcgen/core/BonusManager.java, code/src/java/pcgen/core/PObject.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/display/SkillCostDisplay.java, code/src/java/pcgen/core/npcgen/NPCGenerator.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/gui2/facade/DescriptionFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/pcgen/persistence/lst/BioSetLoader.java, code/src/java/plugin/initiative/gui/Initiative.java, code/src/test/pcgen/core/prereq/PreBirthplaceTest.java, code/src/test/pcgen/core/prereq/PreCityTest.java, code/src/test/pcgen/io/exporttoken/TextTokenTest.java, code/src/test/plugin/exporttokens/BioTokenTest.java
Rather than keep PlayerCharacter attributes hardcoded with specific getters and setters for each, move them into appropriate enum types.
=> move attribute fields outside of PlayerCharacter

build.gradle
This reverts commit 3bc19a5cb47f68eaaebf6283a67e512202f03c81.
=> Fix Integration Tests - Revert "Simplified test dependencies"

build.gradle
This (minorly) reduces the distribution size and makes our gradle file more honest
=> make orange extensions only needed during compilation

build.gradle, code/gradle/reporting.gradle
jdepend provides nearly zero value to pcpgen. Its useful for doing certain kinds of academic analysis; however since we're still not at the point of erroring out for true bugs or serious style errors don't even bother producing jdepend reports
=> remove jdepend

build.gradle
The minimum version of the JDK we support building with is 1.8, and this
check is "wrong" for the future 1.9
=> Remove java version check from xdoclint warnings

build.gradle
Defined inputs and outputs for task. Now it verifies that:
1) The output folder is created (libs in root folder)
2) All sources are present.
Meaning that it will check if one or more of the source files are 
missing and/or the folder doesn't exist altogether before skipping.
=> Fix issue CODE-3095

data/pathfinder/paizo/player_companion/adventurers_armory/aa_equip_arms_armor.lst
Leaf Armor is not leather (but leaf), and masterwork, spell failure is
15%.
Rosewood has spikes, using the eqmod for it.
=> [Paizo][Pathfinder][Adventurer’s Armory] fix leaf and rosewood armors

code/pcgen.sh
The current command line script `pcgen.sh` fails to handle arguments that include spaces or other special characters properly.  For example, trying the command
```
pcgen.sh -- -v -m "Pathfinder RPG for Players - Advanced"
```
as the help suggests will result in an error message about the argument _RPG_ being unknown.
The issue here is the shuffling of the command line arguments into a new variable, _pcgenargs_, which is later expanded without any protection.  Even if the arguments are properly protected when calling the script, this protection is lost in this shuffling.
My suggested fix is to simply stop argument processing when the “--” divider is reached, and then use the `"$@"` syntax at the end, which will do proper quoting.
A minor change in behaviour by this change is that the `-h` …
=> Improve handling of arguments with spaces or other special characters.

code/src/java/pcgen/io/freemarker/EquipSetLoopDirective.java
Changing the CalcEquipSetId does not change data to be output.
Need to set the CalcEquipmentList after the id change to get the
equipment data to change.
=> [CODE-3102] Multiple equipmentset export (Freemarker) fix.

code/pcgen.sh
- use quotes where its supposed to exist
- stop passing BROWSER; the application should handle this anyways.
- include a "--" after java to handle passing arguments
- move to top of git repo during development
=> A variety of pcgen.sh improvements

preview/d20/5e/Standard.htm.ftl
I don't see a simple and easy to reference Proficiency Bonus and Hit Dice shown on the preview. So I replaced the Misc Table and the Base Attack Bonus.
=> Preview Proficiency and Hit Dice

code/src/java/pcgen/gui2/tools/SpinningTabbedPane.java
=> Fix regression in SpinningTabbedPane.getMovableTabIndices() introduced

docs/faqpages/faqotherissues.html, docs/faqpages/faqoutofmemoryandjavaissues.html, docs/faqpages/faqprintingissues.html, docs/freemarkeroutputpages/pcgenfunctions.html, docs/listfilepages/globalfilestagpages/globalfilesformulas.html, docs/listfilepages/globalfilestagpages/globalfilestype.html, docs/listfilepages/listfileLSTstandards.html, docs/listfilepages/listfileLSTwalkthrough.html, docs/listfilepages/listfileimportanttoknow.html, docs/listfilepages/lstfileclass/lfc_lesson13_feat2.html, docs/listfilepages/lstfileclass/lfc_lesson14_deities.html, docs/listfilepages/lstfileclass/lfc_lesson15_domains1.html, docs/listfilepages/rulesguide/game_rules_implement_heading.html, docs/listfilepages/systemfilestagpages/gamemodeloadlist.html, docs/listfilepages/systemfilestagpages/gamemodemigrationlist.html, docs/listfilepages/systemfilestagpages/gamemodemiscinfolist.html, docs/menupages/edit/editaddkitoptions.html, docs/menupages/file/filesectionheading.html, docs/menupages/tools/preferences/preferencespcgenoptions.html, docs/menupages/tools/preferences/preferencessectionheading.html, docs/tabpages/tabdescription.html, docs/tabpages/tabfeatsandabilities.html, docs/tabpages/tabinventory.html, docs/tabpages/tabsectionheading.html, docs/tabpages/tabspells.html, docs/tabpages/tabtemporarybonuses.html, docs/walkthroughpages/walkthroughcreatecharacter.html
While reading through the documentation, I stumbled on a number of minor editorial mistakes for which I submit fixes here.
In addition, I removed the section on running on Fedora.  Fedora 7 is very out of date, and on current Fedoras (24 and 25) PCGen works just fine with the standard Java (OpenJDK 1.8.0).
=> Fix minor language mistakes in the documentation.

data/35e/wizards_of_the_coast/unearthed_arcana/ua_classes.lst
half-orc paragon class requisite refers to halfling race wrongly.
=> half-orc paragon prerequisite wrong

outputsheets/d20/fantasy/htmlxml/csheet_fantasy_statblock_pathfinder.htm.ftl, preview/d20/fantasy/common/common-pathfinder.ftl
This allows statblock to be used to copy/paste into MapTool scripts. Copy/paste from paizo.com's PRD works since it does not use nbsp. MapTool borks on nbsp characters.
=> Remove nbsp's

.appveyor.yml
This will help contributors without native access to windows ensure
their changes don't fail due to Windows specific things.
This incidentally also finds real data issues in other campaigns.
=> Add appveyor.yml for building on windows

.travis.yml
This reduces the chance for random failure due to network flakiness.
=> Add caching for Gradle deps

build.gradle, code/pcgen.sh
Gradle and windows do not seem to play nice with each other in ways I
don't fully understand.
This moves pcgen into a dedicated output directory instead as this is
better practice in the first place. We may need some slight changes to
other release scripts but that will happen in due course
=> Move gradle output into a dedicated directory.

build.gradle
All the places that require it, already explicitly use clean. Clean
slows down builds, and it isn't usually required except in CI builds.
=> [gradle] Remove clean from default build

code/src/java/gmgen/gui/ImagePreview.java, code/src/java/pcgen/cdom/base/Constants.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/InfoGuidePane.java, code/src/java/pcgen/gui2/SplashScreen.java, code/src/java/pcgen/gui2/UIPropertyContext.java, code/src/java/pcgen/gui2/dialog/CharacterHPDialog.java, code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java, code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java, code/src/java/pcgen/gui2/tabs/DomainInfoTab.java, code/src/java/pcgen/gui2/tabs/SkillInfoTab.java, code/src/java/pcgen/gui2/tabs/ability/CategoryTableModel.java, code/src/java/pcgen/gui2/tabs/bio/ImagePreviewer.java, code/src/java/pcgen/gui2/tabs/bio/PortraitPane.java, code/src/java/pcgen/gui2/tabs/equip/EquipmentModel.java, code/src/java/pcgen/gui2/tabs/equip/EquipmentModels.java, code/src/java/pcgen/gui2/tabs/skill/SkillPointTableModel.java, code/src/java/pcgen/gui2/tabs/summary/ClassLevelTableModel.java, code/src/java/pcgen/gui2/tabs/summary/LanguageTableModel.java, code/src/java/pcgen/gui2/tabs/summary/StatTableModel.java, code/src/java/pcgen/gui2/util/JTreeTable.java, code/src/java/pcgen/gui2/util/SimpleTextIcon.java, code/src/java/pcgen/gui2/util/table/TableUtils.java, code/src/java/plugin/notes/gui/NotesView.java
This PR attempts to fix all hardcoded row heights for JTables and JTreeTables and replaces hardcoded black text color with SystemColor.text color.
See issue https://github.com/PCGen/pcgen/issues/1760
=> Fixing hardcoded row height(to FontMetrics.getHeight()) and hardcoded black text color(to SystemColor.text)

code/src/java/pcgen/system/Main.java
We already require bytecode of version 1.8 or later, so earlier versions of Java can't run.
Newer versions that don't work should be reported as bugs.
Just remove the entire env check.
=> CODE-3070 Remove Java version check

code/src/java/pcgen/gui2/PCGenUIManager.java
I'm going to try and get this to work, but work around the issue for now
=> [CODE-3070] Don't start macOS GUI if we're on Java 9 since it doesn't work

code/src/java/gmgen/GMGenSystem.java
While this should happen in the OSX adapter, there is some brokenness
around this code. In addition this feature is likely not to continue
existing in Java 9.
=> CODE-2017: Don't hide edit menu on mac

code/src/java/pcgen/core/Globals.java
Convert the list of allowable resizable types (found in miscinfo.lst) to uppercase so the compare against the piece of equipment's modifiers works.
miscinfo.lst for some of the systems may need to be updated.
=> Address CODE-3120 -- Fix equipment auto resize

code/src/java/plugin/qualifier/weaponprof/EquipmentToken.java, code/src/java/plugin/qualifier/weaponprof/SpellCasterToken.java
As far as I could tell this isn't used by anything, including the
installer on windows.
=> Remove sbin directory

build.gradle
One should not need a full deployment machine in order to run tests
before a code commit
=> Remove (false) Nsis dependency from itest

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_templates.lst
Androids in Pathfinder have no bonus languages
=> Fix bug: DATA-3370

data/pathfinder/paizo/roleplaying_game/occult_adventures/_occult_adventures.pcc
Monster Codex not created causing a missing dependencies issue in Occult Adventures.
=> Fix bug: DATA-3426

data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_feats.lst
Threatening Defender trait doesn't apply when using Stalwart w/ Combat Expertise
=> Fix bug: DATA-3403

code/src/java/pcgen/persistence/lst/LstObjectFileLoader.java
Fix for issue #3369, CODE-3204.
Problem was caused by all non CLASS:/comment lines following a CLASS .MOD being picked up as part of the MOD.
Easy fix, ignore line consisting of just white space characters before any processing is done on them. There was already some code for this introduced to fix a similar problem in commit 7e0ccf5de131fa8090b3a3a7f8f515b51969a3aa but it was after the MOD handling code for some reason.
=> [CODE-3204] Fix handling of whitespace lines in class lst files.

code/src/java/pcgen/core/BioSet.java
Fix by removing unneccessary & unchecked call to genderTok.nextToken()
=> Fix #3453: Pathfinder: choose 'Aasimars' race got exception

build.gradle
- basic Java 9 support
- newer xstream dep
- 64bit linux binaries
- minor bug fixes
=> Bump launch4j to latest (2.4.1)

code/src/java/pcgen/core/BioSet.java
This addresses an issue where races without Height and Weight information for certain agesets would fail to load properly.
This is due to the fact that the data for that ageset would be stored as "0" by BioSetLoader, but BioSet only checked for "null".
Addresses:
https://pcgenorg.atlassian.net/browse/DATA-3455
https://pcgenorg.atlassian.net/browse/DATA-3461
=> Handle agesets without Height and Weight information [DATA-3455]

preview/d20/fantasy/Fantasy_Character_Sheet.html
Adjusted the html file to correct an issue with the Armor & Shield fields when having only one of them equipped.
https://i.imgur.com/Id2M7p9.png
The change made will fix the issue seen in the linked image.
The current code makes the armor and shield properties hard to read due to a repeating image that should be a solid background instead.
This "fix" corrects the repeated bad image and adjusts the code to show the proper background image.
=> Fix for the Fantasy Character Sheet preview for 3.5e

data/pathfinder/paizo/roleplaying_game/ultimate_magic/_ultimate_magic.pcc, data/pathfinder/paizo/roleplaying_game/ultimate_magic/support/um_abilities_class_acg.lst, data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_class.lst
Fixes the missing ability error that pops up when loading Ultimate Magic without Advanced Class Guide.
=> Ultimate Magic Shaman familiars mod load fix

code/src/java/pcgen/core/VariableProcessor.java, code/src/java/pcgen/system/CharacterManager.java
VariableProcessor caching produces unreliable results because sometimes it will try to cache a variable used in a PREREQ that hasn't had all relevant BONUS values loaded.  It's better to rely on the caching in BonusManager.
=> NEWTAG-597 - turning off VariableProcessor caching

code/src/java/pcgen/core/prereq/PrerequisiteUtilities.java
This resolves the PREABILITY issue because the sub-key (choice) didn't match exactly since the choice was from a category internal list.  In this case it should match the choice to the item that ends with a pipe in front of the name of the item we're matching.
=> CODE-3222 - sub choices might match the prereq with a delimiter

data/pathfinder/paizo/player_companion/people_of_the_stars/_people_of_the_stars.pcc, data/pathfinder/paizo/player_companion/people_of_the_stars/pots_abilities_class.lst
Fixed Draconic Bloodline choices granted by Outer Dragon Blood trait and a missed eqmod change.
=> POTS - Ability and Equipment Fixes

code/pluginbuild.xml, code/src/java/plugin/lsttokens/datacontrol/DefaultVariableValueToken.java, code/src/java/plugin/modifier/dice/SetModifierFactory.java
Improves error messaging and also adds the SET Modifier for DICE. This is needed for DEFAULTVARIABLEVALUE to be able to function.
=> NEWTAG-597 Add SET for Dice Format

code/src/java/plugin/lsttokens/ModifyOtherLst.java
Note:
This structure of having inline classes like this is a bit of a hack to demonstrate the process works, but we still need it to work.  Longer term, there are ways to make this more sensible in how groupings are formed
=> CODE-3225 Fix MODIFYOTHER so that it correctly filters for object type

code/src/java/pcgen/gui2/solverview/SolverViewFrame.java
Fixes a problem in the Solver UI where it will dump stack if selections are not fully initialized (almost inevitable)
=> Bug Fix CODE-3030

data/pathfinder/paizo/player_companion/adventurers_armory/aa_equip.lst
renamed items to be consistent with other sources and avoid redundant entries of the same item but with slightly different names
=> renamed items to avoid duplicate listings

code/src/java/pcgen/cdom/enumeration/SkillArmorCheck.java, code/src/java/pcgen/cdom/helper/CNAbilitySelection.java, code/src/java/pcgen/cdom/helper/SpellLevel.java, code/src/java/pcgen/core/term/EQACCheckTermEvaluator.java, code/src/java/pcgen/core/term/EQCritMultTermEvaluator.java, code/src/java/pcgen/core/term/EQRangeTermEvaluator.java, code/src/java/pcgen/core/term/PCACcheckTermEvaluator.java, code/src/java/pcgen/core/term/PCArmourACcheckTermEvaluator.java, code/src/java/pcgen/core/term/PCHandsTermEvaluator.java, code/src/java/pcgen/core/term/PCLegsTermEvaluator.java, code/src/java/pcgen/core/term/PCProfACCheckTermEvaluator.java, code/src/java/pcgen/core/term/PCShieldACcheckTermEvaluator.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/plugin/lsttokens/NaturalattacksLst.java, code/src/java/plugin/lsttokens/add/AbilityToken.java, code/src/java/plugin/lsttokens/choose/SpellLevelToken.java, code/src/java/plugin/lsttokens/deprecated/RemoveFeatToken.java, code/src/java/plugin/lsttokens/deprecated/TemplateFeatToken.java, code/src/java/plugin/lsttokens/equipment/RangeToken.java
Background: Globals.getContext() is generally bad behavior, as it's a loader function, and really should be avoided at runtime.  While we have many uses of it, we want to reduce those over time, especially those in code we know to be strategic.  This is another pass at reducing the calls to Globals.getContext() and replacing it with alternative methods of accessing the context or go get the required information directly from another object.
=> Reduce use of Globals.getContext()

code/src/java/pcgen/cdom/format/table/TableFormatFactory.java, code/src/java/pcgen/cdom/format/table/TableFormatManager.java, code/src/java/plugin/function/LookupFunction.java, code/src/utest/plugin/function/LookupFunctionTest.java
Replaces PR#3672
This reduces the TABLE[...] format syntax to only have one sub-argument. Previously, it had both the lookup and result columns. This now seems unnecessary. The result column format is already provided in the COLUMN[...] format of the column used in lookup(...), so this is redundant information that is, at best, error catching.
At worst, it is much more confusing since a table with 3 columns, NUMBER, STRING, and NUMBER, must be referred to as two different formats if the target column type is included in the TABLE format. That confusion is unnecessary, as the information is available elsewhere, and there is no added value from providing the redundant format information.
=> NEWTAG-615 Reduce Table Format to only the lookup column

data/pathfinder/paizo/player_companion/elemental_masters_handbook/_elemental_masters_handbook.pcc
Removed FORWARDREF; it's not needed for PREABILITY. Wild Talent ~ Void Healer does not yet exist in any source, and as such was causing an unconstructed reference error even in only for FORWARDREF.
=> EMH - Load Error Corrections

data/pathfinder/paizo/player_companion/legacy_of_dragons/_legacy_of_dragons.pcc
Fixed FORWARDREF; Monk ~ Unchained Class is CATEGORY=CLASS, not an actual class.
=> LOD - Load Error Corrections

data/pathfinder/paizo/adventure_path/curse_of_the_crimson_throne/ap11/ap11.pcc, data/pathfinder/paizo/adventure_path/curse_of_the_crimson_throne/ap8/ap8_kits.lst, data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_equip_general.lst
Removed bad FOREWARDREF; I can't figure out what it's supposed to be forwarding. Source loads fine without it.
Changed ability reference in kit to match others. It's still wrong, but it needs the ability chooser reference fix, and this way it doesn't cause loading errors. I'm not sure where it was changed earlier that I'm only now noticing it.
Fixed a capitalization error that was causing a mismatch error on load.
=> Load Error Corrections

code/src/itest/plugin/lsttokens/editcontext/race/FaceIntegrationTest.java, code/src/itest/plugin/lsttokens/editcontext/template/FaceIntegrationTest.java, code/src/java/pcgen/rules/context/LoadContext.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/plugin/lsttokens/InfoVarsLst.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/java/plugin/lsttokens/race/FaceToken.java, code/src/java/plugin/lsttokens/template/FaceToken.java, code/src/java/plugin/lsttokens/variable/ChannelToken.java, code/src/java/plugin/lsttokens/variable/GlobalToken.java, code/src/test/pcgen/core/PObjectTest.java, code/src/utest/plugin/lsttokens/ModifyLstTest.java, code/src/utest/plugin/lsttokens/ModifyOtherLstTest.java, code/src/utest/plugin/lsttokens/race/FaceTokenTest.java, code/src/utest/plugin/lsttokens/template/FaceTokenTest.java
This reduces the necessary information in LoadContext to get a LegalScope (the embedded Dummy ScopeInstance is not necessary now that the formula system can run processing for Dependencies without needing a scope instance
=> Simplify how LoadContext works to avoid a dummy object. 

code/src/java/pcgen/cdom/facet/StatValueFacet.java
This changes the internal behavior of StatValueFacet.  Previously, if the stat channel was set the new formula system could access the stat value, but other items (using the old system) would fail.  Due to the extensive presence if stats and their impact across an entire PC, that either/or scenario is untenable.
This changes how stat values are read through the entire program, ensuring that they are either using the new or old system - but allows all of the surrounding code to continue to use this facet (for now ;) )
=> Ensure Stat values behave correctly with old and new system concurrently

code/src/java/pcgen/cdom/base/GroupableFormatManager.java, code/src/java/pcgen/cdom/base/ObjectManager.java, code/src/java/pcgen/cdom/reference/AbstractReferenceManufacturer.java, code/src/java/pcgen/cdom/reference/ReferenceManufacturer.java, code/src/java/pcgen/rules/context/AbstractReferenceContext.java, code/src/java/pcgen/rules/context/ReferenceContextUtilities.java, code/src/java/pcgen/rules/context/TrackingManufacturer.java
Effectively this introduces a new (slightly more powerful) FormatManager
derivative called an ObjectManager, and then uses that for
ReferenceManufacturer objects.  This additional capability will be
expanded and leveraged for a number of items in the formula system going
forward.
Also removes one (confusing and likely buggy) unused method
=> Change minor method semantics on Reference Manufacturer

code/src/java/pcgen/rules/persistence/token/AbstractSimpleChooseToken.java, code/src/java/pcgen/rules/persistence/token/AbstractToken.java, code/src/java/plugin/converter/FavClassConvertPlugin.java, code/src/java/plugin/lsttokens/NaturalattacksLst.java, code/src/java/plugin/lsttokens/SpellknownLst.java, code/src/java/plugin/lsttokens/SpelllevelLst.java, code/src/java/plugin/lsttokens/TemplateLst.java, code/src/java/plugin/lsttokens/TypeLst.java, code/src/java/plugin/lsttokens/ability/BenefitToken.java, code/src/java/plugin/lsttokens/add/AbilityToken.java, code/src/java/plugin/lsttokens/add/SkillToken.java, code/src/java/plugin/lsttokens/add/SpellCasterToken.java, code/src/java/plugin/lsttokens/campaign/ForwardRefToken.java, code/src/java/plugin/lsttokens/deprecated/RemoveFeatToken.java, code/src/java/plugin/lsttokens/equipment/AlttypeToken.java, code/src/java/plugin/lsttokens/kit/ability/AbilityToken.java, code/src/java/plugin/lsttokens/kit/table/ValuesToken.java
For items that are trying to shortcut a good report on the location of
an error, this will help reduce that problem.  It forces a slightly more
verbose syntax in a few places, but in general helps standardize
behavior and improve error reporting.
=> Pushes ParseResult deeper into the processing for certain tokens.

code/pluginbuild.xml, code/src/java/pcgen/cdom/base/CDOMObject.java, code/src/java/pcgen/cdom/base/ConcretePrereqObject.java, code/src/java/pcgen/cdom/base/PrereqObject.java, code/src/java/pcgen/cdom/enumeration/ListKey.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/EquipmentList.java, code/src/java/pcgen/core/EquipmentModifier.java, code/src/java/pcgen/core/Kit.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/analysis/BonusCalc.java, code/src/java/pcgen/core/analysis/DomainApplication.java, code/src/java/pcgen/core/analysis/SpellLevel.java, code/src/java/pcgen/core/analysis/SubClassApplication.java, code/src/java/pcgen/core/analysis/SubstitutionClassApplication.java, code/src/java/pcgen/core/character/WieldCategory.java, code/src/java/pcgen/core/kit/KitClass.java, code/src/java/pcgen/core/npcgen/ClassDataParser.java, code/src/java/pcgen/core/prereq/PrereqHandler.java, code/src/java/pcgen/core/prereq/PrerequisiteUtilities.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/gui2/facade/TempBonusHelper.java, code/src/java/pcgen/rules/context/LoadContext.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/java/plugin/lsttokens/AllowLst.java, code/src/java/plugin/lsttokens/EnableLst.java, code/src/java/plugin/lsttokens/PrerequisiteLst.java, code/src/java/plugin/lsttokens/RequirementLst.java, code/src/java/plugin/primitive/domain/DeityToken.java
Includes framework (token at this point) for ENABLE, but the ENABLE token is guaranteed to fail at LST load.
This is the first in a series of items that provides for interaction of the new formula system to data control of allowed/granted. This implements (a beta version as it is subject to negotiation with the data team) of ALLOW:
This should enable certain items (e.g. VISION) to be fully converted to Dynamic/Formula items.
Note there are certain deficiencies with this system as it is currently designed. The following features still work with PRExxx, but this new token will not:
Build Ability Prerequisites for the Prerequisite Tree view for the UI
Display in the UI of what the ALLOWsituation is (in the HTML description of an object)
In addition, there is some existing items where I think …
=> NEWTAG-617 First ALLOW Implementation

data/pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_companionmods.lst, data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_companionmods.lst
Per Ultimate Wilderness, cavalier and samurai mounts may use light armor proficiency in place of share spells to qualify for archetypes
=> Mount_Support_for_Companion_Archetypes

.gitignore
Ths existing incarnation uses simple words for some very specific
folders, and these pattern matches accidentally impact portions of the
code base, meaning there are places where files can be added but they
will not be detected by git as significant... that's obviously a major
problem, so the .gitignore file needs to be more specific of what it is
ignoring.
=> This fixes a problem with .gitignore

code/src/java/pcgen/cdom/reference/AbstractReferenceManufacturer.java, code/src/java/pcgen/cdom/reference/ReferenceManufacturer.java, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/cdom/util/SortKeyComparator.java, code/src/java/pcgen/cdom/util/SortKeyed.java, code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/core/PaperInfo.java, code/src/java/pcgen/rules/context/AbstractReferenceContext.java, code/src/java/pcgen/rules/context/TrackingManufacturer.java, code/src/java/plugin/lsttokens/paper/SortKeyToken.java
This implements the change "allowed" as of 6.06 release, which is to drop out of injection order to use SORTKEY for PaperInfo.
As a result, the entire context system is simplified, dropping entirely the getItemInOrder method.
=> CODE-3037 Fix: PaperInfo problem

code/pluginbuild.xml, code/src/java/pcgen/cdom/content/RollMethod.java, code/src/java/plugin/lsttokens/gamemode/rollmethod/SortKeyToken.java
This forces all RollMethod objects to have a SORTKEY.
This will be the last class that is sorted internally to PCGen but does not have SORTKEY. With this completed, all of the existing "assumes things are sorted by how they appear first" will be deprecated and removable from PCGen.
This is proposed to be a non-graceful change (meaning it will complain immediately, not provide a transition between versions) as this is a game mode level item and therefore very isolated.  It will also not be catastrophic with this PR if SORTKEY doesn't exist... (the order won't actually change in the UI based on this at this time - it will occur later after the older methods are removed a few PRs from now)
=> NEWTAG-619 Add SORTKEY for RollMethod objects

code/src/java/pcgen/cdom/facet/ScopeFacet.java, code/src/java/pcgen/cdom/formula/scope/GlobalScope.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/context/VariableContext.java, code/src/java/plugin/function/DropIntoContext.java, code/src/java/plugin/function/GetFactFunction.java, code/src/java/plugin/lsttokens/variable/ChannelToken.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/function/AbstractFormulaTestCase.java, code/src/utest/plugin/function/DropIntoContextFunctionTest.java, code/src/utest/plugin/function/GetFactFunctionTest.java, code/src/utest/plugin/function/InputFunctionTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java, code/src/utest/plugin/modifier/number/SetNumberModifierTest.java
This is cleanup work that separates the concepts of FORMAT and SCOPE.
This is necessary to have certain later behaviors work correctly, as
well as to generally avoid confusion (and bugs) later on. This supports,
but is not exclusively preparation for, Library version 147. (Meaning if
147 never happens or the relevant changes are backed out, this is still
a good commit and shouldn't be removed)
In particular, this (1) Shares the Global Scope name through a constant
(2) clearly drives getFact and dropIntoContext to have their first
argument as a FORMAT (3) Changes some tests to use SKILL rather than
EQUIPMENT since EQUIPMENT can't be used as a FORMAT at this time
To consider why getFact and dropIntoContext use FORMAT, consider
something like getFact("EQUIPMENT.PART","xx","FactName"). Right …
=> FORMAT and SCOPE separation

build.gradle, code/src/java/pcgen/cdom/content/VarModifier.java, code/src/java/pcgen/cdom/facet/SolverManagerFacet.java, code/src/java/pcgen/cdom/formula/scope/EquipmentPartScope.java, code/src/java/pcgen/cdom/formula/scope/GlobalScope.java, code/src/java/pcgen/cdom/inst/Dynamic.java, code/src/java/pcgen/cdom/inst/EquipmentHead.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/EquipmentModifier.java, code/src/java/pcgen/core/PCCheck.java, code/src/java/pcgen/core/PCStat.java, code/src/java/pcgen/core/SizeAdjustment.java, code/src/java/pcgen/core/Skill.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/plugin/function/DropIntoContextFunctionTest.java, code/src/utest/plugin/function/GetFactFunctionTest.java, code/src/utest/plugin/lsttokens/ModifyOtherLstTest.java, code/src/utest/plugin/lsttokens/variable/LocalTokenTest.java
The major change here is that local scopes are now PC.x (this impacts
what appears on MODIFYOTHER as the first argument)
The primary reason for this change is to isolate the PC as a formula scope.  Basically, there are places where we need to do calculations independent of a PC (Equipment and Spells both come to mind), so this will ease that isolation.
=>  Update for Formula Library version 149

.gitattributes
On Mac, `gradlew.bat` was always unstaged with line endings changed. This prevented me from pulling or pushing anything. Add `gradlew.bat` to `.gitattributes` to fix this.
=> Do not normalize gradlew.bat eol

data/pathfinder/paizo/roleplaying_game/bestiary_4/_bestiary4.pcc
Kitsune PC race overridden by Kitsune monster race when both ARG and Bestiary 4 are loaded
=> Fix bug: DATA-3565

data/pathfinder/paizo/player_companion/heroes_of_the_wild/hotw_equip_general.lst
http://archivesofnethys.com/PoisonDisplay.aspx?ItemName=Blistercap%20spore%20poison
=> renamed poison to correct spelling

code/src/java/pcgen/rules/persistence/TokenUtilities.java, code/src/java/plugin/lsttokens/spell/TargetareaToken.java, code/src/utest/plugin/lsttokens/AddTokenTest.java, code/src/utest/plugin/lsttokens/PreTokenTest.java, code/src/utest/plugin/lsttokens/testsupport/AbstractGlobalTokenTestCase.java, code/src/utest/plugin/lsttokens/testsupport/AbstractTokenTestCase.java
Unfortunately, the way we break up LST files uses StringTokenizer, which doesn't create new Strings.  Therefore, one accidental move by a token can ingest the full file stored on disk into memory - "permanently".  These additional tests (and one fix in TokenUtilities) are designed to detect that accidental capture (at least in some circumstances) to reduce the probability of it occurring.
Note this does rely on certain behavior by System.gc() that is not guaranteed, but we have nothing better in Java.
=> Add tests to ensure tokens don't accidentally capture the full file

code/src/java/pcgen/cdom/content/AbilitySelection.java, code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/core/term/PCCountAbilitiesTypeNatureVirtualTermEvaluator.java, code/src/java/pcgen/persistence/lst/FeatLoader.java, code/src/java/plugin/lsttokens/kit/spells/SpellsToken.java
In non-deprecated places where LoadContext is already available, use it
to indirectly look up the FEAT AbilityCategory.
Fixes one item in a term as well where the AbilityCategory is available
and it was incorrectly hardcoded to FEAT.
=> Reduce usage of hard-coded AbilityCategory.FEAT

code/src/java/pcgen/gui2/tabs/RaceInfoTab.java
This makes the UI self-consistent in what is selected vs what is shown in the info pane, across different characters and selections
=> This fixes a display behavior

code/src/itest/tokencontent/testsupport/AbstractContentTokenTest.java, code/src/itest/tokenmodel/testsupport/AbstractGrantedListTokenTest.java, code/src/itest/tokenmodel/testsupport/AbstractTokenModelTest.java, code/src/java/pcgen/cdom/base/CDOMObject.java, code/src/java/pcgen/cdom/base/VarContainer.java, code/src/java/pcgen/cdom/base/VarHolder.java, code/src/java/pcgen/cdom/content/RemoteModifier.java, code/src/java/pcgen/cdom/content/VarModifier.java, code/src/java/pcgen/cdom/facet/GrantedVarFacet.java, code/src/java/pcgen/cdom/inst/GlobalModifiers.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/EquipmentModifier.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/rules/context/LoadContext.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/persistence/TokenLibrary.java, code/src/java/pcgen/rules/persistence/TokenSupport.java, code/src/java/pcgen/rules/persistence/token/CDOMInterfaceToken.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/utest/plugin/lsttokens/ModifyLstTest.java, code/src/utest/plugin/lsttokens/ModifyOtherLstTest.java
Leverages the Proxy system from -base
This system allows a load token to use an interface rather than the
object class (or ancestor class).  This allows multiple different,
otherwise unrelated objects to use the same load token.
This sets up for allowing Dynamic (which is not - and shouldn't be - a
CDOMObject) to handle variables.
This sets up a simplification of GlobalModifiers as well.
Overall, this also sets up the ability to do a simplification of the
token system - allowing them to ignore the context in many cases and act
directly on an interface (thus making the code clearer)
=> Interface Tokens

code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/formula/scope/EquipmentPartScope.java, code/src/java/pcgen/cdom/inst/EquipmentHead.java, code/src/java/pcgen/core/EquipmentModifier.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/plugin/lsttokens/equipment/PartToken.java
Two changes: Extracts the frequent use of constants to one location
Corrects the PartToken of Equipment to use the "PC." prefix (side
effect)
=> Correct Equipment Part Scoping

build.gradle, code/gradle/reporting.gradle
Gradle 4.4.1 had an issue (gradle/gradle#3908) where the toolVersion settings for code quality plugins could be ignored. I suspect in order to get the reports to work someone placed them near the beginning of build.gradle as well as leaving the values in code/gradle/reporting.gradle. The issue was resolved in gradle 4.6 so now you have moved to that version the recent changes to toolVersion in build.gradle are being overridden by the old values still present in reporting.gradle. So to avoid confusion this change reverts to the old setup  where you only set the toolVersion in one location (reporting.gradle).
=> Set toolVersion for pmd and checkstyle in one place.

code/pcgen.sh
- We already cd to correct directory at the top of the file. This one is
extraneous and has incorrect quoting
- remove broken '2> /dev/null' in conditional
- add quotes
=> CODE-3257: fix pcgen.sh a bit

build.gradle
, update to '1.6.2'
JDK9 is end of life. Building with gradle and Java10 had issues with spotbug version 1.6.1
Also adjusted toolVersion from 3.1.2 to 3.1.3 in two places as this seems to be current version.
Build with ./gradlew fullZip produced usable build.
=> gradlew with JDK10 has issues with spotbug version '1.6.1'

code/src/java/pcgen/core/analysis/SpellLevel.java
This is a proposed fix to the abovementioned JIRA issue. It appears that sometimes the spell level list in question is not sorted. 
I'd like review from those more familiar with this class to ensure the assumption that the spell list is sorted is not relied upon elsewhere, which would indicate the bug comes from a different source.
=> Fix bug: CODE-3259

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities.lst
Mobility bonus not appearing in character sheet
=> Fix bug: DATA-3684

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items.lst
[Pathfinder] Duelist's Vambraces applying benefit to all attacks with off hand
=> Fix bug: DATA-3701

code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui2/plaf/MacGUIHandler.java
MacGUIHandler was no longer usable with Java 9, but was skipped for exactly Java version 9 only. Rewrote MacGUIHandler class to work with Java 9+, so it can be used again.
=> CODE-3274: Fix the MacGUIHandler to run with Java 9+

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_templates.lst
https://pcgenorg.atlassian.net/browse/DATA-3718
Pathfinder Energy Drain not applying penalty to level dependent spell effects
=> Fixbug: DATA-3718

build.gradle
Originally removed by PR #4220 but then put back by PR #4108.
Maybe using the "Rebase and merge" option for the "Merge pull request" would of caught it. May have also removed the need for PR #4247 because PR #4015 undid PR #4043.
=> Remove gradle lint again.

code/src/java/pcgen/gui2/tools/Utility.java
A block of code once used to set the application title on X11 systems is obsolete and causes a "Illegal reflective access" warning on JDK 9+ and is likely to fail in upcoming Java releases. The code also serves no purpose, and so I have removed it.
=> Fix Introspection depreciation with Java 10+ by removing some obsolete code

build.gradle
Currently building PCGen from the command line with gradle does not create an environment where PCGen can easily be stared without having to copy some files after every build (also the pcgen.sh script is broken inside a development environment – see PR #4316). I have created a new task "installToRoot" that builds the executables and copies them to the root directory so PCGen can be started by running the pcgen.sh or pcgen.bat script without needing any further operations after each build.
=> Add a gradle task to create a development environment where you can easily run PCGen from the command line

code/pcgen.sh
Currently the shell script pcgen.sh tests if it is started from inside a git repository environment. If so, it changes directory to the output directory where the build process creates the shell file and the jars. However there is no access to the libraries directory from there, and PCGen fails to run. removing this code allows the script to run from inside a git repository environment as well as when run from a normal installation or an extracted zip archive .
=> Fix pcgen.sh so it works inside a git environment

code/src/java/pcgen/core/Equipment.java, code/src/test/pcgen/core/EquipmentTest.java
The issue seems to be that previously unused `EquipmentMods` don't get included in the scope tree when they are added to a piece of `Equipment`. 
`EquipmentMod`s are added to `Equipment`s in different ways:
* Via `#addToEqModifierList`, which sets the `variableParent` of the `EquipmentModifier` (thus adding it to the scope tree)
* Via `#load`, which transitively calls the private `#addEqModifier`, which makes use of `#addToEqModifierList` above
* Via the package-private `#addEqModifier`, which does *not* use `#addToEqModifierList` and does not set the `variableParent`.
The equipment editor in the inventory/purchase tab makes use of the latter option, which can lead to a case where the character has a piece of equipment with a modifier, but it's not possible to look upwards from the …
=> CODE-3287: Custom magic weapons break the OS

code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java
Necessary because logical items like || trigger a false positive
Note: If a var is a boolean and the formula is A || B that will fail.
It will need to be written as (A || B) ... with the parenthesis
In that way, ParsingSeparator will detect the || as logical OR
=> CODE-3293 Don't enforce traditional separators on MODIFY

code/src/java/pcgen/cdom/content/fact/FactGroupDefinition.java, code/src/java/pcgen/cdom/content/fact/FactGrouping.java, code/src/java/pcgen/cdom/grouping/GroupingDefinition.java, code/src/java/pcgen/cdom/grouping/GroupingInfo.java, code/src/java/pcgen/cdom/grouping/GroupingInfoFactory.java, code/src/java/pcgen/cdom/grouping/GroupingScopeFilter.java, code/src/java/pcgen/rules/context/AbstractReferenceContext.java, code/src/java/pcgen/rules/context/GameReferenceContext.java, code/src/java/pcgen/rules/context/LoadContext.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/pcgen/rules/context/RuntimeReferenceContext.java, code/src/java/pcgen/rules/persistence/ChoiceSetLoadUtilities.java, code/src/java/pcgen/rules/persistence/TokenLibrary.java, code/src/java/plugin/grouping/AllGroupingToken.java, code/src/java/plugin/grouping/GroupGroupingToken.java, code/src/java/plugin/grouping/KeyGroupingToken.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java
Fixes an issue Andrew found in the new formula system
Stabilizes how certain objects work, allows many formats more easily
Grouping doesn't need to be Loadable
Include ARRAY[] format
=> Fix how FormatManager is established for variables

code/pluginbuild.xml, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java, code/src/utest/plugin/lsttokens/ModifyLstTest.java, code/src/utest/plugin/lsttokens/ModifyOtherLstTest.java
This prepares for other tokens that will want to process the same 3+association set of information, such as TEMPMODIFY
=> Centralize MODIFY processing behavior

code/src/utest/plugin/lsttokens/testsupport/AbstractTokenTestCase.java
These two tests take the running time of tests on my computer 5m18s to
about 12m.
In addition the tests don't quite work as expected. Java implementations
don't have do anything on a gc, and WeakReference isn't guaranteed to be
null even post gc.
=> [tests] halve the time it takes to run unit tests

code/src/utest/plugin/lsttokens/testsupport/AbstractGlobalTokenTestCase.java
Like #4450, remove the WeakReference test for gc isn't quite correct and
slows down the test significantly.
=> [test] speed up and modernize AbstractGlobalTokenTestCase.

build.gradle
New Gradle versions issue warnings if configuration is read at a "bad"
time. Reorganize in accordance with modern docs in order to avoid this
warning.
Further, teach IntelliJ that "slowtest" is a test directory.
=> [build] avoid configuration leakage in build

code/src/java/pcgen/core/RuleConstants.java, code/src/test/pcgen/io/exporttoken/WeaponTokenTest.java
While an interface for a holder isn't inherently a problem, it leads to
confusion and encourages users to _implement_ the iface rather than
statically access the values.  Change RuleConstants to a class.
=> RuleConstants: make a class

code/src/itest/pcgen/io/JarTest.java
This is currently preventing "build" from completing properly because build doesn't depend in installToRoot, so this will always fail when it is struck,
The spirit here is right, but I don't think itest is the place for this test to exist.  We probably need another test folder (dtest for deployment test?)
=> Ignore Jar Test since it is not called in build

code/src/java/pcgen/rules/context/AbstractReferenceContext.java, code/src/java/pcgen/rules/context/LoadContextInst.java
Reverts PCGen/pcgen#4553
This patch causes build failures - it is not logically correct
=> Revert "Simplify AbstractReferenceContext.resolveReferences"

code/src/java/pcgen/util/chooser/ChoiceHandler.java, code/src/java/pcgen/util/chooser/ChooserFactory.java, code/src/java/pcgen/util/chooser/RandomChooser.java
This makes more sense in library code than in application code and just
causes warning. Remove.
=> Remove forRemoval from @deprecated

build.gradle
See
https://docs.gradle.org/5.1-rc-1/userguide/task_configuration_avoidance.html
for configuration avoidance documentation. This begins with the simple
ones.
=> [build] begin the conversion to newer API

code/src/java/pcgen/gui2/converter/ConvertPanel.java, code/src/java/pcgen/gui2/converter/event/TaskStrategyListener.java, code/src/java/pcgen/gui2/converter/event/TaskStrategyMessage.java
These methods are never called and the contents of the methods don't
matter. Just remove them.
=> Remove dead code in TaskStrategyListener

code/src/java/pcgen/gui2/tools/PCGenAction.java
We no longer use mrj, so this is always false.
=> PCGenAction: remove always false check

code/src/java/pcgen/core/SettingsHandler.java, code/src/java/plugin/exporttokens/SpecialAbilityToken.java, code/src/java/plugin/exporttokens/SpellMemToken.java
This setting was initially added CVS in 1.175 of SettingsHandler.java.
At present there is no UI to modifying the setting, though in theory
it is honored if it was set in the past.
It doesn't seem useful to keep it around, is undocumented, and adds a
mild amount of complexity to some tokens.
=> Settings: remove 'rog' setting

code/src/java/pcgen/gui2/tabs/PurchaseInfoTab.java, code/src/java/pcgen/resources/lang/LanguageBundle.properties
Sometimes equipment gets used rather than sold. Instead of having to switch
the sell mode each time, add a new button.
(this PR should be rebased; not squashed)
=> CODE-2772: Implement a 'remove equipment' button

code/standards/pcgen.importorder
This is intended to match pcgen's code standards for import ordering.
=> Add `.importorder` file for Eclipse

build.gradle
The wrapper (pcgen.sh) also needs to be updated, but one thing at a time.
=> Teach Gradle about the application name on macOS

code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/facet/FacetInitialization.java, code/src/java/pcgen/cdom/facet/GrantedVarFacet.java, code/src/java/pcgen/cdom/helper/BridgeListener.java
Today, GRANT of a variable can only be used on CDOMObjects (e.g. SKILL), but that is too limited.  It should work on any object that allows new-style variables (e.g. DYNAMIC objects should work too)
=> Move Granted Vars to any PCGenScoped object

code/src/java/pcgen/rules/context/AbstractReferenceContext.java, code/src/java/pcgen/rules/context/RuntimeReferenceContext.java, code/src/java/pcgen/util/StringPClassUtil.java
This fixes - in hopefully a brute-force enough fashion that it's "final" - the problem of how we access a format like "SKILL".  The historical problem has been "SKILL" as a format isn't defined until the first skill is loaded, which is very late.  A previous system had tried to hack through that and say "if you requested something we recognize as a CDOM format, we'll just create it on the fly", but it has a bit of a loophole that will fail.  Asking for an Array of a format before the base format will cause the logic to fail.  This forces a pre-build of all of the "known basic formats" so that this shouldn't occur (for at least those base formats - which is most of what we will use in the formula system to start)
=> This fixes a race condition on creation of formats for CDOM classes

code/src/utest/plugin/lsttokens/testsupport/AbstractTokenTestCase.java
This is another part of fixing the issues we currently have in master.  There is good evidence we are suffering from a memory leak of some sort, and probably not by us (but from JUnit, Gradle, etc.).  This has certain tests clean up their variables, meaning their objects will be garbage collected after the test is run.  This significantly reduces memory strain (even though one could assert it shouldn't since the objects should be destroyed when the test exits)
=> [FOR FREEZE] Cleanup in test to reduce memory strain

code/src/utest/plugin/lsttokens/testsupport/AbstractListInputTokenTestCase.java
This is one part of lifting the current code freeze - this eliminates temporarily a transient error being caused by weak references / unpredictable garbage collection.
Longer term, the associated tokens need better behavior (they should store the references in the object, actually, even if unused,  so that errors are guaranteed to be displayed)
=> [FOR FREEZE] Remove test (for now) that causes a transient error

code/src/test/pcgen/AbstractCharacterTestCase.java, code/src/test/pcgen/core/BioSetTest.java, code/src/test/pcgen/core/ChallengeRatingPathfinderTest.java, code/src/test/pcgen/core/EquipmentTest.java, code/src/test/pcgen/core/PCClassTest.java, code/src/test/pcgen/core/PlayerCharacterSpellTest.java, code/src/test/pcgen/core/analysis/SpellLevelTest.java, code/src/test/pcgen/core/bonus/BonusTest.java, code/src/test/pcgen/core/prereq/PreFactSetTest.java, code/src/test/pcgen/core/prereq/PreFactTest.java, code/src/test/pcgen/core/prereq/PreSpellDescriptorTest.java, code/src/test/pcgen/core/prereq/PreSpellSchoolTest.java, code/src/test/pcgen/core/prereq/PreSpellSubSchoolTest.java, code/src/test/pcgen/core/prereq/PreSpellTypeTest.java, code/src/test/pcgen/gui2/facade/CompanionSupportFacadeImplTest.java, code/src/test/pcgen/gui2/facade/SpellBuilderFacadeImplTest.java, code/src/test/pcgen/io/ExportHandlerTest.java, code/src/test/pcgen/io/PCGVer2ParserCharacterTest.java, code/src/test/pcgen/io/exporttoken/SpellMemTokenTest.java, code/src/test/plugin/exporttokens/SkillSitTokenTest.java, code/src/test/plugin/exporttokens/SkillTokenTest.java, code/src/testcommon/plugin/lsttokens/testsupport/BuildUtilities.java
This is another portion of fixing the problems we have in master and eventually lifting the code freeze.
This changes how certain tests behave. Due to some enhancements deployed over the last few days, a number of features have interacted, causing a few badly behaved unit tests to be exposed in their less than stellar behavior. Some of these unit tests required additional setup for a test before they "finish the load" and resolve references. In order to accommodate that, a fairly significant change to AbstractCharacterTestCase was required. This will fix a number of unit tests that are currently failing (3 ish?)
=> [FOR FREEZE] Move around to have finishLoad() in CharacterTestCase

code/src/utest/plugin/lsttokens/MoveLstTest.java, code/src/utest/plugin/lsttokens/TypeLstTest.java, code/src/utest/plugin/lsttokens/choose/NoChoiceTokenTest.java, code/src/utest/plugin/lsttokens/choose/UserInputTokenTest.java, code/src/utest/plugin/lsttokens/equipment/AltTypeTokenTest.java, code/src/utest/plugin/lsttokens/kit/funds/FundsTokenTest.java, code/src/utest/plugin/lsttokens/pcclass/HDTokenTest.java, code/src/utest/plugin/lsttokens/spell/ClassesTokenTest.java, code/src/utest/plugin/lsttokens/spell/DomainsTokenTest.java, code/src/utest/plugin/lsttokens/template/SubraceTokenTest.java, code/src/utest/plugin/lsttokens/testsupport/AbstractGlobalIntegerTokenTestCase.java, code/src/utest/plugin/lsttokens/testsupport/AbstractIntegerTokenTestCase.java, code/src/utest/plugin/lsttokens/testsupport/AbstractTypeSafeListTestCase.java
This message will make it harder to convert from Junit 3/4 to 5.
=> [*] Remove extranious "message" from several unit tests

build.gradle
I need to make sure I more fully understand the implications of
'implementation' on code we distribute or use in later tasks. Revert for 
now.
(also fix the grouping of one dep)
depends on #5072
=> [build] revert change to impl and back to compile

code/pluginbuild.xml, code/src/java/pcgen/core/AgeSet.java, code/src/java/pcgen/core/BioSet.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/output/model/AgeSetModel.java, code/src/java/pcgen/persistence/lst/BioSetLoader.java, code/src/java/plugin/exporttokens/deprecated/AgeToken.java, code/src/java/plugin/lsttokens/gamemode/ageset/BonusToken.java, code/src/java/plugin/lsttokens/gamemode/ageset/KitToken.java, code/src/utest/pcgen/cdom/facet/analysis/AgeSetFacetTest.java
(1) Allows comment lines in BioSettings file (starting with # as other LST files)
(2) Takes the two behaviors of AgeSet and makes them into proper tokens (Avoid Dummy PObjects)
(3) Makes a few stricter changes to BioSettings files
(3a) REGION must be on own line [I think this is done in practice anyway]
(3b) Other functional Lines must start with RACENAME: [I think this is done in practice anyway]
(4) AgeSet is Loadable (zero arg constructor) to enable future work
=> Tokenize AgeSet information

code/src/itest/pcgen/io/testsupport/AbstractGlobalTargetedSaveRestoreTest.java
Note the test was testing for +/- 1.0, which is a huge range and would
cause errors to be missed.
Converted two other items to assertEquals that were not converted in
PR #4472 for some reason.
=> Fix a test equality issue injected during a test conversion.

build.gradle
Necessary to allow the unit tests to be run by hand in eclipse.
Updated per Eitan's comments on a previous PR.
=> Revert change to XMLUnit items

.travis.yml, build.gradle
In an effort to eventually move us to building an uberjar and using
gradle's native runtime scripts, remove the mode that installs files to
the root. Instead all output will always be in `output`
Further, allow build's output to be cached by not depending on 'clean'
=> Distribution: eliminate 'root' mode

code/src/itest/plugin/lsttokens/editcontext/testsupport/AbstractIntegrationTestCase.java
This pulls out a (small) piece of #5230
=> AbstractIntegrationTestCase: switch to assertArrayEquals

data/pathfinder/dreamscarred_press/ultimate_psionics/up_biosettings.lst, data/pathfinder/paizo/campaign_setting/dragon_empires_gazetteer/deg_biosettings.lst, data/pathfinder/paizo/player_companion/blood_of_the_moon/botm_biosettings.lst
I think there was a recent change that made the SOURCEx tags at the top of the file no longer legal for biosettings.
=> Fix Biosettings files

data/pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_globalvar.lst
The wrong FACT was used in the line that gives the shield proficiency so it was unable to be replaced.
=> Fixed Samurai archetype support for shield proficiency

code/src/java/pcgen/cdom/facet/analysis/MovementResultFacet.java, code/src/utest/pcgen/cdom/facet/analysis/MovementResultFacetTest.java
Without this change, the PREREQ testers for movement throw an exception
if they try to find a movement speed the character doesn't have.
=> CODE-3363: avoid exception with missing MOVE type

code/src/java/pcgen/rules/persistence/util/TokenFamily.java
Generally we should avoid calling toMessage and adding it to a string.
Instead, we should use it as a 'source' in a Throwable.
=> TokenFamily: avoid swallowing exception source

code/src/java/pcgen/gui2/tabs/EquipInfoTab.java, code/src/java/pcgen/resources/lang/LanguageBundle.properties, code/src/java/pcgen/resources/lang/LanguageBundle_es.properties, code/src/java/pcgen/resources/lang/LanguageBundle_fr.properties, code/src/java/pcgen/resources/lang/LanguageBundle_it.properties, code/src/java/pcgen/resources/lang/cleaned.properties
These are four buttons on the EquipInfo Tab that appear to be completely 
unused. It seems they either used to be useful, or only there for a future
plan.
Note that other changes are mostly UI simplifications post-deletion. Ideally this change should be _rebased_ as the deletion and UI changes are two different commits.
=> EquipInfoTab: remove unused buttons

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenMenuBar.java
I'd be happy to work on or implement some of these in the future, but
its confusing when you accidentally press a key to see an exception.
Also, it makes it seem like there is more implemented than actually
exists.
This also adds missing tooltips and missing localization to menu items.
=> PCGenActionMenu: delete unsupported actions

code/src/java/pcgen/gui2/PCGenStatusBar.java
When the mouse is released after being moved, most users don't expect
the UI to react. Override the correct item to react to this.
=> PCGenStatusBar: only react to click, not release

code/src/java/pcgen/core/utils/CoreUtility.java, code/src/java/pcgen/gui2/converter/LSTConverter.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/persistence/lst/LstFileLoader.java, code/src/java/pcgen/persistence/lst/LstLineFileLoader.java, code/src/java/pcgen/persistence/lst/LstObjectFileLoader.java, code/src/java/pcgen/persistence/lst/VariableLoader.java
The previous code makes an attempt to be fast by reading into a
StringBuilder and using a buffer, but in reality the JVM can do a better
job than we can.
We can do even better if we were to hide the 'reader' abstraction and
handle files differently from net URLs.
- while here: fix a security issue where we default to assuming URLs are
non-net. This would break with e.g. h2 or QUIC schemes.
=> [CoreUtility] speed up file reading.

code/src/java/pcgen/core/bonus/Bonus.java
- add Locale since Bonus is always internal name, not translatable text
- use modern newClass
- don't swallow exception if unable to build bonus class
- avoid explicit StringBuilder. Java does this automatically if needed.
=> Bonus: cleanup

code/src/java/pcgen/system/PluginClassLoader.java
Rather than using our own custom implementation of buffer-reading,
instead use the likely better-optimized native functions.
=> PluginClassLoader: use native methods to read all bytes

code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/bonus/Bonus.java, code/src/java/pcgen/persistence/lst/AbilityLoader.java, code/src/java/pcgen/persistence/lst/BioSetLoader.java, code/src/java/pcgen/persistence/lst/GenericLoader.java, code/src/java/pcgen/persistence/lst/KitLoader.java, code/src/java/pcgen/persistence/lst/LevelLoader.java, code/src/java/pcgen/persistence/lst/LstUtils.java, code/src/java/pcgen/persistence/lst/PCClassLoader.java, code/src/java/pcgen/persistence/lst/VariableLoader.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/plugin/lsttokens/eqslot/NumslotsToken.java, code/src/java/plugin/lsttokens/gamemode/MenuentryToken.java
See https://shipilev.net/jvm/anatomy-quarks/10-string-intern for some
useful information.  In addition, we don't actually rely on the strings
being interned (equality check is usually done via .equals() instead of
==).
=> [*] avoid calling string.intern()

code/src/java/pcgen/core/character/CharacterSpell.java, code/src/java/pcgen/core/character/SpellInfo.java, code/src/java/pcgen/facade/core/SpellFacade.java, code/src/java/pcgen/gui2/facade/Gui2InfoFactory.java, code/src/java/pcgen/gui2/facade/SpellFacadeImplem.java
There is only implementation of SpellFacade. This assumption is used in
the character output code in order to get at the underlying impl of the
facade. Fix this by just pulling the impl functions into the interface.
=> [SpellFacade] pull public functions into interface

code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java
Store the language choosers list in the CharacterFacadeImpl after creation, so we can add to it later, when changes are triggered.
Mainly, we want to ensure the bonus language chooser is not available on a new character if there is no race, but this will also handle instances of bonus languages being added by intelligence increase, or other general triggers that call `refreshLanguageList`.
It will also remove the bonus chooser if it exists, and bonus languages remaining has been set to 0, or race was removed.
Coincidentally, this also removes the bonus language todo's if a race is not selected, or is removed.
=> CODE-3248: store language choosers in CharacterFacadeImpl

code/src/java/pcgen/cdom/enumeration/ObjectKey.java, code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/kit/KitGear.java, code/src/java/pcgen/core/npcgen/EquipmentItem.java, code/src/java/pcgen/gui2/facade/CharacterUtils.java, code/src/java/pcgen/io/exporttoken/EqToken.java
As a prereq to converting weight to the formula system, reduce the
reliance on the ObjectKey by itself.
=> [*] Switch users of ObjectKey.WEIGHT.get to getSizeAdjustment()

code/src/java/pcgen/gui2/PCGenFrame.java
Problem:
If you hit "esc" or close the "Save all" character dialog, it gets
treated as if you selected "Save All" which is unexpected.
Solution:
Treat "close" as "cancel" and do not close PCGen.
=> PCGenFrame: handle closing "save all" dialog

code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/facet/ScopeFacet.java, code/src/java/pcgen/cdom/formula/scope/DynamicScope.java, code/src/java/pcgen/cdom/formula/scope/GlobalPCScope.java, code/src/java/pcgen/cdom/formula/scope/LegalScopeUtilities.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/pcgen/rules/context/LoadContextInst.java, code/src/java/plugin/lsttokens/variable/GlobalToken.java, code/src/java/plugin/lsttokens/variable/LocalToken.java, code/src/utest/pcgen/base/solver/SetSolverManagerTest.java, code/src/utest/pcgen/cdom/base/FormulaFactoryTest.java, code/src/utest/pcgen/cdom/formula/VariableChannelTest.java, code/src/utest/pcgen/cdom/helper/BridgeListenerTest.java, code/src/utest/plugin/function/GetFactFunctionTest.java, code/src/utest/plugin/function/GetOtherFunctionTest.java, code/src/utest/plugin/function/InputFunctionTest.java, code/src/utest/plugin/function/testsupport/AbstractFormulaTestCase.java, code/src/utest/plugin/modifier/bool/SetBooleanModifierTest.java, code/src/utest/plugin/modifier/number/AddNumberModifierTest.java, code/src/utest/plugin/modifier/number/DivideNumberModifierTest.java, code/src/utest/plugin/modifier/number/MaxNumberModifierTest.java, code/src/utest/plugin/modifier/number/MinNumberModifierTest.java, code/src/utest/plugin/modifier/number/MultiplyNumberModifierTest.java, code/src/utest/plugin/modifier/number/SetNumberModifierTest.java, code/src/utest/plugin/modifier/orderedpair/SetOrderedPairModifierTest.java, code/src/utest/plugin/modifier/string/SetStringModifierTest.java
We should do this because it is true. Also, because we are soon going to
introduce a new "EQ" scope that differs from the PC scope.
=> CODE-3380: [*] Rename GlobalScope to GlobalPCScope

build.gradle
- Added support for plugin composite builds.
- Added support for continuous builds.
- Added support for capturing the details of annotation processors used during Java compilation.
=> [build] update build-scan to 2.3

code/pluginbuild.xml, code/src/java/pcgen/cdom/util/CControl.java, code/src/java/pcgen/core/Equipment.java, code/src/java/plugin/encounter/EncounterPlugin.java, code/src/java/plugin/lsttokens/gamemode/codecontrol/WeaponHandsToken.java, code/src/java/plugin/lsttokens/gamemode/wieldcategory/HandsToken.java
Adds WEAPONHANDS Code Control to disable use of HANDS: on WieldCategory.
WARNING: This will only be (easily) usable in game modes where the # of hands does not need to change based on wield category.  Other systems might be possible, but that is unlikely until a WieldCategory code control exists (those systems will likely require two changes at once)
=> [NEWTAG-620] WEAPONHANDS Code Control

code/src/java/pcgen/core/DataSet.java, code/src/java/pcgen/core/Kit.java, code/src/java/pcgen/gui2/facade/EquipmentBuilderFacadeImpl.java, code/src/java/pcgen/gui2/tabs/PurchaseInfoTab.java, code/src/java/pcgen/gui2/tabs/models/BigDecimalFieldHandler.java, code/src/java/plugin/lsttokens/deprecated/RemoveFeatToken.java
The constructor is unpredictable and can give "wrong" results at times.
Instead use the string representation which is more obvious.
=> [*] use BigDecimal.valueOf rather than constructor

code/src/java/applicationContext.xml, code/src/java/pcgen/cdom/facet/model/SizeFacet.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/utest/pcgen/cdom/facet/model/SizeFacetTest.java
The previous design seems to have assumed they would be used together,
but that shouldn't be necessary.  Because SizeFacet's PC Size
calculation depends on the base size, we need to intercept that within
the Facet and not only do the code control interception in the case when
the base size is requested from PlayerCharacter.
=> Allow BaseSize Code control to be used independently of PCSIZE Control

code/src/java/pcgen/core/Equipment.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/term/PCCountContainersTermEvaluator.java, code/src/java/pcgen/core/term/PCCountEqTypeTermEvaluator.java, code/src/java/pcgen/facade/core/EquipmentBuilderFacade.java, code/src/java/pcgen/gui2/facade/EquipmentBuilderFacadeImpl.java, code/src/java/pcgen/io/exporttoken/EqTypeToken.java
- acceptsChildren and isContainer are identical. Combine them and pick
better name.
- remove canAddModifier from EquipmentBuilderFacade, it is unused. We
should possibly actually use it instead of removing it.
=> Equipment: remove some unused code; combine two functions

code/src/java/pcgen/cdom/base/PCGenIdentifier.java, code/src/java/pcgen/cdom/enumeration/CharID.java, code/src/java/pcgen/cdom/enumeration/DataSetID.java
This is in preparation for  ResultFacet and VariableStoreFacet taking a
DatasetID instead of a CharID
=> NEWTAG-627: Add getDatasetID to PCGenIdentifier interface

build.gradle
With the conversion to JavaFX we longer need cobra or rhino.
=> [build] remove now unneeded dependencies

code/src/java/pcgen/gui2/tabs/InfoTabbedPane.java, code/src/java/pcgen/system/PluginClassLoader.java
Thread priorities are non-portable and mostly meaningless.
=> [*] avoid setting Java thread priority

code/src/java/pcgen/core/utils/ShowMessageDelegate.java
This is prep work for migrating JOptionPane to JavaFX
=> gui utils: remove unused showMessageDialog function

build.gradle, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui3/JFXPanelFromResource.java, code/src/java/pcgen/gui3/SimpleHtmlPanelController.java, code/src/resources/pcgen/gui3/SimpleHtmlPanel.fxml
This continues to more fully decouple code from UI. Further it makes the
notion of a controller "real" in pcgen.
Long term we may even have people who edit the UI that don't need code
permissions or info.
While this is a trivial example, I'm trying to figure out the right
pattern for UI in pcgen.
=> [gui3] use FXML instead of creating nodes in code

code/src/java/pcgen/gui2/PCGenUIManager.java
It is possible that pcgenFrame is null when cmd-q is hit. Handle this
case by ignoring the frame and just shutting down.
=> PCGenUIManager: handle null pcgenFrame

code/src/java/pcgen/gui3/preloader/PCGenPreloader.java
Since my original implementation I found a much nicer way of handling
the async return. This pattern turns what async into a blocking call,
but enforces it at the boundary of `gui3`. If we ever find ourselves
having performance issues, we could always pass the future out.
=> PCGenPreloader: simplify getController

code/src/java/pcgen/gui3/preloader/PCGenPreloader.java
we require a non-null controller which is only guaranteed to exist after
the UI is initialized. Since we can't know when it is safe to run,
serialize getting the controller on the UI thread.
=> PCGenPreloader: fix runtime of preloader

code/src/java/pcgen/gui2/dialog/ExportDialog.java
This broke in 96dcdde641c62b43c4750fdc9cb52cbc8e35f83a. The previous
implementation was recursive (as the notFileFilter implicitly did NOT
filter out directories). Matching this behavior fixes the issue.
=> ExportDialog: fix exports

code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/prefs/EquipmentPanel.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_de.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/resources/pcgen/lang/LanguageBundle_pt.properties
As it happens, the preference is never actually used in code.
=> llowMetamagicInCustomizer: remove preference

code/src/java/pcgen/gui2/doomsdaybook/NameGenPanel.java, code/src/java/plugin/initiative/gui/Initiative.java
NameGenPanel and Initiative have their own notion of "version". Aside
from almost never changing, this adds complexity for little gain.
Remove.
=> Remove 'version' from some plugins

code/src/java/pcgen/cdom/facet/ModifierFacet.java, code/src/java/pcgen/cdom/facet/RemoteModifierFacet.java, code/src/java/pcgen/cdom/formula/scope/DynamicScope.java, code/src/java/pcgen/cdom/formula/scope/EquipmentPartScope.java, code/src/java/pcgen/cdom/formula/scope/EquipmentScope.java, code/src/java/pcgen/cdom/formula/scope/GlobalEQScope.java, code/src/java/pcgen/cdom/formula/scope/GlobalPCScope.java, code/src/java/pcgen/cdom/formula/scope/PCGenScope.java, code/src/java/pcgen/cdom/formula/scope/RaceScope.java, code/src/java/pcgen/cdom/formula/scope/SaveScope.java, code/src/java/pcgen/cdom/formula/scope/SizeScope.java, code/src/java/pcgen/cdom/formula/scope/SkillScope.java, code/src/java/pcgen/cdom/formula/scope/StatScope.java, code/src/java/pcgen/cdom/grouping/GroupingInfo.java, code/src/java/plugin/function/GetOtherFunction.java, code/src/java/plugin/function/GroupFunction.java, code/src/java/plugin/lsttokens/ModifyLst.java, code/src/java/plugin/lsttokens/ModifyOtherLst.java
This avoid catching runtime UnsupportedOperationException, which seemed
like bad behavior
Note: some situations assumed the format existed, so some bug fixes are embedded
=> CODE-3401: Cleanup: Make FormatManager in scope an Optional

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java
Plugin loading is currently inside of a JTabbedPane - but it doesn't
have to be as is the only tab. Pull this out into the main frame.
Prep work to make porting to JavaFX easier.
=> Preferences: pull plugin loading out of tabbed pane

code/src/java/gmgen/gui/PreferencesPluginsPanel.java, code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties
PCGen is always disabled, and thus there is no choice. This simplifies
the plugin-loading UI quite a bit.
=> PluginPanel: remove checkboxes for systems

code/src/java/gmgen/plugin/Combatant.java, code/src/java/gmgen/plugin/Effect.java, code/src/java/gmgen/plugin/Event.java, code/src/java/gmgen/plugin/InitHolder.java, code/src/java/gmgen/plugin/InitHolderList.java, code/src/java/gmgen/plugin/Spell.java, code/src/java/pcgen/core/RollingMethods.java, code/src/java/pcgen/core/kit/KitTemplate.java, code/src/java/pcgen/gui2/doomsdaybook/NameGenPanel.java, code/src/java/pcgen/gui2/tabs/AbilitiesInfoTab.java, code/src/java/pcgen/gui2/tabs/AbilityChooserTab.java, code/src/java/pcgen/gui2/util/treetable/DefaultSortableTreeTableNode.java, code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java, code/src/java/plugin/encounter/EncounterPlugin.java, code/src/java/plugin/initiative/gui/AttackDialog.java, code/src/java/plugin/initiative/gui/Initiative.java, code/src/java/plugin/notes/gui/NotesTreeNode.java, code/src/java/plugin/notes/gui/NotesView.java, code/src/java/plugin/overland/gui/OverPanel.java, code/src/java/plugin/overland/model/TravelMethodFactory.java, code/standards/ruleset.xml
Annotate use of Hashtable and Vector that can't be avoided. This should
allow pmd to check for such usages infecting other parts of the
codebase.
=> pmd: reduce number of exclusions (part 2)

code/src/java/pcgen/cdom/base/Constants.java, code/src/java/pcgen/core/CustomData.java, code/src/java/pcgen/core/EquipmentList.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/prefs/EquipmentPanel.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_de.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/resources/pcgen/lang/LanguageBundle_pt.properties, code/src/resources/pcgen/lang/cleaned.properties
Much of this feature has been broken for some time. It
- teaches code too much about the data
- makes several assumptions about naming of items which should
not be required.
- introduces a performance penalty of having so many items.
- requires hacks in data where the auto-gen item may conflict with
special rules around some of the items
as such, remove it.
Ref: CODE-3123, CODE-3409, CODE-761, CODE-1873, CODE-3159
=> CODE-3159: Auto generation of equipment: remove feature

code/src/java/pcgen/cdom/base/Constants.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/core/display/CharacterDisplay.java, code/src/java/pcgen/io/IOConstants.java, code/src/java/pcgen/io/PCGVer2Creator.java
As it happens, the tab display style heavily depends on the code 
understanding details like "race" or "class" and can be fully replaced by
having a "tab label" in the file (which there is). If we ever want to bring
it back, we'll need a data driven list of options and format strings.
Depends on #5586
=> Tab Display Style: remove it

code/src/java/pcgen/core/SettingsHandler.java
As it happens, this setting is never read in code.
=> spellMarketPriceAdjusted: remove setting

code/src/java/pcgen/core/AbilityUtilities.java, code/src/java/pcgen/core/utils/LastGroupSeparator.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/persistence/SourceFileLoader.java, code/src/java/plugin/initiative/gui/OpposedCheckDialog.java
Java does not actually enforce that unchecked exceptions declared on
functions are caught. As such, remove it from the decl and leave it in
the documentation only (or just remove if unneeded).
=> Avoid explicitly throwing unchecked exceptions

code/src/java/pcgen/system/Main.java
Having an option mildly complicates the code. In addition, it doesn't
match any of the existing pcgen options (as it is a java param).
=> Main: remove option to not show splash screen

code/src/java/pcgen/gui3/preferences/EquipmentPreferencesModel.java, code/src/java/pcgen/gui3/preferences/EquipmentPreferencesPanelController.java
This moves the bounds data into the model. It also set the valueFactory
(enforcing the bounds) into the init function rather than relying on it
happening during an early `reset()` call.
=> EquipmentPreferencesPanelController: move data into model

code/src/java/plugin/notes/gui/JIcon.java
JIcon has a fair amount of logic for the case where `Desktop` doesn't
support opening a file. There are few cases where this matters and it
complicates a class that will eventually need to be removed or migrated.
Remove the logic.
=> JIcon: remove support for non-desktop supported

code/src/java/pcgen/gui3/JFXPanelFromResource.java
Without this we risk getting a null value
=> JFXPanelFromResource: getController operate on JavaFX thread

code/src/java/gmgen/GMGenSystem.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/resources/pcgen/lang/LanguageBundle_ja.properties
As much as I'd like an online version check, we don't have one right
now. Remove code to simplify future efforts to migrate this code to
JavaFX
=> GMGen: eliminate "check newest version"

code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/prefs/LocationPanel.java, code/src/java/pcgen/gui2/tools/DesktopBrowserLauncher.java, code/src/java/pcgen/system/PCGenSettings.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_de.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/resources/pcgen/lang/LanguageBundle_pt.properties, code/src/resources/pcgen/lang/cleaned.properties
This setting is actually ignored by PCGen in favour of using the Desktop
class introduced in Java 6. As such, completely eliminate the setting
and the UI to set it.
=> browserPath: remove setting

code/src/java/pcgen/io/ExportHandler.java
Configuration now directly takes a version number for bug-fixes. I did
not test new configurations but we are notably behind: all versions
between 2.3.21 and 2.3.28 introduced changes.
Note that some tests set a newer version.
=> ExportHandler: use a non-deprecated ctor for config

code/src/java/pcgen/gui2/prefs/LanguagePanel.java
Before we load settings, there is no selected value.
=> LanguagePanel: handle null

code/src/java/pcgen/system/Main.java
JFXPanel can't be constructed in the headless case. Avoid doing so.
This allows int tests to run, but exposes that they have been failing
for some time.
=> Main: construct dialog only in "use gui" case

code/src/java/gmgen/GMGenSystem.java, code/src/java/pcgen/gui2/PCGenUIManager.java, code/src/java/pcgen/gui3/application/DesktopHandler.java
- test for "supported" before using a feature
- avoid platform specific names
- move to gui3 since it is a "converted" class
=> DesktopHandler: handle unsupported platforms

code/src/java/plugin/pcgtracker/PCGTrackerPlugin.java
Note that setSelectedComponent may not be dead, since isActive depends
on said value.
=> PCGTrackerPlugin: remove some dead code.

code/src/java/pcgen/gui2/tabs/models/HtmlSheetSupport.java
If we have multiple changes, permit the latest one to go through.
=> HtmlSheetSupport: make it possible to interrupt the refresher

code/src/java/pcgen/gui2/tabs/models/HtmlSheetSupport.java
While it is possible that newer JDKs can still make use of this cache,
we'll be modifying the code in the near future to covert to JavaFX.
=> ImageCache: eliminate hack for old JDKs

code/standards/ruleset.xml
Also change the reference to "latest". The current version is defined in
gradle and adding multiple places to update is annoying. PMD doesn't
change often enough that going to the latest documentation isn't usually
an issue.
=> pmd: add more excuses

code/src/java/pcgen/core/SettingsHandler.java
Remove some unused code from SettingsHandler. Also remove some comments
which will slowly become less relevant over time as we turn settings
into Properties.
=> SettingsHandler: remove unused code and comments

code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/prefs/OutputPanel.java, code/src/java/pcgen/io/exporttoken/WeaponToken.java, code/src/java/plugin/exporttokens/deprecated/InvalidTextToken.java, code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/testResources/pcgen/lang/cleaned.properties
There is limited reason to make this a preference: it merely changes the
text that gets printed when an option is not available. Further, it
complicates some of the options dialog, so remove it.
=> Remove "invalid option text" preference

code/src/java/pcgen/gui3/dialog/AboutDialogController.java, code/src/resources/pcgen/gui3/component/PCGenStatusBar.fxml, code/src/resources/pcgen/gui3/dialog/AboutDialog.fxml, code/src/utest/pcgen/gui3/dialog/AboutDialogTest.java
- We no longer distribute L2F, so remove the license from the dialog.
- Further, add test to ensure that about dialog continues loading.
- Add some ids to components to facilitate future tests
=> AboutDialog: remove l2f license; add test

code/src/java/pcgen/gui2/PCGenFrame.java
This behavior needs to be redone for JavaFX and complicates the
migration. Further it isn't quite correct: it checks that _any_ screen
can handle its size without regard to which screen it will end up on.
=> PCGenFrame: stop storing state across restarts

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/tabs/AbilityChooserTab.java, code/src/java/pcgen/gui2/tabs/SkillInfoTab.java, code/src/java/pcgen/gui2/tools/FlippingSplitPane.java
Now that we no longer persist state, there is no more use for a Prefs
key.
=> FlippingSplitPane: remove prefsKey

code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/core/SettingsHandler.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java
There is no UI to change this setting, so it only works for people that
set it in older versions or that manually modified their settings files.
As such, stop enforcing the option.
=> SettingsHandler: remove enforceSpendingBeforeLevelUp

code/pcgen.sh
Make available (free) memory calculation in linux use correct value from /proc/meminfo
In /proc/meminfo, the "MemFree:" value is the amount of non allocated memory. Linux uses available memory as cache to speed-up IO, keeping only a small amount of unused memory as free memory. So the correct calculation to determine the amount of free memory should instead use the "MemAvailable" field.
Fixes PCGen#5796
Test-Plan:
Verified that running `available_memory=$(grep MemAvailable: /proc/meminfo | awk '{ print $2; }') ` on an arch linux subsystem correctly calculated the available memory as opposed to the "MemFree" which was basically empty
```
~$ echo $(grep MemAvailable: /proc/meminfo | awk '{ print $2; }')
3164836
~$ echo $(grep MemFree: /proc/meminfo | awk '{ print $2; }')
104320
```
=> Linux Launch Script: Calcuate free memory from correct value

code/src/java/pcgen/gui2/sources/SourceSelectionDialog.java, code/src/java/pcgen/system/FacadeFactory.java
This is a rather specific feature: adding the ability to hide
"quick-start" sets of sources. These sources only show up on one panel -
and by the time you're hiding them, you're likely an expert enough to
just ignore them.
While this feature is easy enough to port to JavaFx, it also adds
complexity by merely existing (any feature does) - so remove it.
=> SourceSelectionPanel: remove hide/unhide button

code/src/test/pcgen/inttest/PcgenFtlTestCase.java
This is required to verify output.
=> PcgenFtlTestCase: stop deleting output file

code/src/java/pcgen/gui2/prefs/OutputPanel.java
This broke when a setting was removed but constraints were not reset
correctly.
=> OutputPanel: fix squashed display

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui3/GuiAssertions.java, code/src/java/pcgen/gui3/JFXPanelFromResource.java, code/src/java/pcgen/gui3/preferences/ColorsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/ConvertedJavaFXPanel.java, code/src/java/pcgen/gui3/preferences/CopySettingsPanelController.java, code/src/java/pcgen/gui3/preferences/DefaultsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/DisplayOptionsPreferencesPanelController.java, code/src/java/pcgen/gui3/preferences/PreferencesPluginsPanel.java, code/src/java/pcgen/gui3/preferences/SourcesPreferencesPanelController.java
This also formalizes a bit better which thread to
expect to run applyOptionValuesToControls on. More specifically,
it should always run on the thread of the "type" of control
(that is, converted = javafx; others = swing)
=> PreferencesDialog: convert tree to JavaFX

code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java
The warning dialog no longer directly displays HTML so just use a
standard string.
=> CharacterFacadeImpl: stop using HTML for kit warnings

code/src/java/gmgen/gui/PreferencesDialog.java
Much like in 8ea81b0b03f353887a0573fd4a66a25dac8daab8, while
FlippingSplitPane has some nice utility, it isn't required for a
preferences dialog.
=> PreferencesDialog: downgrade to JSplitPane

code/src/java/pcgen/gui2/InfoGuidePane.java
This value gets ignored by the callee, so just remove it.
=>  InfoGuidePane: don't call pane.setOpaque

build.gradle, code/gradle/reporting.gradle
We don't use it much and it adds more complexity (i.e., might cause
failure on windows)
=> build: remove build-scan plugin

code/src/java/pcgen/gui2/util/JDynamicTable.java, code/src/java/pcgen/gui2/util/JTreeViewTable.java
This causes an exception JTableMenuButton@684f551b[styleClass=root
button]''is already set as root of another scene
=> JTableMenuButton: avoid reconstructing wrapped corner button

code/src/java/pcgen/system/CharacterManager.java
JavaFX warning doesn't, by default, use HTML for errors anymore.
=> CharacterManager: stop using HTML for load errors

code/src/utest/pcgen/gui3/dialog/AboutDialogTest.java, code/src/utest/pcgen/gui3/preloader/PCGenPreloaderTest.java
This pull request add `System.load("C:\\Windows\\System32\\WindowsCodecs.dll");` to 2 of the tests as a temporary fix to https://github.com/javafxports/openjdk-jfx/issues/66. This was causing `gradlew` builds to fail on my side with `EXCEPTION_ACCESS_VIOLATION` during running `Task :test`.
This commit need to be tested on linux and mac machines as it could cause builds to fail on them.
=> Added temporary fix for build error 

build.gradle
This ensures the clean never runs after build if called in the same dependsOn such as in prepareRelease. 
`task prepareRelease (dependsOn: ['clean', 'build']) {` Without the `shouldRunAfter` (this Pr addition) the build and clean could run in either order. Gradle just cared about them running before `prepareRelease` which often led to the situation of clean running after build and deleting the build folder.
~~I am using `shouldRunAfter` rather than `mustRunAfter` so that clean and build can be run independently as well.~~ - This was incorrect.
=> Fixed clean running after build deleting build folder

code/src/java/pcgen/gui2/dialog/PreferencesDialog.java, code/src/java/pcgen/gui2/prefs/CharacterStatsPanel.java, code/src/java/pcgen/gui2/prefs/OutputPanel.java, code/src/java/pcgen/gui2/tools/DesktopBrowserLauncher.java, code/src/java/pcgen/gui3/JFXPanelFromResource.java, code/src/resources/pcgen/lang/LanguageBundle.properties
- Fix alert when documentation viewer not supported on platform.
- Small typo in OK button text for preferences dialog.
-------------------------------------
More progress on the road to UI working. Some stop gaps to shore up the preferences and the alert for documentation viewer. Also a small typo that didn't warrant a ticket.
=> FIX CODE-3454: Preferences do not save when applying

code/src/itest/pcgen/io/testsupport/AbstractSaveRestoreTest.java, code/src/java/pcgen/gui2/facade/DescriptionFacadeImpl.java, code/src/java/pcgen/io/PCGVer2Creator.java, code/src/java/pcgen/io/PCGVer2Parser.java, code/src/java/plugin/pretokens/test/PreCityTester.java, code/src/test/pcgen/core/prereq/PreCityTest.java
- Append CITY instead of RESIDENCE in PCGVer2Creator.
- Complete the rename where applicable of PCStringKey.RESIDENCE =>PCStringKey.CITY .
--------------
Resolves issue of saving the City field to PCG.
=> FIX CODE-3459: Descriptions City Field Does Not Save

preview/d20/modern/statblock1.htm
- Replaced inline with standard for loop, strangely one liner would not
expand on character preview tab.
------------------------------
This fix is in response to #6006 on the 6.08 branch. It affects master as well, so please merge to master and cherry pick it back to 6.08 branch. Modern character loading isn't working well on master atm, so to test use 6.08.
=> FIX GITHUB-6006: d20 Modern statblock1.htm Template does not display

code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/sources/SourceSelectionDialog.java
- When a character is loaded and advanced source selections brought up,
always present the character's source selections. Allows easy editting
of sources.
-------------------------
Only overwrite sources in advanced selection if user wanted to load sources and only do this when the PCG is loaded for first time. Prevents the clobber issue in last PR.
This isn't a priority to fix on 6.08 but it is definitely very handy and probably a common complaint.
=> FIX GITHUB-5990: Loading Source from Existing Character

build.gradle
From running it
===
dependencyUpdates.resolutionStrategy Remove the assignment operator, '=', when setting this task property
===
=> [build] remove '=' from dependencyUpdates.resolutionStrategy

code/gradle/release.gradle, code/pcgen_JREx32.bat, code/pcgen_JREx64.bat
- Project depends on JDK instead of JRE during javaFX transition.
- Bundle latest full release of JDK for forseeable future.
- Use relative path for bat files.
=> FIX CODE-3461: 6.09.01 Crash Log

data/pathfinder/paizo/roleplaying_game/occult_adventures/oa_classes.lst
Like other spellcasters, a psychic detective can cast
only a certain number of spells of each spell level per
day. She knows the same number of spells and receives
the same number of spells slots per day as a bard of her
investigator level, and knows and uses 0-level knacks as a
bard uses cantrips. In addition, she receives bonus spells
per day if she has a high Intelligence score (see Table 1–3
on page 17 of the Core Rulebook).
=> Fix  DATA-4011    Psychic Detective uses Bard known spells.  

code/src/java/pcgen/system/Main.java
This is not the best fix, I just set it to open the current folder instead of the PCG_SAVE_PATH.  
It seems like we really need to actually create the preset directory paths during the initial load if they don't exist.   
When you first open the app it asks which directory will be your pcgen directory, then it looks for a characters directory in the path of whatever you selected, but nothing actually creates those directories.  So when you go to open the path, java throws a path not found behind the scenes but the user gets no indication.
=> Create PCG_SAVE_PATH after selecting options.ini location

gradle/wrapper/gradle-wrapper.properties
This is not the latest version. Gradle 6.0 and 6.0.1 has issues
resolving jep.
=> [build] bump gradle to 5.6.4

build.gradle
It wouldn't build on my linux machine because the jep url must have been changed recently.
=> [gradle] Fixed JEP dependency

code/src/java/pcgen/util/enumeration/Tab.java, code/src/java/pcgen/util/enumeration/View.java
The commit 5d56bdf7d3b32cbae141e826947c540ae1f3b4af changes the retrieval of enum entries by name to EnumUtils.getEnumIgnoreCase(). This does not match previous functionality where the given string is checked against the text variable. Therefore, pcgen crashes for enum entries where the name and text do not match.
=> Partially revert changes to enumerations

code/src/java/pcgen/base/util/NamedFormula.java, code/src/java/pcgen/cdom/content/ContentDefinition.java, code/src/java/pcgen/cdom/content/DatasetVariable.java, code/src/java/pcgen/cdom/content/UserContent.java, code/src/java/pcgen/gui2/tabs/CharacterSheetInfoTab.java, code/src/java/pcgen/io/FreeMarkerExportHandler.java, code/src/java/pcgen/system/application/DeadlockDetectorTask.java, code/src/utest/pcgen/base/util/NamedFormulaTest.java
Object.requireNonNull throws an NullPointerException, which is very ugly.  There are lots of these in the code base, which is a lazy way of getting out of methods where a null would be problematic.  This prevents the NPEs - especially the one in CharacterSheetInfoTab.
=> Fixing NullPointerExceptions raised by Objects.requireNonNull

data/pathfinder/paizo/roleplaying_game/ultimate_magic/um_abilities_class.lst
An otherwise unused ability was removed, but a reference to call that ability wasn't removed.
=> [UM] Fix unconstructed reference

build.gradle
The former is deprecated and no longer required.
=> build; replace maven with maven-publish

code/src/java/pcgen/cdom/base/CDOMObject.java, code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/rules/context/AbstractReferenceContext.java
the two moved functions were feature envy, and the field Campaign_Name_MAP had no functionality since duplicates were being checked before adding to the other map, and in addition the code removed did not work as intended if it was being used.
=> moved two functions from globals to the class the act on and removed dead code.

code/src/java/pcgen/core/Globals.java, code/src/java/pcgen/core/kit/KitGear.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/gui2/facade/EquipmentBuilderFacadeImpl.java, code/src/java/pcgen/persistence/lst/CampaignLoader.java, code/src/java/plugin/lsttokens/eqslot/NumslotsToken.java, code/src/test/pcgen/gui2/facade/EquipmentSetFacadeImplTest.java
- removed the deprecated getGame method in favor of the supported version.
- EQ_SLOT_MAP was only every using integers, so now it uses integers
- canResizeHaveEffect was using a list, with a backup list, but the backup list was only ever populated with the firs list
- getSection15 was the only access to the underlying variable, and it's only modified and never queried.
=> cleaned up Globals and changed a few callers to work with the changes

.travis.yml, build.gradle, code/gradle/release.gradle
Updated the openjdk/openjre version used in the build, fixed as many of the deprecated Gradle commands as I can. The remaining `compile` command, `compile group: 'org.apache.xmlgraphics', name: 'fop', version:'2.4'`, causes the build to fail if updated to `implementation` like the rest of the commands.
When Gradle gets to the point of doing the Windows buils using NSIS, it fails due to no files being found in the `nsis\PCGen_60903_opt\plugin\pdf\libs` folder of the build directory.
Why changing the command from `compile` to `implementation` causes the output library jars to not be build into this folder I don't know yet - I'm still learning Gradle/Java so don't know why this happens.
I can only assume it is due to a change within that task setup for Gradle, and try to have a look at it in …
=> Updated jdk/jre version, updated Gradle commands

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/io/exporttoken/WeaponToken.java, code/src/java/plugin/lsttokens/gamemode/WeapontypeToken.java
In addition to type safety, follows a better pattern of parsing in the input token rather than at runtime
=> CODE-3401: Make Weapon Type Abbreviations Type Safe

build.gradle
Items in xml-apis have now been imported into Java; therefore the dependency is redundant, and should break the compile.  It currently does not due to a but in javac.
This patch is a solution to avoid that bug in javac that we would encounter should it ever be fixed.  Note that the bug IS produced by the compiler in Eclipse, so currently Eclipse is unusable without this fix.
=> Support modern versions of Eclipse with PCGen

code/src/utest/actor/add/AbilityTokenTest.java, code/src/utest/actor/choose/AbilitySelectionTokenTest.java, code/src/utest/actor/choose/AbilityTokenTest.java, code/src/utest/actor/choose/AlignmentTokenTest.java, code/src/utest/actor/choose/ArmorProficiencyTokenTest.java, code/src/utest/actor/choose/CheckTokenTest.java, code/src/utest/actor/choose/ClassTokenTest.java, code/src/utest/actor/choose/DeityTokenTest.java, code/src/utest/actor/choose/DomainTokenTest.java, code/src/utest/actor/choose/EquipmentTokenTest.java, code/src/utest/actor/choose/LangTokenTest.java, code/src/utest/actor/choose/NoChoiceTokenTest.java, code/src/utest/actor/choose/PCStatTokenTest.java, code/src/utest/actor/choose/RaceTokenTest.java, code/src/utest/actor/choose/SchoolsTokenTest.java, code/src/utest/actor/choose/ShieldProficiencyTokenTest.java, code/src/utest/actor/choose/SizeTokenTest.java, code/src/utest/actor/choose/SkillTokenTest.java, code/src/utest/actor/choose/SpellLevelTokenTest.java, code/src/utest/actor/choose/SpellsTokenTest.java, code/src/utest/actor/choose/StringTokenTest.java, code/src/utest/actor/choose/TemplateTokenTest.java, code/src/utest/actor/choose/WeaponProficiencyTokenTest.java
Makes items private static final rather than just static
Cleans up how exceptions are processed (do it correctly with newer JUnit features)
Use BuildUtilities for common methods when possible
=> Clean Actor Tests

.travis.yml, code/gradle/distribution.gradle
Removed workaround for StartScripts block fixed in https://github.com/beryx/badass-runtime-plugin/issues/67.
Removed macos from travis build on normal pull request. Will now only run on tag builds for releases. Macos builds randomly seem to fail due to timeout issues or issues with hdiutil. Believe may be related to this jpackage bug https://bugs.openjdk.java.net/browse/JDK-8238781. For release you may need to on travis click restart build on the macos 2 or 3 times if failing before a successful build. (If macos build fails but linux passes, then release should still appear but will be missing mac installers)
Log from failed build with hdiutil:
```
> Task :jpackage
WARNING: Using incubator modules: jdk.incubator.jpackage
WARNING: Using incubator modules: jdk.incubator.jpackage …
```
=> Fixed travis builds failing and removes start script work around

data/pathfinder/paizo/roleplaying_game/occult_adventures/oa_spells.lst
The Psychic Detective archetype (Occult Adventures) is supposed to have Detect Evil on their spell list, but it was not. Added it to the Psychic Detective spell list.
=> Psychic Detective archetype missing Detect Evil on spell list

.travis.yml
Incorrect indentation in deploy block after token. Removed deploy only on `osx` as those build still may need to be restarted several times due to issues intermittent issues with jpackage creating installers. (travis osx build may be just needed to be restarted)
=> Fix travis deploy token

README.md
6.09 does not need java preinstalled and for macos should either use dmg or .sh rather than .jar which differ from 6.08.
=> Update README.md with installation process for 6.09

code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/dialog/ExportDialog.java, code/src/java/pcgen/util/FileHelper.java, code/src/java/plugin/pcgtracker/PCGTrackerPlugin.java, code/src/test/pcgen/util/FileHelperTest.java
Resolves CODE-3501, which was caused by using characters from a character name which are not allowed in filenames.
=> Sanitize filenames when creating them from character name

build.gradle, gradle/wrapper/gradle-wrapper.properties
bump a few dependencies to their latest versions.
The goal is to keep this relatively modern and buildable so that should
we get volunteers to help with the code it has a chance of being kept
alive.
=> [build] bump various dependency versions

code/src/java/pcgen/gui2/csheet/PreviewVariablesHandler.java
Problem
modern libraries prevent casting to HTMLInputElementImpl so we're unable
to fully produce character previews
Solution
Use the EventTarget interface instead.
=> [bugfix] fix casting error with preview handler

code/src/java/pcgen/gui2/PCGenActionMap.java, code/src/java/pcgen/gui2/PCGenStatusBar.java, code/src/java/pcgen/gui3/dialog/DebugDialog.java
Problem
The status bar is javafx but currently tries to open the debug dialog
through a pattern that expects the swing thread. This prevents opening
the dialog via the button (though F10 works as it is on the swing
thread).
Solution
Rejigger the mechanism of opening the debug dialog to be callable at
multiple sites. This also makes the dialog a singleton as there is no
reason for multiple instances to exist.
=> [bugfix] handle opening debug dialog from status bar

code/src/test/pcgen/persistence/lst/DataLoadTest.java
Problem / Solution
We want to check both warnings and errors be empty but we accidentally
check errors twice.
=> [bugfix] check warnings in warning list

data/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items.lst
Did not properly affect CHA-based casters
=> Robe of Powerlessness fix

data/pathfinder/dreamscarred_press/ultimate_psionics/up_classes.lst
According to Ultimate Psionics, p 50 "Each psion gains three 0 level talents (see Chapter 5: Powers) of their choice, as well as detect psionics."
This PR adds automatic "Detect psionics" spell and adjusts "spells known" total to 4 for level 0
=> Add automatic "Detect psionics" to psion class

data/35e/wizards_of_the_coast/rsrd/monsters/rsrd_classes_monsters_specific.lst
an incomplete bonus is used ("C"), changed to classlevel()
=> combat bonus use classlevel instead of "C"

data/pathfinder/paizo/roleplaying_game/ultimate_combat/_ultimate_combat.pcc
Removed the wrong line from _ultimate_combat.pcc, that forced PCGen to interpret support/uc_abilitzcategories_um.lst file as an ABILITY list instead of ABILITYCATEGORY.
Moved the line to the top position.
@BlyatBeauty, this is your DATA, I guess, so you should agree with me :) Probably you overlooked this line.
=> DATA-4314 - Fix #2

code/src/resources/pcgen/lang/LanguageBundle.properties, code/src/resources/pcgen/lang/LanguageBundle_es.properties, code/src/resources/pcgen/lang/LanguageBundle_fr.properties, code/src/resources/pcgen/lang/LanguageBundle_it.properties, code/src/testResources/pcgen/lang/cleaned.properties
Some menu items use, or don't use mnemonics, and now the *.property resources look more consistent.
=> Updated version of CODE-3526

code/testsuite/csheets/35e_Bard.xml, code/testsuite/csheets/35e_Bob.xml, code/testsuite/csheets/35e_Charlie.xml, code/testsuite/csheets/35e_CloudGiantHalfDragon.xml, code/testsuite/csheets/35e_Dave.xml, code/testsuite/csheets/35e_Eve.xml, code/testsuite/csheets/35e_Fran.xml, code/testsuite/csheets/35e_Gordon.xml, code/testsuite/csheets/35e_Harold.xml, code/testsuite/csheets/35e_Ivan.xml, code/testsuite/csheets/35e_Jango.xml, code/testsuite/csheets/35e_JimDop.xml, code/testsuite/csheets/35e_Lauren.xml, code/testsuite/csheets/35e_Mallory.xml, code/testsuite/csheets/35e_Q-PsiCrystal.xml, code/testsuite/csheets/35e_Quasvin.xml, code/testsuite/csheets/3e_BarJack.xml, code/testsuite/csheets/3e_BrdJoe.xml, code/testsuite/csheets/3e_CleElf.xml, code/testsuite/csheets/3e_FigFae.xml, code/testsuite/csheets/3e_MonKee.xml, code/testsuite/csheets/3e_SWizSam.xml, code/testsuite/csheets/3e_WizShar.xml, code/testsuite/csheets/msrd_Ilyana.xml, code/testsuite/csheets/pf_Cleric.xml, code/testsuite/csheets/pf_Paladin.xml
This long PR fixes approximately 26 XML files located in /csheets folder. There are multiple reasons, why this was needed:
1. in the base template, a trailing /t/t was removed, and this change affected all templates
2. A long time ago FEAT and TEMPLATE tokens were replaced withe FEATHIT/-DAMAGE and TEMPLATEHIT/-DAMAGE (appeared somewhere in 2015)
3. The deity tag was removed for an MSRD character, because she doesn't have deity in the rule book.
p.s. not all characters were updated, because for some of them big blocks of data was modified. I need some time to investigate, why this change appeared.
You can squash this PR to a single commit.
=> Updated expected templates (csheet files)

code/src/java/pcgen/gui2/prefs/OutputPanel.java
This happens because the underlying code works in Swing threads only. Now the entire content of the panel is running in JavaFX thread.
Few empty lines were also removed.
As a symptom, the user sees the error in the logs:
```
023-07-10T00:10:47.285913900 SEVERE JavaFX Application Thread LoggingUncaughtExceptionHandler:32 Uncaught error on thread  Thread[JavaFX Application Thread,5,main] - ignoring
pcgen.gui3.GuiAssertions$WrongThreadException: expected NOT to be on JavaFX thread - actually on: JavaFX Application Thread
at pcgen.gui3.GuiAssertions.assertIsNotJavaFXThread(GuiAssertions.java:59)
at pcgen.gui3.GuiUtility.runOnJavaFXThreadNow(GuiUtility.java:56)
at pcgen.gui2.prefs.OutputPanel.onOutputSheetHTMLDefaultButton(OutputPanel.java:291)
at …
```
=> Fixed a bug, when the OutputPanel couldn't show the file chooser dialog

code/src/java/plugin/exporttokens/PortraitToken.java, code/src/test/pcgen/io/ExportHandlerTest.java, code/src/test/pcgen/util/TestHelper.java, code/src/test/plugin/exporttokens/BioTokenTest.java, code/src/test/plugin/exporttokens/CampaignHistoryTokenTest.java, code/src/test/plugin/exporttokens/PortraitTokenTest.java
It breaks the image export. In addition to this change, other changes were added:
- PortraitTokenTest now uses JUnit5 assertions
- TestHelper got a helper method "evaluateToken", that was used by other test-classes. This is a small refactoring to avoid the duplicated code;
- The token object is final;
- Trimmed spaces in the modified files.
=>  OS-538: Solved the bug, when PortraitToken path was encoded

code/src/java/pcgen/cdom/facet/fact/RegionFacet.java
Some code in the `RegionFacet#updateRegion` method was in danger of throwing a run-time `NoSuchElementException`, this patch introduces a fix.
=> Prevent run time exception when region update occurs

.run/Main.run.xml, README.md, code/src/java/pcgen/cdom/enumeration/SkillArmorCheck.java, code/src/java/pcgen/cdom/facet/analysis/MovementResultFacet.java, code/src/java/pcgen/core/PlayerCharacter.java, code/src/java/pcgen/gui3/component/PCGenToolBar.java
Fixed the house rule to ignore load (from equipment such as armor) with AC and movement
=> Fix code 3533

code/src/java/pcgen/cdom/facet/analysis/LoadFacet.java, code/src/java/pcgen/core/PlayerCharacter.java
Encumbrance now always shows as light
=> Fix code 3534

build.gradle, code/gradle/reporting.gradle, code/src/java/pcgen/base/test/InequalityTester.java, code/src/java/pcgen/gui2/converter/UnstretchingGridLayout.java, code/src/java/pcgen/gui2/filter/FilterBar.java, code/src/java/pcgen/gui2/tabs/summary/ClassLevelTableModel.java, code/standards/ruleset.xml
@karianna, I have prepared this PR with a small update. Can you please review it?
Please merge the changes, and don't rebase them.
p.s. I made a typo in one of the commit messages, I have updated Java to 21.0.5, and not to 21.0.4.
=> Java update from 21.0.4 to 21.0.5 including different depenndencies

code/src/java/pcgen/core/SystemCollections.java, code/src/java/pcgen/facade/core/CharacterFacade.java, code/src/java/pcgen/facade/core/SourceSelectionFacade.java, code/src/java/pcgen/facade/util/ReferenceFacade.java, code/src/java/pcgen/gui2/PCGenFrame.java, code/src/java/pcgen/gui2/facade/CharacterFacadeImpl.java, code/src/java/pcgen/system/CharacterManager.java, code/src/java/pcgen/system/FacadeFactory.java, code/src/java/pcgen/system/PropertyContext.java, code/src/java/pcgen/system/RecentFileList.java, code/src/java/pcgen/util/Logging.java
This feature is incomplete, because it is not configurable.
I have created it, because one of users from Discord asked a longer list.
Here are other changes:
Massive refactoring of PropertyContext.java and switching to Java's Optional and Streams if possible. Slightly reduced the dependency to Apache Commons.
Resolved many warnings suggested by IDEA and SonarLint.
@karianna 
Please merge this PR (if you accept it), after you merge PR #7221, because you will likely get errors from PMD.
=> CODE-3531: increased the number of recent files from 8 to 20

outputsheets/d20/5e/htmlxml/common/common-spells.ftl, preview/d20/5e/Standard.htm.ftl, preview/d20/5e/common/common-spells.ftl
Adding a new spiffy Spell Slot Tracker so that players can check off spell slots as they use them. Automatically figures out and displays boxes for the appropriate number of spell slots a player is entitled to.
=> Spell Slot Tracker

data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_equip_arms_armor.lst
This fixes [DATA-4370](https://pcgenorg.atlassian.net/browse/DATA-4370) by adding `RANGE:10` to all the improvised thrown weapons added in commit https://github.com/PCGen/pcgen/commit/45ab44c2d7dc15fc0059805111af0e097baf924
[DATA-4370]: https://pcgenorg.atlassian.net/browse/DATA-4370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(fix): Adding range to Improvised Thrown Weapns (fix for DATA-4370)

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/io/exporttoken/Token.java
export sheets can now include TOKEN.INFO.TAG type tokens so export the TAG labeled INFO value from the TOKEN map. e.g. RACE.INFO.SOME_LABEL to export the value of the 'SOME_LABEL' tag from the pc's associated race token map.
=> support for INFO token export

code/src/java/pcgen/core/GameMode.java, code/src/java/pcgen/core/term/PCCasterLevelTotalTermEvaluator.java, code/src/java/pcgen/io/ExportHandler.java, code/src/java/pcgen/io/exporttoken/Token.java
SPROP was not correctly evaluating CASTERLEVEL for use in variable replacement - it was always 0 (which was treated as empty).  Now the term will be the total caster level across all classes.
=> CASTERLEVEL SPROP fix

code/src/java/pcgen/cdom/facet/AddedTemplateFacet.java, code/src/java/plugin/lsttokens/TemplateLst.java
Added some logs - they trigger if a data file has an invalid template item (The TemplateLst.java change) or as specified in CODE-103, a CHOOSE token is specified that has no corresponding template.
One limitation - if a CHOOSE token is VALID, but not REFERENCED, we can't detect it this way. that would require a recursive lookup to check if the valid token is also being accessed in the source and template and character - not easy, not consistent across systems, and not performant without fundamentally changing how the CDOM works.
=> Added logging to catch invalid CHOOSE options

code/src/java/pcgen/gui2/tabs/SkillInfoTab.java
A renderer was being created that wasn't returning a usable TableCellRenderer.  By not registering a "custom" renderer, the default provided by JSpinner is used -- and that one works fine.
There are other references to the SpinnerRenderer that I have not touched but which also may need to be updated.  They are:
* PostLevelUpDialog.java:53
* PostLevelUpDialog.java:134
* EquipmentModels.java:378
* EquipmentModels.java:487
* StatTableModel.java:325
I'd like some eyeballs on both this patch and those other references.  I don't know how to get PCGen through those other code paths, so someone more familiar with PCGen should take a look at those areas to see if the spinners are working properly.
=> Fix for empty Ranks column on the Skills tab
